query POAMItemList {
  poamItems {
    edges {
      node {
        id
        poam_id
        name
        description
        related_risks {
          edges {
            node {
              id
              created
              modified
              labels {
                id
                name
                color
                description
              }
              deadline
              risk_status
              characterizations {
                ... on VulnerabilityCharacterization {
                  id
                  vulnerability_id
                  facets {
                    id
                    name
                    value
                  }
                }
                ... on RiskCharacterization {
                  id
                  risk
                  risk_state
                  likelihood
                  impact
                  facets {
                    id
                    name
                    value
                  }
                }
                ... on GenericCharacterization {
                  id
                  facets {
                    id
                    name
                    value
                  }
                }
              }
              remediations {
                response_type
                lifecycle
              }
            }
          }
        }
        related_observations {
          edges {
            node {
              name
              subjects {
                subject_type
                subject {
                  ... on OscalParty {
                    id
                    name
                    party_type
                  }
                  ... on Component {
                    id
                    name
                    component_type
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}