query POAMRiskList {
  poam(id: "0000") {
    id
    risks {
      edges {
        node {
          id
          created
          modified
          labels {
            id
            name
            color
            description
          }
          deadline
          risk_status
          characterizations {
            ... on VulnerabilityCharacterization {
              id
              vulnerability_id
              facets {
                id
                name
                value
              }
            }
            ... on RiskCharacterization {
              id
              risk
              risk_state
              likelihood
              impact
              facets {
                id
                name
                value
              }
            }
            ... on GenericCharacterization {
              id
              facets {
                id
                name
                value
              }
            }
          }
          remediations {
            response_type
            lifecycle
          }
          related_observations {
            edges {
              node {
                name
                subjects {
                  subject_type
                  subject {
                    ... on OscalParty {
                      name
                      party_type
                    }
                    ... on Component {
                      name
                      component_type
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}