query RiskItemRemediationDetails {
  riskResponse(id: "ac5a1fdb-23fd-4e43-9b8d-7a7897ba91a8") {
    id
    name                # Title
    description         # Description
    created             # Created
    modified            # Last Modified
    lifecycle           # Lifecycle
    response_type       # Response Type
    origins{            # Detection Source
      id
      origin_actors {
        actor_type
        actor_ref {
          ... on AssessmentPlatform {
            id
            name
          }
          ... on Component {
            id
            component_type
            name          # Source
          }
          ... on OscalParty {
            id
            party_type
            name            # Source
          }
        }
      }
    }
    required_assets(first: 5) {   # Required Resources
      edges {
        node {
          id
          subjects {
            subject {
              ... on InventoryItem {
                id
                asset_type
                name   # Required Resource
              }
              ... on Component{
                id
                component_type
                name    # Required Resource
              }
              ... on OscalParty {
              id
              party_type
              name      # Required Resource
              }
            }
          }
        }
      }
    }
    tasks(first: 5) {             # Related Tasks
      edges {
        node {
          id
          created
          modified
          labels {
            id
            name
            color
            description
          }
          task_type
          name
          description
          timing {
            ... on DateRangeTiming {
              start_date          # Start Date
              end_date            # End Date
            }
            ... on OnDateTiming {
              on_date             # Start Date
            }
          }
          task_dependencies(first: 5) {
            edges {
              node {
                id
                name
              }
            }
          }
          responsible_roles {
            id
            created
            modified
            labels {
              id
              name
              color
              description
            }
            role {
              id
              created
              modified
              role_identifier
              name
            }
          }
        }
      }
    }
    external_references {
      id
      created
      modified
      external_id     # external id
      source_name     # Title
      description     # description
      url             # URL
      media_type      # Media Type
    }
    notes {
      id
      abstract
      content
      authors
      labels {
        id
        name
        color
        description
      }
    }
  }
}