query RiskItemAnalysis {
  risk(id: "d67ba9c2-9421-4e3e-ba6c-8a3ab382dc3a") {
    id
    created
    modified
    characterizations {
      ... on VulnerabilityCharacterization {
        id
        origins{
          id
          origin_actors {
            actor_type
            actor_ref {
              ... on AssessmentPlatform {
                id
                name
              }
              ... on Component {
                id
                component_type
                name          # Detection Source
              }
              ... on OscalParty {
                id
                party_type
                name            # Detection Source
              }
            }
          }
        }
        vulnerability_id
        exploitability
        exploitability
        severity
        cvss3_vector_string
        cvss3_base_score
        cvss3_temporal_score
        cvss3_environmental_score
        cvss2_vector_string
        cvss2_base_score
        cvss2_temporal_score
        cvss2_environmental_score
        score_rationale
        facets {
          id
          risk_state
          name            # Characterization Name
          value           # Characterization Value
        }
      }
      ... on RiskCharacterization {
        id
        origins{
          id
          origin_actors {
            actor_type
            actor_ref {
              ... on AssessmentPlatform {
                id
                name
              }
              ... on Component {
                id
                component_type
                name          # Detection Source
              }
              ... on OscalParty {
                id
                party_type
                name            # Detection Source
              }
            }
          }
        }
        risk
        likelihood
        impact
        facets {
          id
          risk_state
          name            # Characterization Name
          value           # Characterization Value
        }
      }
    }
    external_references {
      id
      created
      modified
      external_id     # external id
      source_name     # Title
      description     # description
      url             # URL
      media_type      # Media Type
    }
    notes {
      id
      abstract
      content
      authors
      labels {
        id
        name
        color
        description
      }
    }
  }
}