type Catalog implements InternalObject & BasicObject {
  id: ID!
  entity_type: String!
  representative: Representative!
  standard_id: String!
  parent_types: [String!]!
  metrics:[Metric]
  # Catalog
  name: String!
  description: String!
  contracts: [String!]! # JSON.Stringified GraphqlCatalogContract items
}

type ExtendedContract {
  catalog_id: String!
  contract: String! # JSON.Stringified GraphqlCatalogContract items
}

# Ordering
enum CatalogsOrdering {
  name
  _score
}

# Relay connections
type CatalogConnection {
  pageInfo: PageInfo!
  edges: [CatalogEdge!]!
}
type CatalogEdge {
  cursor: String!
  node: Catalog!
}

# Queries
type Query {
  # Returns only the latest compatible version of each contract for
  # backwards compatibility.
  catalog(id: String!): Catalog @auth(for: [INGESTION])
  # Returns only the latest compatible version of each contract for
  # backwards compatibility.
  catalogs: [Catalog!]! @auth(for: [INGESTION])
  # Returns only the latest compatible version for backwards compatibility.
  contract(slug: String!): ExtendedContract @auth(for: [INGESTION])
}
