apiVersion: 1

datasources:
  - name: Prometheus
    uid: opencti-prometheus
    type: prometheus
    access: proxy
    url: http://opencti-dev-telemetry-prometheus:9090
    isDefault: true
    editable: true
