enum UsersOrdering {
  name
  user_email
  firstname
  lastname
  language
  external
  created_at
  updated_at
  _score
}

type UserConnection {
  pageInfo: PageInfo!
  edges: [UserEdge!]!
}

type UserEdge {
  cursor: String!
  node: User!
}

type OtpElement {
  secret: String!
  uri: String!
}

type ApiToken {
  id: ID!
  name: String
  created_at: DateTime
  expires_at: DateTime
  masked_token: String
  last_used_at: DateTime
}

type TokenGenerated {
  token_id: String!
  plaintext_token: String!
  expires_at: DateTime
  masked_token: String!
}

input UserTokenAddInput {
  name: String!
  duration: TokenDuration!
}

type User implements BasicObject & InternalObject {
  id: ID! # internal_id
  standard_id: String!
  entity_type: String!
  representative: Representative!
  parent_types: [String!]!
  metrics:[Metric]
  # User
  user_email: String!
  api_tokens: [ApiToken!]! @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  personal_notifiers: [Notifier!]
  individual_id: String
  name: String!
  description: String
  firstname: String
  otp_activated: Boolean
  otp_qr: String
  otp_mandatory: Boolean
  password_valid_until: DateTime
  user_service_account: Boolean
  lastname: String
  theme: String
  language: String
  external: Boolean
  roles(
    orderBy: RolesOrdering
    orderMode: OrderingMode
  ): [Role!]!
  capabilities: [Capability]!
  capabilitiesInDraft: [Capability]!
  default_hidden_types: [String!]!
  user_confidence_level: ConfidenceLevel
  effective_confidence_level: EffectiveConfidenceLevel
  no_creators: Boolean
  restrict_delete: Boolean
  groups(
    orderBy: GroupsOrdering
    orderMode: OrderingMode
  ): GroupConnection @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  objectOrganization(
    first: Int
    orderBy: OrganizationsOrdering
    orderMode: OrderingMode
  ): OrganizationConnection @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  objectAssignedOrganization(
    first: Int
    orderBy: OrganizationsOrdering
    orderMode: OrderingMode
  ): OrganizationConnection @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  created_at: DateTime!
  updated_at: DateTime!
  refreshed_at: DateTime
  sessions: [SessionDetail] @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  default_time_field: String
  account_status: String! @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  account_lock_after_date: DateTime @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  administrated_organizations: [Organization!]!
  unit_system: UnitSystem
  submenu_show_icons: Boolean
  submenu_auto_collapse: Boolean
  monochrome_labels: Boolean
  unsubscribed_news_feed_types: [String!]
  # Technical
  editContext: [EditUserContext!]
  creator: Creator
}

type MeUser implements BasicObject & InternalObject {
  id: ID! # internal_id
  standard_id: String!
  entity_type: String!
  representative: Representative!
  parent_types: [String!]!
  metrics:[Metric]
  user_email: String!
  name: String!
  description: String
  firstname: String
  otp_activated: Boolean
  otp_qr: String
  password_valid_until: DateTime
  lastname: String
  theme: String
  language: String
  external: Boolean
  individual_id: String
  api_tokens: [ApiToken!]!
  personal_notifiers: [Notifier!]
  objectOrganization: MeOrganizationConnection
  capabilities: [Capability!]!
  capabilitiesInDraft: [Capability!]!
  default_hidden_types: [String]!
  user_confidence_level: ConfidenceLevel
  effective_confidence_level: EffectiveConfidenceLevel
  no_creators: Boolean
  restrict_delete: Boolean
  allowed_marking: [MarkingDefinition!]
  default_marking: [DefaultMarking!]
  max_shareable_marking: [MarkingDefinition!]
  otp_mandatory: Boolean
  groups(
    orderBy: GroupsOrdering
    orderMode: OrderingMode
  ): GroupConnection
  default_dashboards: [Workspace!]!
  default_dashboard: Workspace
  default_time_field: String
  account_status: String!
  account_lock_after_date: DateTime
  administrated_organizations: [Organization!]!
  unit_system: UnitSystem
  submenu_show_icons: Boolean
  submenu_auto_collapse: Boolean
  monochrome_labels: Boolean
  unsubscribed_news_feed_types: [String!]
  can_manage_sensitive_config: Boolean
  draftContext: DraftWorkspace
}

type SessionDetail {
  id: ID!
  created: DateTime
  ttl: Int
  originalMaxAge: Int
}

type UserSession {
  user: Creator
  sessions: [SessionDetail]
}

input UserAddInput {
  user_email: String @constraint(minLength: 5, format: "email")
  name: String! @constraint(minLength: 2, format: "not-blank")
  password: String
  firstname: String
  lastname: String
  description: String
  language: String
  theme: String
  objectOrganization: [ID!]
  account_status: String
  account_lock_after_date: DateTime
  unit_system: String
  submenu_show_icons: Boolean
  submenu_auto_collapse: Boolean
  monochrome_labels: Boolean
  unsubscribed_news_feed_types: [String!]
  groups: [ID!]
  user_confidence_level: ConfidenceLevelInput
  prevent_default_groups: Boolean
  user_service_account: Boolean
  email_template_id: String
}

input SendUserMailInput {
  target_user_id: ID!
  email_template_id: ID!
}

input UserLoginInput {
  email: String!
  password: String!
}

input UserOTPLoginInput {
  code: String!
}

input UserOTPActivationInput {
  secret: String!
  code: String!
}

type UserEditMutations {
  delete: ID
  fieldPatch(input: [EditInput]!): User
  contextPatch(input: EditContext): User
  contextClean: User
  relationAdd(input: InternalRelationshipAddInput!): InternalRelationship
  relationDelete(toId: StixRef!, relationship_type: String!): User
  organizationAdd(organizationId: ID!): User
  organizationDelete(organizationId: ID!): User
}

extend type Query {
  me: MeUser! @auth
  otpGeneration: OtpElement @auth @allowUnprotectedOTP
  user(id: String!): User @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  users(
    first: Int
    after: ID
    orderBy: UsersOrdering
    orderMode: OrderingMode
    filters: FilterGroup
    search: String
    toStix: Boolean
  ): UserConnection @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  sessions: [UserSession] @auth(for: [SETTINGS_SETACCESSES])
  bookmarks(
    first: Int,
    after: ID,
    types: [String],
    orderBy: StixDomainObjectsOrdering
    orderMode: OrderingMode
    filters: FilterGroup
  ): StixDomainObjectConnection @auth(for: [KNOWLEDGE])
}

extend type Mutation {
  token(input: UserLoginInput): String @public @rateLimit(limit: 1, duration: 1) # Use for login
  otpActivation(input: UserOTPActivationInput): MeUser @auth @allowUnprotectedOTP
  otpDeactivation: MeUser @auth
  otpUserDeactivation(id: ID!): MeUser @auth(for: [SETTINGS_SETACCESSES])
  otpLogin(input: UserOTPLoginInput): Boolean @auth @rateLimit(limit: 1, duration: 1) @allowUnprotectedOTP
  userAdd(input: UserAddInput!): User @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  userEdit(id: ID!): UserEditMutations @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  userTokenAdd(input: UserTokenAddInput!): TokenGenerated! @auth(for: [APIACCESS_USETOKEN])
  userTokenRevoke(id: ID!): ID @auth(for: [APIACCESS_USETOKEN])
  userAdminTokenRevoke(userId: ID!, id: ID!): ID @auth(for: [SETTINGS_SETACCESSES])
  userAdminTokenAdd(userId: ID!, input: UserTokenAddInput!): TokenGenerated! @auth(for: [SETTINGS_SETACCESSES])
  meEdit(input: [EditInput]!, password: String): MeUser @auth
  bookmarkAdd(id: ID!, type: String!): StixDomainObject @auth(for: [KNOWLEDGE])
  bookmarkDelete(id: ID!): ID @auth(for: [KNOWLEDGE])
  sendUserMail(input: SendUserMailInput!): Boolean @auth(for: [SETTINGS_SETACCESSES, VIRTUAL_ORGANIZATION_ADMIN])
  logout: ID @auth @allowUnprotectedOTP
  sessionKill(id: ID!): ID @auth(for: [SETTINGS_SETACCESSES])
  userSessionsKill(id: ID!): [ID] @auth(for: [SETTINGS_SETACCESSES])
}

extend type Subscription {
  me: MeUser @auth
  user(id: ID!): User @auth(for: [SETTINGS_SETACCESSES])
}
