import {
  InvestigationAutonomousAction,
  InvestigationConfidenceLabel,
  InvestigationEvidenceCategory,
  InvestigationEvidenceKind,
  InvestigationRecommendationActionKind,
  InvestigationRecommendationPriority,
  InvestigationRecommendationStatus,
  InvestigationRunPhase,
  InvestigationRunStatus,
  InvestigationRunTrigger,
} from '../../../../src/generated/graphql';
import type { BasicStoreEntityInvestigationPolicy, BasicStoreEntityInvestigationRun } from '../../../../src/modules/investigationRun/investigationRun-types';

export const buildRun = (overrides: Partial<BasicStoreEntityInvestigationRun> = {}): BasicStoreEntityInvestigationRun => ({
  id: 'run-1',
  internal_id: 'run-1',
  standard_id: 'investigationrun--1',
  entity_type: 'InvestigationRun',
  parent_types: ['Basic-Object', 'Internal-Object'],
  name: 'Case Autopilot - Phishing wave',
  subject_id: 'incident-1',
  subject_type: 'Incident',
  case_id: null,
  case_ids: [],
  create_case: false,
  workspace_id: null,
  draft_id: 'draft-1',
  policy_id: 'policy-1',
  agent_slug: 'deep-investigation-agent',
  pack_id: 'opencti-case-investigation',
  xtm_investigation_id: 'inv-1',
  xtm_investigation_ids: ['inv-1'],
  xtm_revision: 3,
  xtm_status: 'running',
  budget_cancelled: false,
  run_trigger: InvestigationRunTrigger.Manual,
  run_status: InvestigationRunStatus.Running,
  run_phase: InvestigationRunPhase.Investigating,
  status_reason: null,
  started_at: '2026-10-01T10:00:00.000Z',
  completed_at: null,
  active_ms: 0,
  running_since: null,
  pending_work_ids: [],
  wave_started_at: null,
  validation_work_id: null,
  engine_failures: 0,
  run_as_id: 'user-1',
  goal_plan: null,
  steps: [],
  evidence: [
    { id: 'incident-1', investigation_id: 'inv-1', n: null, kind: InvestigationEvidenceKind.OpenctiObject, label: 'Phishing wave', opencti_id: 'incident-1', standard_id: 'incident--1', entity_type: 'Incident', in_draft: false, created: '2026-09-30T08:00:00.000Z' },
    { id: 'ip-1', investigation_id: 'inv-1', n: 1, kind: InvestigationEvidenceKind.OpenctiObject, label: '185.12.4.2', opencti_id: 'ip-1', standard_id: 'ipv4-addr--1', entity_type: 'IPv4-Addr', in_draft: true },
    { id: 'indicator-1', investigation_id: 'inv-1', n: null, kind: InvestigationEvidenceKind.OpenctiObject, label: "[domain-name:value = 'evil.example']", opencti_id: 'indicator-1', standard_id: 'indicator--1', entity_type: 'Indicator', in_draft: false },
    { id: 'inv-1:2', investigation_id: 'inv-1', n: 2, kind: InvestigationEvidenceKind.Url, label: 'Vendor write-up', href: 'https://vendor.example/apt28', quote: 'The C2 185.12.4.2 belongs to APT28', in_draft: false },
  ],
  hypotheses: [{
    candidate_id: 'apt28',
    candidate_standard_id: 'intrusion-set--28',
    candidate_name: 'APT28',
    candidate_type: 'Intrusion-Set',
    rationale: 'Shared infrastructure',
    evidence: [{
      evidence_id: 'ip-1',
      evidence_standard_id: 'ipv4-addr--1',
      evidence_type: 'IPv4-Addr',
      evidence_name: '185.12.4.2',
      category: InvestigationEvidenceCategory.InfrastructureOverlap,
      consistency: 2,
      weight: 0.95,
      diagnosticity: 1,
      rationale: 'Known C2 | reused',
    }],
    rank: 1,
    score: 0.5,
    inconsistency: 0,
    probability: 0.61,
    confidence: 61,
    confidence_label: InvestigationConfidenceLabel.Likely,
    explanation: 'Ranked 1 of 1 with a likely probability (61%).',
  }],
  timeline: [
    { ts: '2026-09-30T08:00:00.000Z', entity_id: 'incident-1', entity_type: 'Incident', name: 'Phishing wave', event: 'created' },
  ],
  recommendations: [{
    id: 'r1',
    course_of_action_id: null,
    text: 'Block 185.12.4.2 at the proxy',
    priority: InvestigationRecommendationPriority.P1,
    rationale: 'C2 server',
    action_kind: InvestigationRecommendationActionKind.Task,
    severity: null,
    approval_required: false,
    status: InvestigationRecommendationStatus.Proposed,
    task_id: null,
  }],
  analyst_feedback: [],
  approvals: [],
  enrichment_requests: [],
  enrichment_waves: [],
  budget: { max_iterations: 10, max_enrichment_jobs: 20, max_minutes: 60, used_iterations: 0, used_enrichment_jobs: 0, used_minutes: 0 },
  summary: 'The phishing wave is most likely APT28.',
  report: 'APT28 operates the C2 [2].',
  report_sources: [{ n: 2, label: 'Vendor write-up', href: 'https://vendor.example/apt28' }],
  outputs: { attributed_candidate_ids: [], observable_ids: {} },
  ...overrides,
}) as unknown as BasicStoreEntityInvestigationRun;

export const buildPolicy = (overrides: Partial<BasicStoreEntityInvestigationPolicy> = {}): BasicStoreEntityInvestigationPolicy => ({
  id: 'policy-1',
  internal_id: 'policy-1',
  entity_type: 'InvestigationPolicy',
  name: 'Default investigation policy',
  is_default: true,
  agent_slug: null,
  pack_id: null,
  pack_options: null,
  allowed_actions: Object.values(InvestigationAutonomousAction),
  enrichment_connector_ids: [],
  approval_connector_ids: ['connector-paid'],
  auto_approve_low_risk: true,
  auto_approve_min_confidence: 80,
  attribution_min_confidence: 55,
  max_iterations: 10,
  max_enrichment_jobs: 20,
  max_minutes: 60,
  trigger_on_case_rfi_creation: false,
  hypotheses_accepted: 0,
  hypotheses_rejected: 0,
  recommendations_accepted: 0,
  recommendations_rejected: 0,
  ...overrides,
}) as unknown as BasicStoreEntityInvestigationPolicy;
