import {
  InvestigationAutonomousAction,
  InvestigationConfidenceLabel,
  InvestigationEvidenceCategory,
  InvestigationEvidenceOrigin,
  InvestigationRecommendationActionKind,
  InvestigationRecommendationPriority,
  InvestigationRecommendationStatus,
  InvestigationRunPhase,
  InvestigationRunStatus,
  InvestigationRunTrigger,
} from '../../../../src/generated/graphql';
import type { BasicStoreEntityInvestigationPolicy, BasicStoreEntityInvestigationRun } from '../../../../src/modules/investigationRun/investigationRun-types';

export const buildRun = (overrides: Partial<BasicStoreEntityInvestigationRun> = {}): BasicStoreEntityInvestigationRun => ({
  id: 'run-1',
  internal_id: 'run-1',
  standard_id: 'investigationrun--1',
  entity_type: 'InvestigationRun',
  parent_types: ['Basic-Object', 'Internal-Object'],
  name: 'Case Autopilot - Phishing wave',
  subject_id: 'incident-1',
  subject_type: 'Incident',
  case_id: null,
  case_ids: [],
  workspace_id: null,
  draft_id: 'draft-1',
  policy_id: 'policy-1',
  agent_slug: 'opencti-case-autopilot',
  run_trigger: InvestigationRunTrigger.Manual,
  run_status: InvestigationRunStatus.Running,
  run_phase: InvestigationRunPhase.Planning,
  status_reason: null,
  iteration: 0,
  started_at: '2026-10-01T10:00:00.000Z',
  completed_at: null,
  active_ms: 0,
  running_since: null,
  pending_work_ids: [],
  wave_started_at: null,
  validation_work_id: null,
  agent_failures: 0,
  run_as_id: 'user-1',
  plan: [],
  steps: [],
  evidence: [
    { id: 'incident-1', standard_id: 'incident--1', entity_type: 'Incident', name: 'Phishing wave', origin: InvestigationEvidenceOrigin.Subject, in_draft: false, created: '2026-09-30T08:00:00.000Z' },
    { id: 'ip-1', standard_id: 'ipv4-addr--1', entity_type: 'IPv4-Addr', name: '185.12.4.2', origin: InvestigationEvidenceOrigin.Enrichment, in_draft: true },
    { id: 'indicator-1', standard_id: 'indicator--1', entity_type: 'Indicator', name: "[domain-name:value = 'evil.example']", origin: InvestigationEvidenceOrigin.Context, in_draft: false },
  ],
  hypotheses: [{
    candidate_id: 'apt28',
    candidate_standard_id: 'intrusion-set--28',
    candidate_name: 'APT28',
    candidate_type: 'Intrusion-Set',
    rationale: 'Shared infrastructure',
    evidence: [{
      evidence_id: 'ip-1',
      evidence_standard_id: 'ipv4-addr--1',
      evidence_type: 'IPv4-Addr',
      evidence_name: '185.12.4.2',
      category: InvestigationEvidenceCategory.InfrastructureOverlap,
      consistency: 2,
      weight: 0.95,
      diagnosticity: 1,
      rationale: 'Known C2 | reused',
    }],
    rank: 1,
    score: 0.5,
    inconsistency: 0,
    probability: 0.61,
    confidence: 61,
    confidence_label: InvestigationConfidenceLabel.Likely,
    explanation: 'Ranked 1 of 1 with a likely probability (61%).',
  }],
  timeline: [
    { ts: '2026-09-30T08:00:00.000Z', entity_id: 'incident-1', entity_type: 'Incident', name: 'Phishing wave', event: 'created' },
  ],
  recommendations: [{
    id: 'r1',
    course_of_action_id: null,
    text: 'Block 185.12.4.2 at the proxy',
    priority: InvestigationRecommendationPriority.P1,
    rationale: 'C2 server',
    action_kind: InvestigationRecommendationActionKind.Task,
    severity: null,
    approval_required: false,
    status: InvestigationRecommendationStatus.Proposed,
    task_id: null,
  }],
  analyst_feedback: [],
  approvals: [],
  enrichment_requests: [],
  budget: { max_tool_calls: 40, max_enrichment_jobs: 20, max_minutes: 60, used_tool_calls: 0, used_enrichment_jobs: 0, used_minutes: 0 },
  summary: 'The phishing wave is most likely APT28.',
  last_delta: null,
  ...overrides,
}) as unknown as BasicStoreEntityInvestigationRun;

export const buildPolicy = (overrides: Partial<BasicStoreEntityInvestigationPolicy> = {}): BasicStoreEntityInvestigationPolicy => ({
  id: 'policy-1',
  internal_id: 'policy-1',
  entity_type: 'InvestigationPolicy',
  name: 'Default Case Autopilot policy',
  is_default: true,
  agent_slug: null,
  allowed_actions: Object.values(InvestigationAutonomousAction),
  enrichment_connector_ids: [],
  approval_connector_ids: ['connector-paid'],
  auto_approve_low_risk: true,
  auto_approve_min_confidence: 80,
  attribution_min_confidence: 55,
  max_tool_calls: 40,
  max_enrichment_jobs: 20,
  max_minutes: 60,
  trigger_on_case_rfi_creation: false,
  hypotheses_accepted: 0,
  hypotheses_rejected: 0,
  recommendations_accepted: 0,
  recommendations_rejected: 0,
  ...overrides,
}) as unknown as BasicStoreEntityInvestigationPolicy;
