coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 80%
      critical_back:
        target: 100%
        paths: ["src/opencti-platform/opencti-graphql/src/database"]
        informational: true
      critical_front:
        target: 100%
        paths: ["src/opencti-platform/opencti-front/src/utils/hooks"]
        informational: true