coverage:
  status:
    patch:
      default:
        target: 80%
        informational: true
      opencti-front:
        target: 80%
        informational: true
      opencti-back-end:
        target: 80%
