kind: pipeline
name: opencti-tests

steps:
- name: api-tests
  image: nikolaik/python-nodejs:python3.8-nodejs12-alpine
  environment:
    APP__ADMIN__PASSWORD: admin
    APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
    GRAKN__HOSTNAME: grakn
    REDIS__HOSTNAME: redis
    ELASTICSEARCH__URL: http://elastic:9200
    MINIO__ENDPOINT: minio
  commands:
  - apk add build-base
  - cd opencti-platform/opencti-graphql
  - yarn install
  - yarn build
  - yarn test

- name: api-coverage
  image: plugins/codecov
  settings:
    token: e5c6fb05-76f7-4985-86cf-ff843d5d103e
    paths:
      - opencti-platform/opencti-graphql/coverage

- name: frontend-tests
  image: nikolaik/python-nodejs:python3.8-nodejs12-alpine
  commands:
  - cd opencti-platform/opencti-front
  - yarn install
  - yarn build
  - yarn test

- name: build-circleci
  image: wesleimp/drone-circleci
  when:
    branch:
    - master
  settings:
    token: 
      from_secret: circleci_token
    user: OpenCTI-Platform
    repo: opencti
    branch: master

services:
- name: grakn
  image: graknlabs/grakn:1.6.2
- name: redis
  image: redis:5.0.5
- name: elastic
  image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
  environment:
    discovery.type: single-node
    ES_JAVA_OPTS: -Xms750m -Xmx750m
- name: minio
  image: minio/minio:RELEASE.2019-10-12T01-39-57Z
  environment:
    MINIO_ACCESS_KEY: ChangeMe
    MINIO_SECRET_KEY: ChangeMe
  command: [ server, /data ]