kind: pipeline
name: opencti-tests

steps:
- name: api-tests
  image: nikolaik/python-nodejs:python3.9-nodejs15-alpine
  environment:
    APP__ADMIN__PASSWORD: admin
    APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
    REDIS__HOSTNAME: redis
    ELASTICSEARCH__URL: http://elastic:9200
    MINIO__ENDPOINT: minio
    RABBITMQ__HOSTNAME: rabbitmq
  commands:
  - apk add build-base git libffi-dev
  - cd opencti-platform/opencti-graphql
  - yarn install
  - yarn build
  - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
  - yarn test

- name: api-coverage
  image: plugins/codecov
  settings:
    token: e5c6fb05-76f7-4985-86cf-ff843d5d103e
    paths:
      - opencti-platform/opencti-graphql/coverage

- name: frontend-tests
  image: nikolaik/python-nodejs:python3.9-nodejs15-alpine
  commands: 
  - cd opencti-platform/opencti-front
  - yarn install
  - yarn build

- name: build-circleci
  image: curlimages/curl
  commands:
  - curl -X POST --data "branch=master" https://circleci.com/api/v1.1/project/github/OpenCTI-Platform/opencti/build?circle-token=$CIRCLECI_TOKEN
  environment:
    CIRCLECI_TOKEN:
      from_secret: circleci_token
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
      - tag

- name: build-circleci-release
  image: curlimages/curl
  commands:
  - curl -X POST --data "tag=$DRONE_TAG" https://circleci.com/api/v1.1/project/github/OpenCTI-Platform/opencti/build?circle-token=$CIRCLECI_TOKEN
  environment:
    CIRCLECI_TOKEN:
      from_secret: circleci_token
  when:
    event:
      - tag

services:
- name: redis
  image: redis:6.2.2
- name: elastic
  image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
  environment:
    discovery.type: single-node
    ES_JAVA_OPTS: -Xms750m -Xmx750m
- name: minio
  image: minio/minio:RELEASE.2021-04-22T15-44-28Z
  environment:
    MINIO_ACCESS_KEY: ChangeMe
    MINIO_SECRET_KEY: ChangeMe
  command: [ server, /data ]
- name: rabbitmq
  image: rabbitmq:3.8-management 
