---
kind: pipeline
name: opencti-tests

steps:
  - name: api-tests
    image: node:16.10.0-alpine
    environment:
      APP__BASE_URL: http://api-tests:4000/
      APP__ADMIN__PASSWORD: admin
      APP__SYNC_RAW_START_REMOTE_URI: http://opencti-raw-start:4100/graphql
      APP__SYNC_LIVE_START_REMOTE_URI: http://opencti-live-start:4200/graphql
      APP__SYNC_DIRECT_START_REMOTE_URI: http://opencti-direct-start:4300/graphql
      APP__SYNC_RESTORE_START_REMOTE_URI: http://opencti-restore-start:4400/graphql
      APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
      REDIS__HOSTNAME: redis
      ELASTICSEARCH__URL: http://elastic:9200
      MINIO__ENDPOINT: minio
      RABBITMQ__HOSTNAME: rabbitmq
      EXPIRATION_SCHEDULER__ENABLED: false
      SUBSCRIPTION_SCHEDULER__ENABLED: false
      SMTP__HOSTNAME: smtp.ethereal.email
      SMTP__PORT: 587
      SMTP__USERNAME: jennyfer.mraz@ethereal.email
      SMTP__PASSWORD: frhJ2mSPTfaEutpbug
      PYTHONUNBUFFERED: 1
    commands:
      - apk add build-base git libffi-dev python3
      - ln -sf python3 /usr/bin/python
      - python3 -m ensurepip
      - pip3 install --no-cache --upgrade pip setuptools
      - git clone https://github.com/OpenCTI-Platform/connectors.git opencti-connectors
      - cd opencti-platform/opencti-graphql
      - yarn install
      - yarn build
      - yarn lint
      - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
      - sleep 60
      - NODE_OPTIONS=--max_old_space_size=8192 yarn test

  - name: api-coverage
    image: plugins/codecov
    settings:
      token: e5c6fb05-76f7-4985-86cf-ff843d5d103e
      paths:
        - opencti-platform/opencti-graphql/coverage

  - name: frontend-tests
    image: nikolaik/python-nodejs:python3.10-nodejs16-alpine
    commands:
      - cd opencti-platform/opencti-front
      - yarn install
      - yarn build
      - yarn lint
      - NODE_OPTIONS=--max_old_space_size=8192 yarn test

  - name: build-circleci
    image: curlimages/curl
    commands:
      - curl -X POST --data "branch=master" https://circleci.com/api/v1.1/project/github/OpenCTI-Platform/opencti/build?circle-token=$CIRCLECI_TOKEN
    environment:
      CIRCLECI_TOKEN:
        from_secret: circleci_token
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
          - tag

  - name: build-circleci-release
    image: curlimages/curl
    commands:
      - curl -X POST --data "tag=$DRONE_TAG" https://circleci.com/api/v1.1/project/github/OpenCTI-Platform/opencti/build?circle-token=$CIRCLECI_TOKEN
    environment:
      CIRCLECI_TOKEN:
        from_secret: circleci_token
    when:
      event:
        - tag

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      username: drone
      icon_url: https://avatars.githubusercontent.com/oa/1284929
      channel: notifications
    when:
      status: [success, failure]
      event:
        exclude:
          - pull_request

services:
  - name: redis
    image: redis:7.0.4
  - name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      ES_JAVA_OPTS: -Xms2g -Xmx2g
  - name: minio
    image: minio/minio:RELEASE.2022-08-26T19-53-15Z
    environment:
      MINIO_ROOT_USER: ChangeMe
      MINIO_ROOT_PASSWORD: ChangeMe
    command: [server, /data]
  - name: rabbitmq
    image: rabbitmq:3.10-management
  - name: opencti-raw-start
    image: nikolaik/python-nodejs:python3.10-nodejs16-alpine
    environment:
      APP__PORT: 4100
      APP__ADMIN__PASSWORD: admin
      APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
      REDIS__HOSTNAME: redis
      REDIS__NAMESPACE: raw-start
      ELASTICSEARCH__URL: http://elastic:9200
      ELASTICSEARCH__INDEX_PREFIX: raw-start
      MINIO__ENDPOINT: minio
      MINIO__BUCKET_NAME: raw-start-bucket
      RABBITMQ__HOSTNAME: rabbitmq
      EXPIRATION_SCHEDULER__ENABLED: false
      SUBSCRIPTION_SCHEDULER__ENABLED: false
    commands:
      - sleep 30
      - apk add build-base git libffi-dev
      - cp -a opencti-platform /tmp/raw-start-platform
      - cd /tmp/raw-start-platform/opencti-graphql
      - yarn install
      - yarn install:python
      - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
      - NODE_OPTIONS=--max_old_space_size=8192 yarn start
  - name: opencti-live-start
    image: nikolaik/python-nodejs:python3.10-nodejs16-alpine
    environment:
      APP__PORT: 4200
      APP__ADMIN__PASSWORD: admin
      APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
      REDIS__HOSTNAME: redis
      REDIS__NAMESPACE: live-start
      ELASTICSEARCH__URL: http://elastic:9200
      ELASTICSEARCH__INDEX_PREFIX: live-start
      MINIO__ENDPOINT: minio
      MINIO__BUCKET_NAME: live-start-bucket
      RABBITMQ__HOSTNAME: rabbitmq
      EXPIRATION_SCHEDULER__ENABLED: false
      SUBSCRIPTION_SCHEDULER__ENABLED: false
    commands:
      - sleep 90
      - apk add build-base git libffi-dev
      - cp -a opencti-platform /tmp/live-start-platform
      - cd /tmp/live-start-platform/opencti-graphql
      - yarn install
      - yarn install:python
      - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
      - NODE_OPTIONS=--max_old_space_size=12288 yarn start
  - name: opencti-direct-start
    image: nikolaik/python-nodejs:python3.10-nodejs16-alpine
    environment:
      APP__PORT: 4300
      APP__ADMIN__PASSWORD: admin
      APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
      REDIS__HOSTNAME: redis
      REDIS__NAMESPACE: direct-start
      ELASTICSEARCH__URL: http://elastic:9200
      ELASTICSEARCH__INDEX_PREFIX: direct-start
      MINIO__ENDPOINT: minio
      MINIO__BUCKET_NAME: direct-start-bucket
      RABBITMQ__HOSTNAME: rabbitmq
      EXPIRATION_SCHEDULER__ENABLED: false
      SUBSCRIPTION_SCHEDULER__ENABLED: false
    commands:
      - sleep 60
      - apk add build-base git libffi-dev
      - cp -a opencti-platform /tmp/direct-start-platform
      - cd /tmp/direct-start-platform/opencti-graphql
      - yarn install
      - yarn install:python
      - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
      - NODE_OPTIONS=--max_old_space_size=12288 yarn start
  - name: opencti-direct-worker
    image: nikolaik/python-nodejs:python3.10-nodejs16-alpine
    environment:
      OPENCTI_URL: http://opencti-direct-start:4300
      OPENCTI_TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
      WORKER_LOG_LEVEL: info
    commands:
      - sleep 180
      - apk add build-base git libffi-dev
      - cp -a opencti-worker /tmp/direct-start-worker
      - cd /tmp/direct-start-worker
      - pip3 install -r src/requirements.txt
      - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
      - python3 src/worker.py
  - name: opencti-restore-start
    image: nikolaik/python-nodejs:python3.10-nodejs16-alpine
    environment:
      APP__PORT: 4400
      APP__ADMIN__PASSWORD: admin
      APP__ADMIN__TOKEN: bfa014e0-e02e-4aa6-a42b-603b19dcf159
      REDIS__HOSTNAME: redis
      REDIS__NAMESPACE: restore-start
      ELASTICSEARCH__URL: http://elastic:9200
      ELASTICSEARCH__INDEX_PREFIX: restore-start
      MINIO__ENDPOINT: minio
      MINIO__BUCKET_NAME: restore-start-bucket
      RABBITMQ__HOSTNAME: rabbitmq
      EXPIRATION_SCHEDULER__ENABLED: false
      SUBSCRIPTION_SCHEDULER__ENABLED: false
    commands:
      - sleep 120
      - apk add build-base git libffi-dev
      - cp -a opencti-platform /tmp/restore-start-platform
      - cd /tmp/restore-start-platform/opencti-graphql
      - yarn install
      - yarn install:python
      - pip3 install --upgrade --force --no-cache-dir git+https://github.com/OpenCTI-Platform/client-python@master
      - NODE_OPTIONS=--max_old_space_size=12288 yarn start
