---
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.31.0
  #   hooks:
  #     - id: yamllint
  - repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: yarn nx affected --base=origin/master --target lint-staged -- --diff="origin/master...HEAD"
        language: system
        pass_filenames: false
        stages: [pre-push, manual]
    -   id: verify-translation
        name: verify-translation (opencti-front)
        entry: yarn nx run opencti-front:verify-translation
        language: system
        files: \.[jt]sx?$
        pass_filenames: false
        stages: [pre-push, manual]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      # Excludes added so you can run against all files versus only changed files in your commit and not impact
      # files which you do not control or are not essential to be linted:
      #    pre-commit run --all-files
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
                .circleci/(.*)|
                .devcontainer/(.*)|
                .github/(.*)|
                yarn.lock|
                LICENSE|
                (.*)/requirements.txt|
                opencti-platform/.dockerignore|
                opencti-platform/opencti-graphql/static/(.*)|
                opencti-platform/opencti-front/src/static/(.*)|
                opencti-platform/opencti-front/packages/(.*)
          )$
      - id: requirements-txt-fixer
      # Excludes added so you can run against all files versus only changed files in your commit and not impact
      # files which you do not control or are not essential to be linted:
      #    pre-commit run --all-files
      - id: trailing-whitespace
        exclude: |
          (?x)^(
                .circleci/config.yml|
                .devcontainer/(.*)|
                .github/(.*)|
                yarn.lock|
                LICENSE|
                (.*)/requirements.txt|
                opencti-platform/.dockerignore|
                opencti-platform/opencti-graphql/static/(.*)|
                opencti-platform/opencti-front/src/static/(.*)|
                opencti-platform/opencti-front/packages/(.*)
          )$
