# .readthedocs.yaml
# Read the Docs configuration file for the Python client documentation
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the client-python/docs/ directory with Sphinx
sphinx:
  configuration: client-python/docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: client-python/requirements.txt
    - requirements: client-python/docs/requirements.txt

