approvedGitRepositories:
  - "**"

defaultSemverRangePrefix: ""

enableScripts: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@filigran/*"
