import './indicatorDecayManager';
import './garbageCollectionManager';
import './hubRegistrationManager';
import './xtmOneRegistrationManager';
import './telemetryManager';
import './retentionManager';
import './exclusionListCacheBuildManager';
import './exclusionListCacheSyncManager';
import './pirManager';
