# use pinned version
defaultSemverRangePrefix: ""

# ensure the best compatibility
nodeLinker: node-modules

# isolate node_modules per workspace package
nmHoistingLimits: workspaces

# security: scripts are not enabled by default and required individual activations in package.json
enableScripts: false

# security: NPM package younger than 3 days won't be considered for installation
npmMinimalAgeGate: 4320
