FROM node:22-alpine AS base


##############################
### Build builder
##############################

FROM base AS builder

# For layer optimisation, start by installing resources not dependant from source code
RUN set -eux; \
    apk add --no-cache g++ make python3 python3-dev; \
    npm install -g node-gyp; \
    npm install -g corepack

##############################
### Build back
##############################

FROM builder AS builder-back

# TAG_VERSION used to generate connector manifest on a tag during yarn build. Default to rolling manifest
ARG TAG_VERSION
ENV TAG_VERSION="${TAG_VERSION}"

WORKDIR /opt/opencti-build
COPY ../client-python ./client-python

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN set -eux; \
    ls -larth; \
    sleep 1; \
    apk add build-base git libffi-dev cargo; \
    pip3 install --upgrade setuptools; \
    cd "/opt/opencti-build/client-python"; \
    pip install -r requirements.txt; \
    pip install .[dev,doc]

WORKDIR /opt/opencti-build/opencti-graphql

# Copy sources necessary for install (preserve cache if no dependency changes)
COPY opencti-platform/opencti-graphql/package.json opencti-platform/opencti-graphql/yarn.lock opencti-platform/opencti-graphql/patch ./
COPY opencti-platform/opencti-graphql/patch/ ./patch/
COPY opencti-platform/.yarnrc.yml ./

RUN yarn install --immutable

# Copy all remaining sources
COPY opencti-platform/opencti-graphql/ ./
RUN yarn build


##############################
### Build front
##############################

FROM builder AS builder-front
WORKDIR /opt/opencti-build/opencti-front

# Copy sources necessary for install (preserve cache if no dependency changes)
COPY opencti-platform/opencti-front/package.json opencti-platform/opencti-front/yarn.lock ./
COPY opencti-platform/opencti-front/packages/ ./packages/
COPY opencti-platform/.yarnrc.yml ./

RUN set -eux; \
    ls -larth; \
    yarn install --immutable

# Copy all remaining sources
COPY opencti-platform/opencti-front/ ./
RUN set -eux; \
    ls -larth; \
    mkdir -p ../opencti-graphql/public; \
    yarn build


##############################
### Build the testing image
##############################


FROM builder AS testing

WORKDIR /opt/opencti

RUN apk add --no-cache tini python3 python3-dev libmagic

RUN set -eux; \
    apk add --no-cache gcc; \
    rm -f /usr/lib/python3.12/EXTERNALLY-MANAGED; \
    python3 -m ensurepip; \
    rm -rv /usr/lib/python*/ensurepip; \
    pip3 install --no-cache-dir --upgrade pip setuptools wheel; \
    ln -sf python3 /usr/bin/python; \
    apk del gcc

COPY --from=builder-back /opt/opencti-build/opencti-graphql/ ./
COPY --from=builder-front /opt/opencti-build/opencti-graphql/public/ ./public/

COPY --from=builder-back /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip3 install --no-cache-dir --requirement /opt/opencti/src/python/requirements.txt

ENV PYTHONUNBUFFERED="1"
ENV NODE_OPTIONS="--max_old_space_size=12288"

RUN set -eux; \
    install -m 0777 -d '/opt/opencti/logs'; \
    install -m 0777 -d '/opt/opencti/telemetry'; \
    install -m 0777 -d '/opt/opencti/.support'

VOLUME ["/opt/opencti/logs", "/opt/opencti/telemetry", "/opt/opencti/.support"]

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "build/back.js"]



