FROM node:24-alpine AS base


FROM base AS graphql-deps-builder

ARG TAG_VERSION
ENV TAG_VERSION=${TAG_VERSION}

WORKDIR /opt/opencti-build/opencti-graphql
COPY opencti-graphql/package.json opencti-graphql/yarn.lock ../.yarnrc.yml ./
COPY opencti-graphql/patch ./patch
RUN set -ex; \
    apk add --no-cache git tini gcc g++ make musl-dev cargo python3 python3-dev postfix postfix-pcre \
    && rm -f /usr/lib/python3.11/EXTERNALLY-MANAGED \
    && rm -f /usr/lib/python3.12/EXTERNALLY-MANAGED \
    && npm install -g node-gyp \
    && npm install -g corepack \
    && yarn install --immutable && yarn cache clean --all


FROM base AS graphql-builder

ARG TAG_VERSION
ENV TAG_VERSION=${TAG_VERSION}

WORKDIR /opt/opencti-build/opencti-graphql
COPY opencti-graphql/package.json opencti-graphql/yarn.lock ../.yarnrc.yml ./
COPY opencti-graphql/patch ./patch
RUN set -ex; \
    apk add --no-cache git tini gcc g++ make musl-dev cargo python3 python3-dev postfix postfix-pcre \
    && rm -f /usr/lib/python3.11/EXTERNALLY-MANAGED \
    && rm -f /usr/lib/python3.12/EXTERNALLY-MANAGED \
    && npm install -g node-gyp \
    && npm install -g corepack \
    && yarn install
COPY opencti-graphql /opt/opencti-build/opencti-graphql
RUN yarn build:prod

FROM base AS app

RUN set -ex; \
    apk add --no-cache git tini gcc g++ make musl-dev cargo python3 python3-dev postfix postfix-pcre; \
    rm -f /usr/lib/python3.11/EXTERNALLY-MANAGED; \
    rm -f /usr/lib/python3.12/EXTERNALLY-MANAGED; \
    python3 -m ensurepip; \
    rm -rv /usr/lib/python*/ensurepip; \
    pip3 install --no-cache-dir --upgrade pip setuptools wheel; \
    ln -sf python3 /usr/bin/python;
WORKDIR /opt/opencti
COPY opencti-graphql/src/python/requirements.txt ./src/python/requirements.txt
RUN pip3 install --no-cache-dir --requirement ./src/python/requirements.txt
RUN apk del git gcc musl-dev
COPY --from=graphql-deps-builder /opt/opencti-build/opencti-graphql/node_modules ./node_modules
COPY --from=graphql-builder /opt/opencti-build/opencti-graphql/build ./build
COPY --from=graphql-builder /opt/opencti-build/opencti-graphql/static ./static
COPY --from=graphql-builder /opt/opencti-build/opencti-graphql/public ./public
COPY opencti-graphql/src ./src
COPY opencti-graphql/config ./config
COPY opencti-graphql/script ./script

ENV PYTHONUNBUFFERED=1
ENV NODE_OPTIONS=--max_old_space_size=12288
ENV NODE_ENV=production

RUN set -ex; \
    install -m 0777 -d '/opt/opencti/logs' \
    && install -m 0777 -d '/opt/opencti/telemetry' \
    && install -m 0777 -d '/opt/opencti/.support'

VOLUME ["/opt/opencti/logs", "/opt/opencti/telemetry", "/opt/opencti/.support"]

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "build/back.js"]