FROM node:20-alpine AS base

ENV PYTHONUNBUFFERED=1
ENV NODE_OPTIONS=--max_old_space_size=12288
ENV NODE_ENV=production

RUN set -ex; \
    install -m 0777 -d '/opt/opencti/logs' \
    && install -m 0777 -d '/opt/opencti/telemetry' \
    && install -m 0777 -d '/opt/opencti/.support'

VOLUME ["/opt/opencti/logs", "/opt/opencti/telemetry", "/opt/opencti/.support"]

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "build/back.js"]