# syntax=docker/dockerfile:1.27
FROM filigran/alpine-python-nodejs-fips:python3.12-nodejs24 AS base
FROM node:24-alpine3.23 AS base-nonfips


##############################
### Build builder (non fips)
##############################

FROM base-nonfips AS builder-nonfips

# For layer optimisation, start by installing resources not dependant from source code
RUN <<EOT
  set -euxo pipefail

  apk --no-cache add make g++ python3 python3-dev
  rm -f /usr/lib/python*/EXTERNALLY-MANAGED
  python3 -m ensurepip
  npm install -g corepack
EOT

WORKDIR /opt/opencti

COPY .yarnrc.yml package.json yarn.lock ./
COPY patch/ ./patch/
COPY opencti-platform/eslint-plugin-custom-rules/package.json ./opencti-platform/eslint-plugin-custom-rules/
COPY opencti-platform/opencti-front/package.json ./opencti-platform/opencti-front/
COPY opencti-platform/opencti-graphql/package.json ./opencti-platform/opencti-graphql/

ENV YARN_ENABLE_IMMUTABLE_INSTALLS="true"


##############################
### Build back
##############################

FROM builder-nonfips AS builder-back

# TAG_VERSION used to generate connector manifest on a tag during yarn build. Default to rolling manifest
ARG TAG_VERSION
ENV TAG_VERSION="${TAG_VERSION}"

RUN yarn workspaces focus opencti-graphql

WORKDIR /opt/opencti/opencti-platform/opencti-graphql

# Copy all remaining sources
COPY opencti-platform/opencti-graphql/ ./
RUN yarn build:prod

##############################
### Build front
##############################

FROM builder-nonfips AS builder-front
RUN yarn workspaces focus opencti-front

WORKDIR /opt/opencti/opencti-platform/opencti-front

# Copy all remaining sources and build
COPY opencti-platform/opencti-front/ ./
RUN yarn build

##############################
### Build production image
##############################

FROM base AS app

RUN <<EOT
  set -euxo pipefail

  apk --no-cache add tini python3-dev
  rm -f /usr/lib/python*/EXTERNALLY-MANAGED
  rm /var/log/apk.log
EOT

RUN --mount=type=bind,source=opencti-platform/opencti-graphql/src/python/requirements.txt,target=/opt/opencti/src/python/requirements.txt <<EOT
  set -euxo pipefail

  apk --no-cache add -t .pip_deps git
  pip3 install --no-cache-dir --requirement /opt/opencti/src/python/requirements.txt
  apk del .pip_deps
  rm /var/log/apk.log
EOT

WORKDIR /opt/opencti

COPY --from=builder-back /opt/opencti/opencti-platform/opencti-graphql/build/ ./build/
COPY --from=builder-back /opt/opencti/opencti-platform/opencti-graphql/config/ ./config/
COPY --from=builder-back /opt/opencti/opencti-platform/opencti-graphql/src/python/runtime/ ./src/python/runtime/
COPY --from=builder-back /opt/opencti/opencti-platform/opencti-graphql/static/ ./static/
COPY --from=builder-front /opt/opencti/opencti-platform/opencti-front/dist/ ./public/

ENV PYTHONUNBUFFERED="1"
ENV NODE_OPTIONS="--max_old_space_size=12288"
ENV NODE_ENV="production"

RUN <<EOT
  set -euxo pipefail

  install -m 0777 -d '/opt/opencti/logs'
  install -m 0777 -d '/opt/opencti/telemetry'
  install -m 0777 -d '/opt/opencti/.support'
EOT

VOLUME ["/opt/opencti/logs", "/opt/opencti/telemetry", "/opt/opencti/.support"]

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "build/back.mjs"]
