FROM filigran/python-nodejs-fips:latest AS base

FROM base AS graphql-deps-builder

WORKDIR /opt/opencti-build/opencti-graphql
COPY opencti-graphql/package.json opencti-graphql/yarn.lock opencti-graphql/.yarnrc.yml ./
COPY opencti-graphql/.yarn ./.yarn
COPY opencti-graphql/patch ./patch
RUN set -ex; \
    apk add --no-cache git tini gcc g++ make musl-dev cargo postfix postfix-pcre gettext-dev \
    && npm install -g node-gyp \
    && yarn install --frozen-lockfile && yarn cache clean --all


FROM base AS graphql-builder

WORKDIR /opt/opencti-build/opencti-graphql
COPY opencti-graphql/package.json opencti-graphql/yarn.lock opencti-graphql/.yarnrc.yml ./
COPY opencti-graphql/.yarn ./.yarn
COPY opencti-graphql/patch ./patch
RUN set -ex; \
    apk add --no-cache git tini gcc g++ make musl-dev cargo postfix postfix-pcre gettext-dev \
    && npm install -g node-gyp \
    && yarn install
COPY opencti-graphql /opt/opencti-build/opencti-graphql
RUN yarn build:prod

FROM base AS app

RUN set -ex; \
    apk add --no-cache git tini gcc g++ make musl-dev cargo postfix postfix-pcre; \
    pip3 install --no-cache-dir --upgrade pip setuptools wheel;
WORKDIR /opt/opencti
COPY opencti-graphql/src/python/requirements.txt ./src/python/requirements.txt
RUN pip3 install --no-cache-dir --requirement ./src/python/requirements.txt
RUN apk del git gcc musl-dev
COPY --from=graphql-deps-builder /opt/opencti-build/opencti-graphql/node_modules ./node_modules
COPY --from=graphql-builder /opt/opencti-build/opencti-graphql/build ./build
COPY --from=graphql-builder /opt/opencti-build/opencti-graphql/static ./static
COPY --from=graphql-builder /opt/opencti-build/opencti-graphql/public ./public
COPY opencti-graphql/src ./src
COPY opencti-graphql/config ./config
COPY opencti-graphql/script ./script

ARG UID=10000
ARG GID=10001
ARG USERNAME="_opencti"

ENV PYTHONUNBUFFERED=1
ENV NODE_OPTIONS="--force-fips --max_old_space_size=12288"
ENV NODE_ENV=production

RUN set -ex \
    ; addgroup -g "${GID}" -S "${USERNAME}" \
    && adduser \
        -h /opt/opencti \
        -g "OpenCTI privsep user" \
        -s "/sbin/nologin" \
        -G "${USERNAME}" \
        -S \
        -u "${UID}" \
        "${USERNAME}" \
    && install -o "${UID}" -g "${GID}" -m 0755 -d '/opt/opencti/logs' \
    && install -o "${UID}" -g "${GID}" -m 0755 -d '/opt/opencti/telemetry' \
    && install -o "${UID}" -g "${GID}" -m 0755 -d '/opt/opencti/.support'

VOLUME ["/opt/opencti/logs", "/opt/opencti/telemetry", "/opt/opencti/.support"]

USER "${USERNAME}"

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "build/back.js"]
