FROM node:22-alpine AS base

FROM base AS builder

ARG TAG_VERSION
ENV TAG_VERSION=${TAG_VERSION}

# Get graphql dependencies for layer cache optimization
WORKDIR /opt/opencti-build/opencti-graphql
RUN apk add --no-cache g++ make musl-dev python3 python3-dev postfix-pcre
COPY opencti-graphql/patch ./patch
RUN npm install -g node-gyp
RUN npm install -g corepack
COPY opencti-graphql/package.json opencti-graphql/yarn.lock ../.yarnrc.yml ./
RUN yarn install --immutable

# Build graphql
COPY opencti-graphql /opt/opencti-build/opencti-graphql
RUN yarn build:prod

# Build front
WORKDIR /opt/opencti-build/opencti-front
COPY opencti-front ../.yarnrc.yml /opt/opencti-build/opencti-front
RUN yarn install
RUN yarn build

FROM base AS app

COPY opencti-graphql/src/python/requirements.txt /opt/opencti/src/python/requirements.txt
RUN apk add --no-cache tini python3 python3-dev postfix postfix-pcre
RUN set -ex; \
    apk add --no-cache --virtual build-dep gcc musl-dev; \
    rm -f /usr/lib/python3.12/EXTERNALLY-MANAGED; \
    python3 -m ensurepip; \
    rm -rv /usr/lib/python*/ensurepip; \
    pip3 install --no-cache-dir --upgrade pip setuptools wheel; \
    ln -sf python3 /usr/bin/python; \
    apk del build-dep
RUN set -ex; \
    pip3 install --no-cache-dir --requirement /opt/opencti/src/python/requirements.txt;

WORKDIR /opt/opencti

COPY --from=builder /opt/opencti-build/opencti-graphql/build ./build
COPY --from=builder /opt/opencti-build/opencti-graphql/static ./static
COPY --from=builder /opt/opencti-build/opencti-graphql/public ./public
COPY opencti-graphql/src ./src
COPY opencti-graphql/config ./config

ENV PYTHONUNBUFFERED=1
ENV NODE_OPTIONS=--max_old_space_size=12288
ENV NODE_ENV=production

RUN set -ex; \
    install -m 0777 -d '/opt/opencti/logs'; \
    install -m 0777 -d '/opt/opencti/telemetry'; \
    install -m 0777 -d '/opt/opencti/.support'

VOLUME ["/opt/opencti/logs", "/opt/opencti/telemetry", "/opt/opencti/.support"]

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["node", "build/back.js"]