---
name: Client Python bug 
title: "' ' "
labels: needs triage, client-python
description: Report a bug in the Python client.
assignees: " '' "
type: bug
body:
- type: textarea 
  attributes:
    label: "Please describe your bug: add environmenment, reproducible steps, Expected Output, Actual Output"

    
--- 
