---
name: Client Python bug 
title: "' ' "
labels: needs triage, client-python
assignees: " '' "
type: bug
body:
- type: textarea 
  attributes:
    label: Description
- type: textarea
    attributes:
      label: Environnment
- type: textarea
    attributes:
      label: Reproducible Steps
- type: textarea
    attributes:
      label: Expected Output
- type: textarea
    attributes:
      label: Actual Output
- type: textarea
    attributes:
      label: Additionnal information
--- 
