---
name: Client Python bug
description: Report a bug in the Python client.
title: "[BUG] <short summary>"
type: bug
labels:
  - needs triage
  - client-python
assignees: []
body:
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "Describe your environment: OpenCTI version, Python version, client version, etc."
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Reproducible Steps
      description: "List the steps needed to reproduce the issue."
      placeholder: |
        1. Do X  
        2. Call Y  
        3. Observe Z
  - type: textarea
    id: actual-outcome
    attributes:
      label: Actual Outcome
      description: "What actually happens?"
      placeholder: "Describe the incorrect behavior or error message."
  - type: textarea
    id: expected-outcome
    attributes:
      label: Expected Outcome
      description: "What did you expect to happen?"
      placeholder: "Describe the expected behavior."
  - type: textarea
    id: media
    attributes:
      label: Add any file, screenshots, video
      description: "Upload screenshots, videos, or log files."

---
