import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// Both pinned CAs are swapped for CAs generated by the test, whose keys sign the licenses below.
const anchors = vi.hoisted(() => ({ opencti: undefined as unknown, xtm: undefined as unknown }));
vi.mock('../../../../src/enterprise-edition/opencti_ca', () => ({
  get OPENCTI_CA() {
    return anchors.opencti;
  },
}));
vi.mock('../../../../src/enterprise-edition/xtm_ca', () => ({
  get XTM_CA() {
    return anchors.xtm;
  },
}));

import conf from '../../../../src/config/conf';
import { getEnterpriseEditionInfo } from '../../../../src/modules/settings/licensing';
import { setCurrentXtmLicenseProof } from '../../../../src/modules/xtm/one/xtm-one-license';
import { isEnterpriseEditionFromSettings } from '../../../../src/enterprise-edition/ee';
import { PlatformEeSource } from '../../../../src/generated/graphql';
import type { BasicStoreSettings } from '../../../../src/types/settings';
import { createTestCertificateAuthority, createTestXtmLicense, DAY } from '../../../utils/xtmLicenseHelper';

const openctiCa = createTestCertificateAuthority();
anchors.opencti = openctiCa.certificate;
const xtmCa = createTestCertificateAuthority();
anchors.xtm = xtmCa.certificate;
const foreignCa = createTestCertificateAuthority();

const PLATFORM_ID = 'platform-0001';
const settings = (overrides: Partial<BasicStoreSettings> = {}) => ({
  id: 'settings--0001',
  internal_id: PLATFORM_ID,
  created_at: new Date(Date.now() - 365 * DAY),
  enterprise_license: undefined,
  ...overrides,
} as unknown as BasicStoreSettings);
const ownLicense = (options = {}) => createTestXtmLicense(openctiCa, { product: 'opencti', openctiIds: null, platform: 'global', customer: 'Own customer', ...options });
// What the settings cache stores and every backend Enterprise Edition check (isEnterpriseEdition) reads.
const settingsCacheEnterpriseEdition = (platformSettings: BasicStoreSettings) => isEnterpriseEditionFromSettings({
  valid_enterprise_edition: getEnterpriseEditionInfo(platformSettings).license_validated,
});

describe('getEnterpriseEditionInfo: the one Enterprise Edition decision', () => {
  beforeEach(() => {
    const confGet = conf.get.bind(conf);
    // Whatever the environment says: the licenses come from the settings of each test.
    vi.spyOn(conf, 'get').mockImplementation((key?: string) => (key === 'app:enterprise_edition_license' ? undefined : confGet(key)));
    setCurrentXtmLicenseProof(null);
  });

  afterEach(() => {
    vi.restoreAllMocks();
    vi.useRealTimers();
  });

  it('is the Community Edition without any license', () => {
    const edition = getEnterpriseEditionInfo(settings());
    expect(edition.license_validated).toBe(false);
    expect(edition.license_source).toBe(PlatformEeSource.OpenctiLicense);
    expect(settingsCacheEnterpriseEdition(settings())).toBe(false);
  });

  it('is the full Enterprise Edition when a verified XTM license sub-licenses the platform', () => {
    const notAfter = new Date(Date.now() + 200 * DAY);
    setCurrentXtmLicenseProof(createTestXtmLicense(xtmCa, { openctiIds: ['global'], customer: 'XTM customer', notAfter }));

    const edition = getEnterpriseEditionInfo(settings());
    expect(edition).toMatchObject({
      license_enterprise: true,
      license_validated: true,
      license_source: PlatformEeSource.XtmOneLicense,
      license_customer: 'XTM customer',
      license_type: 'standard',
      license_global: true,
      license_expired: false,
      license_extra_expiration: false,
      license_by_configuration: false,
    });
    expect(new Date(edition.license_expiration_date).getTime()).toBe(Math.floor(notAfter.getTime() / 1000) * 1000);
    expect(settingsCacheEnterpriseEdition(settings())).toBe(true);
  });

  it('is the Enterprise Edition for a license listing this platform id, not another one', () => {
    setCurrentXtmLicenseProof(createTestXtmLicense(xtmCa, { openctiIds: [PLATFORM_ID] }));
    expect(getEnterpriseEditionInfo(settings()).license_global).toBe(false);
    expect(getEnterpriseEditionInfo(settings()).license_validated).toBe(true);
    expect(getEnterpriseEditionInfo(settings({ internal_id: 'platform-0002' })).license_validated).toBe(false);
  });

  it('keeps the Enterprise Edition during the 90 days of grace, flagged as expired', () => {
    setCurrentXtmLicenseProof(createTestXtmLicense(xtmCa, { notAfter: new Date(Date.now() - 10 * DAY) }));
    const edition = getEnterpriseEditionInfo(settings());
    expect(edition).toMatchObject({ license_validated: true, license_expired: true, license_extra_expiration: true });
    expect(edition.license_extra_expiration_days).toBe(79);
  });

  it.each([
    ['an expired license past its grace period', () => createTestXtmLicense(xtmCa, { notAfter: new Date(Date.now() - 91 * DAY) })],
    ['a license signed by another CA', () => createTestXtmLicense(foreignCa)],
    ['a missing certificate', () => null],
    ['an OpenCTI license instead of an XTM license', () => createTestXtmLicense(xtmCa, { product: 'opencti' })],
  ])('reverts to the Community Edition for %s', (_, proof) => {
    setCurrentXtmLicenseProof(proof());
    expect(getEnterpriseEditionInfo(settings()).license_validated).toBe(false);
    expect(settingsCacheEnterpriseEdition(settings())).toBe(false);
  });

  it('applies the certificate dates on every read', () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    setCurrentXtmLicenseProof(createTestXtmLicense(xtmCa, { type: 'trial', notAfter: new Date(Date.now() + 60 * 60 * 1000) }));
    expect(getEnterpriseEditionInfo(settings()).license_validated).toBe(true);

    vi.setSystemTime(Date.now() + 2 * 60 * 60 * 1000);
    expect(getEnterpriseEditionInfo(settings()).license_validated).toBe(false);
  });

  it('prefers the own OpenCTI license when both are valid, and leaves it unaffected', () => {
    setCurrentXtmLicenseProof(createTestXtmLicense(xtmCa, { customer: 'XTM customer' }));
    const edition = getEnterpriseEditionInfo(settings({ enterprise_license: ownLicense() }));
    expect(edition).toMatchObject({ license_validated: true, license_source: PlatformEeSource.OpenctiLicense, license_customer: 'Own customer' });

    setCurrentXtmLicenseProof(createTestXtmLicense(foreignCa));
    expect(getEnterpriseEditionInfo(settings({ enterprise_license: ownLicense() })).license_validated).toBe(true);
  });

  it('falls back to the XTM license when the own license is not valid', () => {
    setCurrentXtmLicenseProof(createTestXtmLicense(xtmCa, { customer: 'XTM customer' }));
    const expiredTrial = ownLicense({ type: 'trial', notAfter: new Date(Date.now() - DAY), notBefore: new Date(Date.now() - 30 * DAY) });
    const edition = getEnterpriseEditionInfo(settings({ enterprise_license: expiredTrial }));
    expect(edition).toMatchObject({ license_validated: true, license_source: PlatformEeSource.XtmOneLicense, license_customer: 'XTM customer' });
  });
});
