FROM registry.access.redhat.com/ubi10/ubi-minimal

COPY src /opt/opencti-worker

WORKDIR /opt/opencti-worker

RUN set -eux; \
    microdnf -y install python3 python3-devel python3-file-magic; \
    microdnf clean all; \
    pip3 install --no-cache-dir --requirement requirements.txt;

# RUN apk --no-cache add libmagic libffi-dev

ENTRYPOINT ["python3"]
CMD ["worker.py"]
