define

  so sub role # Generic STIX object

  # Attribution
  origin sub role # <Object> is origin of someshing
  attribution sub role # <Object> is attributed to something

  # Usage
  user sub role # <Object> is the user of something
  usage sub role #  <Object> is used by something

  # Indicating
  indicator sub role # <Object> is the indicator of something
  characterize sub role # <Object> is indicated by something

  # Targeting
  target sub role # <Object> is targeted by something
  source sub role # <Object> 

  # Reporting
  aggregate-knowledge sub role # <Object> is responsible to aggregate something

  # Marking
  marking sub role

  # Create
  creator sub role

  # Author
  author sub role

  stix_relation_embedded sub relationship
    is-abstract;

  stix_relation sub relationship
    is-abstract
    plays so
    has relationship_type;

  attributed_to sub stix_relation
    relates origin, relates attribution
    has event-date;

  uses sub stix_relation
    relates user, relates usage;

  indicates sub stix_relation
    relates indicator, relates characterize;

  targets sub stix_relation
    relates target, relates source;

  object_refs sub stix_relation_embedded
    relates aggregate-knowledge, relates so;

  object_marking_refs sub stix_relation_embedded
    relates marking, relates so;

  created_by_ref sub stix_relation_embedded
    relates creator, relates so;

  authored_by sub stix_relation_embedded
    relates author, relates so;

  User sub entity
    has email
    has name
    plays author;
 
  Stix-Domain sub entity
    is-abstract
    plays so
    #plays sdo
    has stix_id
    has creation-date;

  Identity sub Stix-Domain
    has name
    plays creator
    plays target
    plays origin;

  Indicator sub Stix-Domain
    has name
    plays indicator;

  Vulnerability sub Stix-Domain
    has name
    plays target;

  Intrusion-Set sub Stix-Domain
    has name
    plays user
    plays attribution;

  Campaign sub Stix-Domain
    has name
    plays user
    plays attribution;

  Malware sub Stix-Domain
    has name
    has description
    plays user
    plays usage;

  Tool sub Stix-Domain
    has name
    has description
    plays usage;
  
  Report sub Stix-Domain
    has name
    plays aggregate-knowledge;

  Threat-Actor sub Stix-Domain
    has name
    has description
    plays characterize
    plays origin
    plays source
    plays user;

  Attack-Pattern sub Stix-Domain
    has name
    has description
    plays user
    plays usage;

  Marking-Definition sub Stix-Domain
    has name
    plays marking;

  stix_id sub attribute, datatype string;
  name sub attribute, datatype string;
  email sub attribute, datatype string;
  description sub attribute, datatype string;
  event-date sub attribute, datatype date;
  creation-date sub attribute, datatype date;
  relationship_type sub attribute, datatype string;