SELECT DISTINCT ?rdf_type ?id ?object_type ?port_number ?protocols 
FROM <tag:stardog:api:context:named>
WHERE {
    {iri} a <http://scap.nist.gov/ns/asset-identification#Port> ;
        <http://darklight.ai/ns/common#id> ?id  ;
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?rdf_type  ;
        <http://scap.nist.gov/ns/asset-identification#port_number> ?port_number ;
        <http://scap.nist.gov/ns/asset-identification#protocols> ?protocols .
    OPTIONAL { {iri} <http://darklight.ai/ns/common#object_type> ?object_type } .
}
