SELECT DISTINCT ?iri ?rdf_type ?id ?object_type ?ip_address_value ?defanged ?stix_value
FROM <tag:stardog:api:context:named>
WHERE {
    ?iri a <http://scap.nist.gov/ns/asset-identification#IpV6Address> .
    OPTIONAL { ?iri <http://darklight.ai/ns/common#id> ?id  . }
    OPTIONAL { ?iri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?rdf_type } .
    OPTIONAL { ?iri <http://darklight.ai/ns/common#object_type> ?entity_type . }  
    OPTIONAL { ?iri <http://scap.nist.gov/ns/asset-identification#ip_address_value> ?ip_address_value } .
    OPTIONAL { ?iri <http://darklight.ai/ns/common#object_type> ?object_type } .
    OPTIONAL { ?iri <http://docs.oasis-open.org/ns/cti/stix#defanged> ?defanged } .
    OPTIONAL { ?iri <http://docs.oasis-open.org/ns/cti/stix/ip-address#value> ?stix_value } .
}
