SELECT DISTINCT ?iri ?rdf_type ?id ?object_type ?starting_port ?ending_port ?protocols 
FROM <tag:stardog:api:context:named>
WHERE {
    # BIND( <> as ?iri)
    ?iri a <http://scap.nist.gov/ns/asset-identification#PortRange> ;
    OPTIONAL { ?iri <http://darklight.ai/ns/common#id> ?id . }
    # OPTIONAL { ?iri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?rdf_type . }
    OPTIONAL { ?iri <http://darklight.ai/ns/common#object_type> ?object_type . }
    OPTIONAL { ?iri <http://scap.nist.gov/ns/asset-identification#starting_port> ?starting_port . }
    OPTIONAL { ?iri <http://scap.nist.gov/ns/asset-identification#ending_port> ?ending_port . }
    OPTIONAL { ?iri <http://scap.nist.gov/ns/asset-identification#protocols> ?protocols . }
}

