// eslint-disable-next-line
export const resolveLink = (type) => {
  switch (type) {
    case 'Attack-Pattern':
      return '/dashboard/ttps/attack_patterns';
    case 'Campaign':
      return '/dashboard/threats/campaigns';
    case 'Note':
      return '/dashboard/containers/notes';
    case 'Observed-Data':
      return '/dashboard/containers/observed_datas';
    case 'Opinion':
      return '/dashboard/containers/opinions';
    case 'Report':
      return '/dashboard/containers/reports';
    case 'Course-Of-Action':
      return '/dashboard/ttps/courses_of_action';
    case 'Individual':
      return '/dashboard/entities/individuals';
    case 'Organization':
      return '/dashboard/entities/organizations';
    case 'Sector':
      return '/dashboard/entities/sectors';
    case 'Indicator':
      return '/dashboard/ttps/indicators';
    case 'Infrastructure':
      return '/dashboard/ttps/infrastructures';
    case 'Intrusion-Set':
      return '/dashboard/threats/intrusion_sets';
    case 'City':
      return '/dashboard/entities/geo/cities';
    case 'Country':
      return '/dashboard/entities/geo/countries';
    case 'Region':
      return '/dashboard/entities/geo/regions';
    case 'Position':
      return '/dashboard/entities/geo/positions';
    case 'Malware':
      return '/dashboard/threats/malwares';
    case 'Threat-Actor':
      return '/dashboard/threats/threat_actors';
    case 'Tool':
      return '/dashboard/ttps/tools';
    case 'Vulnerability':
      return '/dashboard/entities/vulnerabilities';
    case 'XOpenCTIIncident':
      return '/dashboard/threats/incidents';
    case 'Stix-Cyber-Observable':
    case 'Autonomous-System':
    case 'Directory':
    case 'Domain-Name':
    case 'Email-Addr':
    case 'Email-Message':
    case 'Email-Mime-Part-Type':
    case 'Artifact':
    case 'File':
    case 'X509-Certificate':
    case 'IPv4-Addr':
    case 'IPv6-Addr':
    case 'Mac-Addr':
    case 'Mutex':
    case 'Network-Traffic':
    case 'Process':
    case 'Software':
    case 'Url':
    case 'User-Account':
    case 'Windows-Registry-Key':
    case 'Windows-Registry-Value-Type':
    case 'X509-V3-Extensions-Type':
    case 'X-OpenCTI-Cryptographic-Key':
    case 'X-OpenCTI-Cryptocurrency-Wallet':
    case 'X-OpenCTI-Text':
    case 'X-OpenCTI-User-Agent':
      return '/dashboard/signatures/observables';
    default:
      return null;
  }
};
