services:
  redis:
    container_name: redis
    image: redis:8.0.3
    restart: unless-stopped
    networks:
      - runner-docker-network
    ports:
      - 6379:6379
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - runner-docker-network
    ports:
      - 9200:9200
      - 9300:9300
  minio:
    container_name: minio
    image: minio/minio:latest
    networks:
      - runner-docker-network
    ports:
      - "9000:9000"
      - "9001:9001"
      - "35300:35300"
    environment:
      MINIO_ROOT_USER: ChangeMe
      MINIO_ROOT_PASSWORD: ChangeMe
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1-management
    restart: unless-stopped
    networks:
      - runner-docker-network
    ports:
      - 5672:5672
      - 15672:15672
  opencti-raw-start:
    container_name: opencti-raw-start
    image: filigran/platform:${TAG}
    restart: unless-stopped
    volumes:
      - /home/runner/work/opencti/opencti:/home/workspace
    networks:
      - runner-docker-network
    ports:
      - 4100:4100
  opencti-live-start:
    container_name: opencti-live-start
    image: filigran/platform:${TAG}
    restart: unless-stopped
    volumes:
      - /home/runner/work/opencti/opencti:/home/workspace
    networks:
      - runner-docker-network
    ports:
      - 4200:4100
  opencti-direct-start:
    container_name: opencti-direct-start
    image: filigran/platform:${TAG}
    restart: unless-stopped
    volumes:
      - /home/runner/work/opencti/opencti:/home/workspace
    networks:
      - runner-docker-network
    ports:
      - 4300:4100
  opencti-restore-start:
    container_name: opencti-restore-start
    image: filigran/platform:${TAG}
    restart: unless-stopped
    volumes:
      - /home/runner/work/opencti/opencti:/home/workspace
    networks:
      - runner-docker-network
    ports:
      - 4400:4100



networks:
  runner-docker-network:
    external: true