services:
  opencti-ci-redis:
    container_name: opencti-ci-redis
    image: redis:8.0.3
    restart: unless-stopped
    ports:
      - 6379:6379
  opencti-ci-elasticsearch:
    container_name: opencti-ci-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300
  opencti-ci-minio:
    container_name: opencti-ci-minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
      - "35300:35300"
    environment:
      MINIO_ROOT_USER: ChangeMe
      MINIO_ROOT_PASSWORD: ChangeMe
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
  opencti-ci-rabbitmq:
    container_name: opencti-ci-rabbitmq
    image: rabbitmq:4.1-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
