undefine

  #PermissionRule sub rule;
  AttributionUsesRule sub rule;
  AttributionTargetsRule sub rule;
  GatheringTargetsRule sub rule;
  LocalizationTargetsRule sub rule;
  LocalizationOfTargetsRule sub rule;
  AttributionAttributionRule sub rule;
  LocalizationLocalizationRule sub rule;