import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { graphql, useSubscription } from 'react-relay';
import Alert from '@mui/material/Alert';
import Tooltip from '@mui/material/Tooltip';
import parse from 'html-react-parser';
import { AISummaryHistorySubscription, AISummaryHistorySubscription$data } from '@components/common/ai/__generated__/AISummaryHistorySubscription.graphql';
import { GraphQLSubscriptionConfig } from 'relay-runtime';
import Divider from '@mui/material/Divider';
import Typography from '@mui/material/Typography';
import IconButton from '@common/button/IconButton';
import { AutoModeOutlined, ContentCopyOutlined } from '@mui/icons-material';
import { AISummaryHistoryStixCoreObjectAskAiHistoryQuery$data } from '@components/common/ai/__generated__/AISummaryHistoryStixCoreObjectAskAiHistoryQuery.graphql';
import { useFormatter } from '../../../../components/i18n';
import { getDefaultAiLanguage } from '../../../../utils/ai/Common';
import { fetchQuery } from '../../../../relay/environment';
import { copyToClipboard, cleanHtmlTags } from '../../../../utils/utils';
import { type AgentOption } from '../../../../utils/ai/agentApi';
import useAgentStream from '../../../../utils/ai/useAgentStream';
import { useChatbot } from '../../chatbox/ChatbotContext';
import XtmOneAISummaryDisplay from './XtmOneAISummaryDisplay';

const subscription = graphql`
    subscription AISummaryHistorySubscription($id: ID!) {
        aiBus(id: $id) {
            content
        }
    }
`;

const aISummaryHistoryQuery = graphql`
  query AISummaryHistoryStixCoreObjectAskAiHistoryQuery($id: ID!, $language: String, $forceRefresh: Boolean) {
      stixCoreObjectAskAiHistory(id: $id, language: $language, forceRefresh: $forceRefresh) {
        result
        updated_at
    }
  }
`;

interface AISummaryHistoryComponentProps {
  refetch: () => void;
  language: string;
  setLanguage: (language: string) => void;
  content: string;
  loading: boolean;
  result: AISummaryHistoryStixCoreObjectAskAiHistoryQuery$data | null;
}

const AISummaryHistoryComponent = ({
  refetch,
  content,
  result,
  loading,
}: AISummaryHistoryComponentProps) => {
  const { t_i18n, nsdt } = useFormatter();
  return (
    <>
      <Alert severity="info" variant="outlined" style={{ marginTop: 20 }}>
        {t_i18n('This summary is based on the history of this entity (internal activity). It has been generated by AI and can contain mistakes.')}
      </Alert>
      {parse(content)}
      {!loading && (
        <>
          <Divider />
          <div style={{ float: 'right', marginTop: 20, display: 'flex', alignItems: 'center', gap: '5px' }}>
            <Typography variant="caption">Generated on {nsdt(result?.stixCoreObjectAskAiHistory?.updated_at)}.</Typography>
            <Tooltip title={t_i18n('Copy to clipboard')}>
              <IconButton size="small" color="primary" onClick={() => copyToClipboard(t_i18n, content)}>
                <ContentCopyOutlined fontSize="small" />
              </IconButton>
            </Tooltip>
            <Tooltip title={t_i18n('Retry')}>
              <IconButton size="small" color="primary" onClick={() => refetch()}>
                <AutoModeOutlined fontSize="small" />
              </IconButton>
            </Tooltip>
          </div>
        </>
      )}
    </>
  );
};

interface AISummaryHistoryProps {
  id: string;
  loading: boolean;
  setLoading: (loading: boolean) => void;
  selectedAgent?: AgentOption | null;
}

const LegacyAISummaryHistory = ({ id, loading, setLoading }: AISummaryHistoryProps) => {
  const busId = `${id}-history`;
  const defaultLanguageName = getDefaultAiLanguage();
  const [content, setContent] = useState('');
  const [result, setResult] = useState<AISummaryHistoryStixCoreObjectAskAiHistoryQuery$data | null>(null);
  const [language, setLanguage] = useState(defaultLanguageName);

  // Subscription
  const handleResponse = (response: AISummaryHistorySubscription$data | null | undefined) => {
    const newContent = response ? (response as AISummaryHistorySubscription$data).aiBus?.content : null;
    const finalContent = cleanHtmlTags(newContent);
    return setContent(finalContent);
  };
  const subConfig = useMemo<GraphQLSubscriptionConfig<AISummaryHistorySubscription>>(
    () => ({
      subscription,
      variables: { id: busId },
      onNext: handleResponse,
    }),
    [busId],
  );
    // TODO: Check by the engineering team
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
  useSubscription(subConfig);

  // Query
  const queryParams = {
    busId,
    id,
    language,
  };
  useEffect(() => {
    setLoading(true);
    fetchQuery(aISummaryHistoryQuery, queryParams).toPromise().then((data) => {
      const resultData = data as AISummaryHistoryStixCoreObjectAskAiHistoryQuery$data;
      if (resultData && resultData.stixCoreObjectAskAiHistory) {
        setResult(resultData);
        setContent(resultData.stixCoreObjectAskAiHistory.result ?? '');
        setLoading(false);
      }
    });
  }, []);

  const refetch = useCallback(() => {
    setContent('');
    setLoading(true);
    fetchQuery(aISummaryHistoryQuery, { ...queryParams, forceRefresh: true }).toPromise().then((data) => {
      const resultData = data as AISummaryHistoryStixCoreObjectAskAiHistoryQuery$data;
      if (resultData && resultData.stixCoreObjectAskAiHistory) {
        setResult(resultData);
        setContent(resultData.stixCoreObjectAskAiHistory.result ?? '');
        setLoading(false);
      }
    });
  }, []);

  return (
    <AISummaryHistoryComponent
      language={language}
      setLanguage={setLanguage}
      refetch={refetch}
      content={content}
      result={result}
      loading={loading}
    />
  );
};

// ── XTM One agent-based history ─────────────────────────────────────────

interface XtmOneHistoryProps {
  id: string;
  loading: boolean;
  setLoading: (loading: boolean) => void;
  selectedAgent: AgentOption | null;
}

const XtmOneHistory = ({ id, loading, setLoading, selectedAgent }: XtmOneHistoryProps) => {
  const { t_i18n } = useFormatter();
  const defaultLanguageName = getDefaultAiLanguage();
  const [language] = useState(defaultLanguageName);
  const { content, loading: streamLoading, error: errorMessage, generatedAt, execute } = useAgentStream({
    transformContent: cleanHtmlTags,
  });

  useEffect(() => {
    setLoading(streamLoading);
  }, [streamLoading, setLoading]);

  const executeCall = useCallback(() => {
    if (!selectedAgent) return;
    const prompt = `Summarize the internal history (audit logs, modifications) of the OpenCTI entity with ID: ${id}. `
      + 'Provide a chronological summary of significant changes.'
      + `Answer using ${language} language.`;
    execute(selectedAgent.slug, prompt);
  }, [selectedAgent, id, language, execute]);

  useEffect(() => {
    if (selectedAgent && !loading) {
      executeCall();
    }
  }, [selectedAgent?.id]);

  const noAgent = !selectedAgent;

  return (
    <XtmOneAISummaryDisplay
      disclaimerText={t_i18n('This summary is based on the history of this entity (internal activity). It has been generated by AI and can contain mistakes.')}
      noAgent={noAgent}
      errorMessage={errorMessage}
      loading={loading}
      content={content}
      generatedAt={generatedAt}
      onRetry={executeCall}
    />
  );
};

// ── Main component (routes between XTM One and legacy) ──────────────────

const AISummaryHistory = ({ id, loading, setLoading, selectedAgent }: AISummaryHistoryProps) => {
  const { xtmOneConfigured } = useChatbot();
  const useXtmOne = xtmOneConfigured === true;

  if (useXtmOne) {
    return (
      <XtmOneHistory
        id={id}
        loading={loading}
        setLoading={setLoading}
        selectedAgent={selectedAgent ?? null}
      />
    );
  }

  return (
    <LegacyAISummaryHistory
      id={id}
      loading={loading}
      setLoading={setLoading}
    />
  );
};

export default AISummaryHistory;
