import { graphql, PreloadedQuery, usePreloadedQuery } from 'react-relay';
import React, { useState } from 'react';
import Alert from '@mui/material/Alert';
import parse from 'html-react-parser';
import { AISummaryHistoryQuery } from './__generated__/AISummaryHistoryQuery.graphql';
import useQueryLoading from '../../../../utils/hooks/useQueryLoading';
import { useFormatter } from '../../../../components/i18n';
import Loader, { LoaderVariant } from '../../../../components/Loader';
import { aiRotatingTexts, getDefaultAiLanguage } from '../../../../utils/ai/Common';

const aISummaryHistoryQuery = graphql`
  query AISummaryHistoryQuery($id: ID!, $language: String) {
      stixCoreObjectAiHistory(id: $id, language: $language) {
        result
        updated_at
    }
  }
`;

interface AISummaryHistoryComponentProps {
  queryRef: PreloadedQuery<AISummaryHistoryQuery>;
  language: string;
  setLanguage: (language: string) => void;
}

const AISummaryHistoryComponent = ({ queryRef }: AISummaryHistoryComponentProps) => {
  const { t_i18n } = useFormatter();
  const { stixCoreObjectAiHistory } = usePreloadedQuery(
    aISummaryHistoryQuery,
    queryRef,
  );
  if (stixCoreObjectAiHistory && stixCoreObjectAiHistory.result) {
    return (
      <>
        {parse(stixCoreObjectAiHistory.result.replace('<body>', '').replace('</body>', ''))}
        <Alert severity="info" variant="outlined" style={{ marginTop: 20 }}>
          {t_i18n('This summary is based on the history of this entity (internal activity). It has been generated by AI and can contain mistakes.')}
        </Alert>
      </>
    );
  }
  return (
    <div
      style={{
        display: 'table',
        height: '100%',
        width: '100%',
        paddingTop: 15,
        paddingBottom: 15,
      }}
    >
      <span
        style={{
          display: 'table-cell',
          verticalAlign: 'middle',
          textAlign: 'center',
        }}
      >
        {t_i18n('No AI Intelligence.')}
      </span>
    </div>
  );
};

interface AISummaryHistoryProps {
  id: string
}

const AISummaryHistory = ({ id }: AISummaryHistoryProps) => {
  const defaultLanguageName = getDefaultAiLanguage();
  const [language, setLanguage] = useState(defaultLanguageName);
  const queryRef = useQueryLoading<AISummaryHistoryQuery>(aISummaryHistoryQuery, { id, language });
  return (
    <>
      {queryRef ? (
        <React.Suspense fallback={<Loader variant={LoaderVariant.inElement} rotatingTexts={aiRotatingTexts} />}>
          <AISummaryHistoryComponent
            queryRef={queryRef}
            language={language}
            setLanguage={setLanguage}
          />
        </React.Suspense>
      ) : (
        <Loader variant={LoaderVariant.inElement} rotatingTexts={aiRotatingTexts} />
      )}
    </>
  );
};

export default AISummaryHistory;
