import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { graphql, useSubscription } from 'react-relay';
import Alert from '@mui/material/Alert';
import parse from 'html-react-parser';
import AlertTitle from '@mui/material/AlertTitle';
import { GraphQLSubscriptionConfig } from 'relay-runtime';
import Divider from '@mui/material/Divider';
import Typography from '@mui/material/Typography';
import IconButton from '@common/button/IconButton';
import { AutoModeOutlined, ContentCopyOutlined, HistoryOutlined } from '@mui/icons-material';
import { AISummaryActivityStixCoreObjectAskAiActivityQuery$data } from '@components/common/ai/__generated__/AISummaryActivityStixCoreObjectAskAiActivityQuery.graphql';
import Tooltip from '@mui/material/Tooltip';
import { AISummaryActivitySubscription, AISummaryActivitySubscription$data } from './__generated__/AISummaryActivitySubscription.graphql';
import { useFormatter } from '../../../../components/i18n';
import { getDefaultAiLanguage } from '../../../../utils/ai/Common';
import { fetchQuery } from '../../../../relay/environment';
import { copyToClipboard, cleanHtmlTags } from '../../../../utils/utils';

const subscription = graphql`
  subscription AISummaryActivitySubscription($id: ID!) {
    aiBus(id: $id) {
      content
    }
  }
`;

const aISummaryActivityQuery = graphql`
  query AISummaryActivityStixCoreObjectAskAiActivityQuery($id: ID!, $language: String, $forceRefresh: Boolean) {
      stixCoreObjectAskAiActivity(id: $id, language: $language, forceRefresh: $forceRefresh) {
        result
        trend
        updated_at
    }
  }
`;

interface AISummaryActivityComponentProps {
  refetch: () => void;
  language: string;
  setLanguage: (language: string) => void;
  content: string;
  loading: boolean;
  result: AISummaryActivityStixCoreObjectAskAiActivityQuery$data | null;
}

const AISummaryActivityComponent = ({
  refetch,
  content,
  result,
  loading,
}: AISummaryActivityComponentProps) => {
  const { t_i18n, nsdt } = useFormatter();
  const generateTrend = (trend: string) => {
    if (loading) {
      return (
        <Alert
          icon={<HistoryOutlined />}
          severity="info"
          variant="outlined"
          style={{ marginTop: 20 }}
        >
          <AlertTitle>{t_i18n('Computing activity evaluation...')}</AlertTitle>
          <i>{t_i18n('This summary is based on the evolution of the activity of this entity (indicators, victimology, etc.). It has been generated by AI and can contain mistakes.')}</i>
        </Alert>
      );
    }
    switch (trend) {
      case 'increasing':
        return (
          <Alert
            severity="error"
            variant="outlined"
            style={{ marginTop: 20 }}
          >
            <AlertTitle>{t_i18n('Activity evaluation')}: <strong>{t_i18n('Increasing')}</strong> - {t_i18n('The threat activity is showing a significant increase.')}</AlertTitle>
            <i>{t_i18n('This summary is based on the evolution of the activity of this entity (indicators, victimology, etc.). It has been generated by AI and can contain mistakes.')}</i>
          </Alert>
        );
      case 'stable':
        return (
          <Alert
            severity="warning"
            variant="outlined"
            style={{ marginTop: 20 }}
          >
            <AlertTitle>{t_i18n('Activity evaluation')}: <strong>{t_i18n('Stable')}</strong> - {t_i18n('The threat activity is stable with minor fluctuations.')}</AlertTitle>
            <i>{t_i18n('This summary is based on the evolution of the activity of this entity (indicators, victimology, etc.). It has been generated by AI and can contain mistakes.')}</i>
          </Alert>
        );
      case 'decreasing':
        return (
          <Alert
            severity="success"
            variant="outlined"
            style={{ marginTop: 20 }}
          >
            <AlertTitle>{t_i18n('Activity evaluation')}: <strong>{t_i18n('Decreasing')}</strong> - {t_i18n('The threat activity is showing a significant decrease.')}</AlertTitle>
            <i>{t_i18n('This summary is based on the evolution of the activity of this entity (indicators, victimology, etc.). It has been generated by AI and can contain mistakes.')}</i>
          </Alert>
        );
      default:
        return (
          <Alert
            severity="info"
            variant="outlined"
            style={{ marginTop: 20 }}
          >
            <AlertTitle>{t_i18n('Activity evaluation')}: <strong>{t_i18n('Unknown')}</strong> - {t_i18n('The evaluation of the threat activity cannot be provided (lack of data).')}</AlertTitle>
            <i>{t_i18n('This summary is based on the evolution of the activity of this entity (indicators, victimology, etc.). It has been generated by AI and can contain mistakes.')}</i>
          </Alert>
        );
    }
  };
  return (
    <>
      {generateTrend(result?.stixCoreObjectAskAiActivity?.trend ?? 'unknown')}
      {parse(content)}
      {!loading && (
        <>
          <Divider />
          <div style={{ float: 'right', marginTop: 20, display: 'flex', alignItems: 'center', gap: '5px' }}>
            <Typography variant="caption">Generated on {nsdt(result?.stixCoreObjectAskAiActivity?.updated_at)}.</Typography>
            <Tooltip title={t_i18n('Copy to clipboard')}>
              <IconButton size="small" color="primary" onClick={() => copyToClipboard(t_i18n, content)}>
                <ContentCopyOutlined fontSize="small" />
              </IconButton>
            </Tooltip>
            <Tooltip title={t_i18n('Retry')}>
              <IconButton size="small" color="primary" onClick={() => refetch()}>
                <AutoModeOutlined fontSize="small" />
              </IconButton>
            </Tooltip>
          </div>
        </>
      )}
    </>
  );
};

interface AISummaryActivityProps {
  id: string;
  loading: boolean;
  setLoading: (loading: boolean) => void;
}

const AISummaryActivity = ({ id, loading, setLoading }: AISummaryActivityProps) => {
  const busId = `${id}-activity`;
  const defaultLanguageName = getDefaultAiLanguage();
  const [content, setContent] = useState('');
  const [result, setResult] = useState<AISummaryActivityStixCoreObjectAskAiActivityQuery$data | null>(null);
  const [language, setLanguage] = useState(defaultLanguageName);

  // Subscription
  const handleResponse = (response: AISummaryActivitySubscription$data | null | undefined) => {
    const newContent = response ? (response as AISummaryActivitySubscription$data).aiBus?.content : null;
    const finalContent = cleanHtmlTags(newContent);
    return setContent(finalContent);
  };
  const subConfig = useMemo<GraphQLSubscriptionConfig<AISummaryActivitySubscription>>(
    () => ({
      subscription,
      variables: { id: busId },
      onNext: handleResponse,
    }),
    [busId],
  );
  // TODO: Check by the engineering team
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  useSubscription(subConfig);

  // Query
  const queryParams = {
    busId,
    id,
    language,
  };
  useEffect(() => {
    setLoading(true);
    fetchQuery(aISummaryActivityQuery, queryParams).toPromise().then((data) => {
      const resultData = data as AISummaryActivityStixCoreObjectAskAiActivityQuery$data;
      if (resultData && resultData.stixCoreObjectAskAiActivity) {
        setResult(resultData);
        setContent(resultData.stixCoreObjectAskAiActivity.result ?? '');
        setLoading(false);
      }
    });
  }, []);

  const refetch = useCallback(() => {
    setContent('');
    setLoading(true);
    fetchQuery(aISummaryActivityQuery, { ...queryParams, forceRefresh: true }).toPromise().then((data) => {
      const resultData = data as AISummaryActivityStixCoreObjectAskAiActivityQuery$data;
      if (resultData && resultData.stixCoreObjectAskAiActivity) {
        setResult(resultData);
        setContent(resultData.stixCoreObjectAskAiActivity.result ?? '');
        setLoading(false);
      }
    });
  }, []);

  return (
    <AISummaryActivityComponent
      language={language}
      setLanguage={setLanguage}
      refetch={refetch}
      content={content}
      result={result}
      loading={loading}
    />
  );
};

export default AISummaryActivity;
