PREFIX vsac:<tag:darklight:vuln-scan-analysis#>
PREFIX vuln: <tag:darklight:vulnerabilitymanagement#>

SELECT * WHERE {
 BIND("438.nessus" as ?scanName) .
 GRAPH ?vs {
  ?vs a <tag:darklight:vulnerabilitymanagement#VulnerabilityScan> .
  ?vs vsac:hasScanAnalysis ?scanAnalysis .
  ?vs vuln:hasScanName ?scanName .
  ?vs vuln:hasHostNum ?hostNum .
  ?vs vuln:hasRecordNum ?recordNum .
  ?vs vuln:hasHostScanDate ?hostScanDate .
  ?vs vuln:hasTotalHostNum ?totalHostNum .
  ?vs vuln:hasScanID ?scanId .
  ?vs vuln:hasPolicyName ?policyName .
  ?vs vuln:hasTotalRecordNum ?totalRecordNum .
  ?vs vuln:hasReportName ?reportName .
  ?vs vuln:hasScanVendor ?scanVendor .
  ?vs vuln:hasScanVendorName ?scanVendorName .
  ?vs vuln:hasUniqueCVECount ?uniqueCVECount .
  ?vs vuln:hasTotalCVECount ?totalCVECount .
  ?vs vuln:hasTargetObservations ?targetObservations .
 }
}
LIMIT 1
