global:
  scrape_interval: "15s"

scrape_configs:
  - job_name: 'opencti-dev-telemetry-prometheus'
    static_configs:
      - targets: ['host.docker.internal:14269']
        labels:
          app: "opencti"
  - job_name: "rabbitmq"
    metrics_path: "/metrics/detailed"
    params:
      family: ["queue_coarse_metrics"]
    static_configs:
      - targets: ["host.docker.internal:15692"]
        labels:
          app: 'opencti'
  - job_name: "connectors"
    static_configs:
      - targets: ["host.docker.internal:9095"]
        labels:
          app: "opencti"

rule_files:
  - "/etc/prometheus/rules/*.yml"
