query DeviceDetails($computingDeviceAssetId: ID!) {
  computingDeviceAsset(id: $computingDeviceAssetId) {
    id
    entity_type
    name
    created
    modified
    asset_id
    asset_type
    is_publicly_accessible
    is_scanned
    is_virtual
    mac_address
    ipv4_address {
      ip_address_value
    }
    ipv6_address {
      ip_address_value
    }
    connected_to_network {
      id
      name
      network_id
      network_name
    }
  }
}