query DevicesLinesFragments {
  computingDeviceAssetList {
    edges {
      node {
        ... Device_device
      }
    }
  }
}

fragment Device_device on ComputingDeviceAsset {
  id
  name
  asset_id
  asset_type
  description
  version
  vendor_name
  serial_number
  release_date
  labels
  ...DeviceDetails_device
}

fragment DeviceDetails_device on ComputingDeviceAsset {
  installed_operating_system {
    id
    name
  }
  # installed_software {
  #   id
  #   name
  # }
  installed_hardware {
    id
    name
  }
  connected_to_network {
    id
    name
  }
  ipv4_address {
    ip_address_value
  }
  ipv6_address {
    ip_address_value
  }
  mac_address
  default_gateway
  locations {
    city
    country
    description
  }
  # ports {
  #   port_number
  #   protocols
  # }
  uri
  model
  fqdn
  hostname
  netbios_name
  baseline_configuration_name
  bios_id
  motherboard_id
  installation_id
  is_publicly_accessible
  is_scanned
  is_virtual
}
