query DeviceFilter {
  computingDeviceAssetList {
    edges {
      node {
        id
        entity_type
        name
        asset_type
        is_publicly_accessible
        is_scanned
        is_virtual
        installed_operating_system {
          id
          asset_type
          name
        }
        installed_software {
          id
          asset_type
          name
          vendor_name
          version
        }
        mac_address
        ipv4_address {
          ip_address_value
        }
        ipv6_address {
          ip_address_value
        }
      }
    }
  }
}