mutation ReplaceFieldValue {
  editComputingDeviceAsset(
    id: "ad089d66-6537-547c-9d51-aee9ffd6483e"
    input: {
      key: "asset_type"
      value: ["tag-2345"]
      operation: replace
    }
  ) {
  id
  }
}