query ItAssetList {
  itAssetList {
    edges {
      cursor
      node {
        id
        entity_type
        created
        name
        ... on ComputingDeviceAsset {
          __typename
        }
        ... on NetworkAsset {
          __typename
        }
        ... on SoftwareAsset {
          __typename
        }
      }
    }
  }
}