mutation DeviceCreationMutation {
  createComputingDeviceAsset(
    input: {
      name: "0003 test"
      operational_status: operational
      asset_id: "d4bc6832-3d88-4b91-9d19-49c196dd2c10"
      asset_type: physical_device
      is_publicly_accessible: false
      is_scanned: false
      is_virtual: false
      ipv4_address: [{ ip_address_value: "192.168.1.190" }]
      ipv6_address: [
        { ip_address_value: "2603:9001:3300:73da:9d67:2975:7df7:875c" }
      ]
      mac_address: ["ac:de:48:00:11:22"]
      ports: [{ port_number: 8443, protocols: [TCP] }]
      release_date: "2022-01-17T00:00:00Z"
    }
  ) {
    id
  }
}
