query NetworkDetails($networkAssetId: ID!) {
  networkAsset(id: $networkAssetId) {
    id
    name
    network_id
    network_name
    network_address_range {
      starting_ip_address {
        ... on IpV4Address {
          ip_address_value
        }
      }
      ending_ip_address {
        ... on IpV4Address {
          ip_address_value
        }
      }
    }
  }
}