query SoftwareList {
  softwareAssetList {
    edges {
      node {
        id
        created
        modified
        labels {
          name
          color
          description
        }
        asset_id
        asset_tag
        asset_type
        name
        description
        serial_number
        vendor_name
        version
        release_date
        implementation_point
        operational_status
        function
        cpe_identifier
        software_identifier
        patch_level
        installation_id
        license_key
        is_publicly_accessible
        is_scanned
        last_scanned
        locations {
          id
          name
          description
        }
        external_references {
          id
          source_name
          description
          url
          hashes {
            algorithm
            value
          }
          external_id
          __typename
        }
        notes {
          id
          created
          modified
          abstract
          content
          authors
        }
      }
    }
  }
}