import { test } from '../fixtures/baseFixtures';
import { addUsers } from './user.data';
import { addRoles } from './role.data';
import { addGroups } from './group.data';
import { addOrganizations, restrictOrganizationVisibility } from './organization.data';
import { addStatusTemplates } from './statusTemplate.data';

test('Init data', async ({ request }) => {
  await addOrganizations(request, [
    { name: 'OrgA' },
    { name: 'OrgB' },
    { name: 'OrgC' },
  ]);
  // OrgA's own Identity must not be visible to OrgB, so a Report authored by OrgA shows a
  // "restricted" Author to OrgB users (Threat Advisory product-test-plan steps 19-20).
  await restrictOrganizationVisibility(request, 'OrgA', ['OrgA', 'OrgC']);
  await addStatusTemplates(request, [
    { name: 'NEW', color: '#4caf50' },
    { name: 'MO MANAGER REVIEW', color: '#ff9800' },
    { name: 'ORGC ANALYST REVIEW', color: '#ff9800' },
    { name: 'ORGC MANAGER REVIEW', color: '#f44336' },
    { name: 'READY FOR VALIDATION', color: '#2196f3' },
    { name: 'ZZZ_THROWAWAY_DELETE_ME', color: '#9e9e9e' },
  ]);
  await addRoles(request, [
    {
      name: 'Dashboards',
      capabilities: ['EXPLORE_EXUPDATE_EXDELETE'],
    },
    {
      name: 'Analyst',
      capabilities: [
        'KNOWLEDGE',
        'KNOWLEDGE_KNPARTICIPATE',
        'KNOWLEDGE_KNFRONTENDEXPORT',
        'KNOWLEDGE_KNUPDATE',
        'KNOWLEDGE_KNUPDATE_KNDELETE',
        'KNOWLEDGE_KNUPDATE_KNMERGE',
        'KNOWLEDGE_KNUPLOAD',
        'KNOWLEDGE_KNASKIMPORT',
        'KNOWLEDGE_KNGETEXPORT',
        'KNOWLEDGE_KNGETEXPORT_KNASKEXPORT',
        'KNOWLEDGE_KNENRICHMENT',
        'EXPLORE',
        'APIACCESS',
        'APIACCESS_USETOKEN',
        'APIACCESS_USEBASICAUTH',
        'TAXIIAPI',
      ],
    },
    {
      name: 'Manager',
      capabilities: [
        'KNOWLEDGE',
        'KNOWLEDGE_KNPARTICIPATE',
        'KNOWLEDGE_KNFRONTENDEXPORT',
        'KNOWLEDGE_KNUPDATE',
        'KNOWLEDGE_KNUPDATE_KNDELETE',
        'KNOWLEDGE_KNUPDATE_KNMERGE',
        'KNOWLEDGE_KNUPDATE_KNBYPASSREFERENCE',
        'KNOWLEDGE_KNUPLOAD',
        'KNOWLEDGE_KNASKIMPORT',
        'KNOWLEDGE_KNGETEXPORT',
        'KNOWLEDGE_KNGETEXPORT_KNASKEXPORT',
        'KNOWLEDGE_KNENRICHMENT',
        'EXPLORE',
        'EXPLORE_EXUPDATE',
        'APIACCESS',
        'APIACCESS_USETOKEN',
        'APIACCESS_USEBASICAUTH',
        'TAXIIAPI',
        'TAXIIAPI_SETCOLLECTIONS',
        'INGESTION',
        'INGESTION_SETINGESTIONS',
        'CSVMAPPERS',
        'AUTOMATION',
        'PIRAPI',
      ],
    },
    {
      name: 'OrgC Analyst',
      capabilities: [
        'KNOWLEDGE',
        'KNOWLEDGE_KNPARTICIPATE',
        'KNOWLEDGE_KNFRONTENDEXPORT',
        'KNOWLEDGE_KNUPDATE',
        'KNOWLEDGE_KNUPDATE_KNDELETE',
        'KNOWLEDGE_KNUPDATE_KNMERGE',
        'KNOWLEDGE_KNUPDATE_KNBYPASSREFERENCE',
        // Deliberately NOT granted KNBYPASSFIELDS - the Reject transition's required-comment
        // enforcement is tested for this persona and this capability would silently bypass it.
        'KNOWLEDGE_KNUPLOAD',
        'KNOWLEDGE_KNASKIMPORT',
        'KNOWLEDGE_KNGETEXPORT',
        'KNOWLEDGE_KNGETEXPORT_KNASKEXPORT',
        'KNOWLEDGE_KNENRICHMENT',
        'EXPLORE',
        'APIACCESS',
        'APIACCESS_USETOKEN',
        'APIACCESS_USEBASICAUTH',
        'TAXIIAPI',
        'INVESTIGATION',
        'INVESTIGATION_INUPDATE',
        'INVESTIGATION_INUPDATE_INDELETE',
        'MODULES',
        'INGESTION',
        'INGESTION_SETINGESTIONS',
        'CSVMAPPERS',
        'PIRAPI',
        'PIRAPI_PIRUPDATE',
        'SETTINGS',
        'SETTINGS_SETLABELS',
        'SETTINGS_SETVOCABULARIES',
      ],
    },
    {
      name: 'OrgC Manager',
      capabilities: [
        'KNOWLEDGE',
        'KNOWLEDGE_KNPARTICIPATE',
        'KNOWLEDGE_KNFRONTENDEXPORT',
        'KNOWLEDGE_KNUPDATE',
        'KNOWLEDGE_KNUPDATE_KNDELETE',
        'KNOWLEDGE_KNUPDATE_KNMERGE',
        'KNOWLEDGE_KNUPDATE_KNBYPASSREFERENCE',
        // Deliberately NOT granted KNBYPASSFIELDS - the Reject transition's required-comment
        // enforcement is tested for this persona and this capability would silently bypass it.
        'KNOWLEDGE_KNUPDATE_KNORGARESTRICT',
        'KNOWLEDGE_KNUPDATE_KNMANAGEAUTHMEMBERS',
        'KNOWLEDGE_KNDISSEMINATION',
        'KNOWLEDGE_KNUPLOAD',
        'KNOWLEDGE_KNASKIMPORT',
        'KNOWLEDGE_KNGETEXPORT',
        'KNOWLEDGE_KNGETEXPORT_KNASKEXPORT',
        'KNOWLEDGE_KNENRICHMENT',
        'EXPLORE',
        'EXPLORE_EXUPDATE',
        'EXPLORE_EXUPDATE_EXDELETE',
        'EXPLORE_EXUPDATE_PUBLISH',
        'APIACCESS',
        'APIACCESS_USETOKEN',
        'APIACCESS_USEBASICAUTH',
        'CONNECTORAPI',
        'TAXIIAPI',
        'TAXIIAPI_SETCOLLECTIONS',
        'INVESTIGATION',
        'INVESTIGATION_INUPDATE',
        'INVESTIGATION_INUPDATE_INDELETE',
        'MODULES',
        'MODULES_MODMANAGE',
        'INGESTION',
        'INGESTION_SETINGESTIONS',
        'CSVMAPPERS',
        'AUTOMATION',
        'AUTOMATION_AUTMANAGE',
        'PIRAPI',
        'PIRAPI_PIRUPDATE',
        'SETTINGS',
        'SETTINGS_SETLABELS',
        'SETTINGS_SETVOCABULARIES',
        'SETTINGS_SETPARAMETERS',
        'SETTINGS_SETMARKINGS',
        'SETTINGS_SETDISSEMINATION',
        'SETTINGS_SETCUSTOMIZATION',
        'SETTINGS_SETCASETEMPLATES',
        'SETTINGS_SETSTATUSTEMPLATES',
        'SETTINGS_SETKILLCHAINPHASES',
        'SETTINGS_SETMANAGEXTMHUB',
        'SETTINGS_SECURITYACTIVITY',
        'SETTINGS_FILEINDEXING',
        'SETTINGS_SUPPORT',
      ],
    },
  ]);
  await addGroups(request, [
    {
      name: 'Dashboards group',
      roles: ['Dashboards'],
    },
    {
      name: 'Analyst group',
      roles: ['Analyst'],
    },
    {
      name: 'Manager group',
      roles: ['Manager'],
    },
    {
      name: 'OrgC Analyst group',
      roles: ['OrgC Analyst'],
    },
    {
      name: 'OrgC Manager group',
      roles: ['OrgC Manager'],
    },
  ]);
  await addUsers(request, [
    {
      name: 'Jean Michel',
      user_email: 'jean.michel@filigran.test',
      password: 'jeanmichel',
      groups: ['Dashboards group'],
    },
    {
      name: 'Anne',
      user_email: 'anne@filigran.test',
      password: 'anne',
      groups: ['Dashboards group'],
    },
    {
      name: 'Bernadette',
      user_email: 'bernadette@filigran.test',
      password: 'bernadette',
      groups: ['Dashboards group'],
    },
    {
      name: 'Louise',
      user_email: 'louise@filigran.test',
      password: 'louise',
      groups: ['Dashboards group'],
    },
    {
      name: 'AnalystOrgA',
      user_email: 'analystorga@filigran.test',
      password: 'analystorga',
      groups: ['Analyst group'],
      organizations: ['OrgA'],
    },
    {
      name: 'ManagerOrgA',
      user_email: 'managerorga@filigran.test',
      password: 'managerorga',
      groups: ['Manager group'],
      organizations: ['OrgA'],
    },
    {
      name: 'AnalystOrgB',
      user_email: 'analystorgb@filigran.test',
      password: 'analystorgb',
      groups: ['Analyst group'],
      organizations: ['OrgB'],
    },
    {
      name: 'ManagerOrgB',
      user_email: 'managerorgb@filigran.test',
      password: 'managerorgb',
      groups: ['Manager group'],
      organizations: ['OrgB'],
    },
    {
      name: 'AnalystOrgC',
      user_email: 'analystorgc@filigran.test',
      password: 'analystorgc',
      groups: ['OrgC Analyst group'],
      organizations: ['OrgC'],
    },
    {
      name: 'ManagerOrgC',
      user_email: 'managerorgc@filigran.test',
      password: 'managerorgc',
      groups: ['OrgC Manager group'],
      organizations: ['OrgC'],
    },
  ]);
});
