import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// ── Mocks (must be declared before imports) ─────────────────────────────

vi.mock('../../../../src/modules/xtm/one/xtm-one-client', () => ({
  default: {
    isConfigured: vi.fn(),
    register: vi.fn(),
  },
}));

vi.mock('../../../../src/database/cache', () => ({
  getEntityFromCache: vi.fn(),
}));

vi.mock('../../../../src/modules/settings/licensing', () => ({
  getEnterpriseEditionActivePem: vi.fn(),
  decodeLicensePem: vi.fn(),
  IS_LTS_PLATFORM: false,
}));

// The pinned XTM CA is swapped for a CA generated by the test, whose key signs the XTM licenses below.
const anchor = vi.hoisted(() => ({ certificate: undefined as unknown }));
vi.mock('../../../../src/enterprise-edition/xtm_ca', () => ({
  get XTM_CA() {
    return anchor.certificate;
  },
}));

vi.mock('../../../../src/config/conf', () => ({
  default: { get: vi.fn() },
  logApp: { info: vi.fn(), warn: vi.fn(), error: vi.fn() },
  PLATFORM_VERSION: '6.0.0-test',
}));

let redisRegistrationResult: object | null = null;
vi.mock('../../../../src/database/redis', () => ({
  redisSetXtmRegistrationResult: vi.fn(async (result: object, _ttlSeconds: number) => {
    redisRegistrationResult = result;
  }),
  redisGetXtmRegistrationResult: vi.fn(async () => redisRegistrationResult),
  publishCacheResetEvent: vi.fn(async () => undefined),
}));

// ── Imports (after mocks) ───────────────────────────────────────────────

import xtmOneClient from '../../../../src/modules/xtm/one/xtm-one-client';
import { getEntityFromCache } from '../../../../src/database/cache';
import { logApp } from '../../../../src/config/conf';
import { getEnterpriseEditionActivePem, decodeLicensePem } from '../../../../src/modules/settings/licensing';
import { refreshXtmLicenseProof, registerWithXtmOne } from '../../../../src/modules/xtm/one/xtm-one';
import { buildXtmLicenseContext, getCurrentXtmLicenseProof, setCurrentXtmLicenseProof, verifyXtmLicenseProof } from '../../../../src/modules/xtm/one/xtm-one-license';
import { publishCacheResetEvent } from '../../../../src/database/redis';
import type { AuthContext, AuthUser } from '../../../../src/types/user';
import type { BasicStoreSettings } from '../../../../src/types/settings';
import { createTestCertificateAuthority, createTestXtmLicense, DAY } from '../../../utils/xtmLicenseHelper';

// ── Test fixtures ───────────────────────────────────────────────────────

const mockContext = {} as AuthContext;
const mockUser = { id: 'user-1' } as AuthUser;

const mockSettings = {
  id: 'settings-id-123',
  internal_id: 'settings-internal-id-123',
  platform_url: 'https://opencti.test',
  platform_title: 'Test OpenCTI',
  enterprise_license: 'some-pem',
  filigran_chatbot_ai_cgu_status: 'enabled',
};

const mockRegistrationResponse = {
  status: 'ok',
  platform_identifier: 'opencti',
  ee_enabled: true,
  user_integrations: 0,
  chat_web_token: null,
  version: '6.0.0-test',
  intent_catalog: [
    {
      intent: 'global.assistant',
      description: 'General-purpose assistant',
      agents: [
        {
          agent_id: 'agent-1',
          agent_name: 'TestAgent',
          agent_slug: 'test-agent',
          agent_description: null,
          vertical: 'cti',
          priority: 1,
          is_default: true,
          is_locked: false,
          enabled: true,
        },
      ],
    },
  ],
};

// ── Tests ───────────────────────────────────────────────────────────────

describe('registerWithXtmOne', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    redisRegistrationResult = null;
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('should do nothing when xtmOneClient is not configured', async () => {
    vi.mocked(xtmOneClient.isConfigured).mockReturnValue(false);

    await registerWithXtmOne(mockContext, mockUser);

    expect(xtmOneClient.register).not.toHaveBeenCalled();
    expect(getEntityFromCache).not.toHaveBeenCalled();
  });

  it('should warn and return when settings are not available', async () => {
    vi.mocked(xtmOneClient.isConfigured).mockReturnValue(true);
    vi.mocked(getEntityFromCache).mockResolvedValue(undefined as any);

    await registerWithXtmOne(mockContext, mockUser);

    expect(xtmOneClient.register).not.toHaveBeenCalled();
  });

  it('should call register with correct payload when configured', async () => {
    vi.mocked(xtmOneClient.isConfigured).mockReturnValue(true);
    vi.mocked(getEntityFromCache).mockResolvedValue(mockSettings as any);
    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: 'test-pem', licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockReturnValue({ license_validated: true, license_type: 'enterprise' } as any);
    vi.mocked(xtmOneClient.register).mockResolvedValue(mockRegistrationResponse);

    await registerWithXtmOne(mockContext, mockUser);

    expect(xtmOneClient.register).toHaveBeenCalledTimes(1);
    const callArgs = vi.mocked(xtmOneClient.register).mock.calls[0][0];
    expect(callArgs.platform_identifier).toBe('opencti');
    expect(callArgs.platform_url).toBe('https://opencti.test');
    expect(callArgs.platform_title).toBe('Test OpenCTI');
    expect(callArgs.platform_id).toBe('settings-internal-id-123');
    expect(callArgs.enterprise_license_pem).toBe('test-pem');
    expect(callArgs.license_type).toBe('enterprise');
    expect(callArgs.business_vertical).toBe('cti');
    // Ask Ariane can render an approval prompt and collect a verdict; this flag is
    // what makes XTM One gate OpenCTI-contributed tools instead of asking an
    // administrator to exempt them. A typo here would silently disable the feature.
    expect(callArgs.supports_approval_prompts).toBe(true);
    expect(callArgs.intents.length).toBeGreaterThan(0);
    expect(callArgs.intents.map((i: { name: string }) => i.name)).toContain('global.assistant');
  });

  it('should not advertise approval prompts when the chatbot is not usable', async () => {
    // The flag promises somebody can be asked. With the CGU not accepted the
    // panel is unreachable, so there is nobody to answer a prompt and a gated
    // tool would stall for callers that cannot prompt at all.
    vi.mocked(xtmOneClient.isConfigured).mockReturnValue(true);
    vi.mocked(getEntityFromCache).mockResolvedValue({ ...mockSettings, filigran_chatbot_ai_cgu_status: 'disabled' } as any);
    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: 'test-pem', licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockReturnValue({ license_validated: true, license_type: 'enterprise' } as any);
    vi.mocked(xtmOneClient.register).mockResolvedValue(mockRegistrationResponse);

    await registerWithXtmOne(mockContext, mockUser);

    const callArgs = vi.mocked(xtmOneClient.register).mock.calls[0][0];
    expect(callArgs.supports_approval_prompts).toBe(false);
  });

  it('should handle null register response gracefully', async () => {
    vi.mocked(xtmOneClient.isConfigured).mockReturnValue(true);
    vi.mocked(getEntityFromCache).mockResolvedValue(mockSettings as any);
    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: undefined, licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockImplementation(() => {
      throw new Error('invalid PEM');
    });
    vi.mocked(xtmOneClient.register).mockResolvedValue(null);

    // Should not throw
    await registerWithXtmOne(mockContext, mockUser);

    expect(xtmOneClient.register).toHaveBeenCalledTimes(1);
    const callArgs = vi.mocked(xtmOneClient.register).mock.calls[0][0];
    expect(callArgs.enterprise_license_pem).toBeUndefined();
    expect(callArgs.license_type).toBeUndefined();
  });

  it('should send license_type undefined when decodeLicensePem throws', async () => {
    vi.mocked(xtmOneClient.isConfigured).mockReturnValue(true);
    vi.mocked(getEntityFromCache).mockResolvedValue(mockSettings as any);
    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: 'bad-pem', licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockImplementation(() => {
      throw new Error('bad cert');
    });
    vi.mocked(xtmOneClient.register).mockResolvedValue(mockRegistrationResponse);

    await registerWithXtmOne(mockContext, mockUser);

    const callArgs = vi.mocked(xtmOneClient.register).mock.calls[0][0];
    expect(callArgs.license_type).toBeUndefined();
  });

  it('should send license_type undefined when license is not validated', async () => {
    vi.mocked(xtmOneClient.isConfigured).mockReturnValue(true);
    vi.mocked(getEntityFromCache).mockResolvedValue(mockSettings as any);
    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: 'pem', licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockReturnValue({ license_validated: false, license_type: 'enterprise' } as any);
    vi.mocked(xtmOneClient.register).mockResolvedValue(mockRegistrationResponse);

    await registerWithXtmOne(mockContext, mockUser);

    const callArgs = vi.mocked(xtmOneClient.register).mock.calls[0][0];
    expect(callArgs.license_type).toBeUndefined();
  });

  it('should fallback platform_id to settings.id when internal_id is missing', async () => {
    const settingsNoInternalId = { ...mockSettings, internal_id: undefined };
    vi.mocked(xtmOneClient.isConfigured).mockReturnValue(true);
    vi.mocked(getEntityFromCache).mockResolvedValue(settingsNoInternalId as any);
    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: undefined, licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockImplementation(() => {
      throw new Error('no pem');
    });
    vi.mocked(xtmOneClient.register).mockResolvedValue(mockRegistrationResponse);

    await registerWithXtmOne(mockContext, mockUser);

    const callArgs = vi.mocked(xtmOneClient.register).mock.calls[0][0];
    expect(callArgs.platform_id).toBe('settings-id-123');
  });
});

describe('registerWithXtmOne: the Enterprise Edition of the XTM license', () => {
  const xtmCa = createTestCertificateAuthority();
  anchor.certificate = xtmCa.certificate;
  const foreignCa = createTestCertificateAuthority();
  const settings = mockSettings as unknown as BasicStoreSettings;

  const heartbeat = async (answer: Record<string, unknown>) => {
    vi.mocked(xtmOneClient.register).mockResolvedValue({ ...mockRegistrationResponse, ...answer } as any);
    await registerWithXtmOne(mockContext, mockUser);
  };
  const warnings = () => vi.mocked(logApp.warn).mock.calls.map(([message]) => message as string);
  // What the Enterprise Edition resolution verifies on every read: the proof this node holds.
  const xtmLicenseVerdict = () => verifyXtmLicenseProof(getCurrentXtmLicenseProof(), buildXtmLicenseContext(settings, false));

  beforeEach(() => {
    vi.clearAllMocks();
    redisRegistrationResult = null;
    setCurrentXtmLicenseProof(null);
    vi.mocked(xtmOneClient.isConfigured).mockReturnValue(true);
    vi.mocked(getEntityFromCache).mockResolvedValue(mockSettings as any);
    // No OpenCTI license of its own: only the XTM One entitlement is at stake.
    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: undefined, licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockReturnValue({ license_validated: false } as any);
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('is granted by an XTM license sub-licensing every OpenCTI platform', async () => {
    await heartbeat({ ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa, { openctiIds: ['global'] }) });

    expect(xtmLicenseVerdict().granted).toBe(true);
    expect(logApp.warn).not.toHaveBeenCalled();
  });

  it('is granted by an XTM license listing the platform_id this platform registers with', async () => {
    await heartbeat({ xtm_license_pem: createTestXtmLicense(xtmCa, { openctiIds: ['another-platform', 'settings-internal-id-123'] }) });

    expect(xtmLicenseVerdict().granted).toBe(true);
  });

  it('is never granted by ee_enabled alone, and an XTM One without the license proof must be upgraded', async () => {
    await heartbeat({ ee_enabled: true });

    const entitlement = xtmLicenseVerdict();
    expect(entitlement.granted).toBe(false);
    expect(entitlement.reason).toBe('XTM One returned no XTM license certificate');
    expect(warnings()).toHaveLength(1);
    expect(warnings()[0]).toContain('Upgrade XTM One to a release returning the XTM license');
  });

  it('is never granted by ee_sources claiming the XTM sub-license without the license', async () => {
    await heartbeat({ ee_enabled: true, ee_sources: ['xtm_sublicense'], xtm_license_pem: null });

    expect(xtmLicenseVerdict().granted).toBe(false);
    expect(warnings()).toEqual(['[XTM One] Enterprise Edition not granted by the XTM license: XTM One reports an XTM sub-license without the XTM license certificate proving it']);
  });

  it('is not granted by a license that does not verify, and the warning says why', async () => {
    await heartbeat({ ee_enabled: true, ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(foreignCa) });

    expect(xtmLicenseVerdict().granted).toBe(false);
    expect(warnings()).toHaveLength(1);
    expect(warnings()[0]).toContain('the XTM license is not signed by the Filigran XTM CA');
  });

  it('is not granted by a license sub-licensing another platform', async () => {
    await heartbeat({ ee_enabled: true, ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa, { openctiIds: ['another-platform'] }) });

    expect(xtmLicenseVerdict().granted).toBe(false);
    expect(warnings()[0]).toContain('the XTM license does not sub-license this OpenCTI platform');
  });

  it('warns once while the heartbeats repeat the same answer', async () => {
    await heartbeat({ ee_enabled: true });
    await heartbeat({ ee_enabled: true });
    await heartbeat({ ee_enabled: true });

    expect(warnings()).toHaveLength(1);
  });

  it('warns once the own license no longer explains the Enterprise Edition an older XTM One reports', async () => {
    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: 'own-pem', licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockReturnValue({ license_validated: true, license_type: 'standard' } as any);
    await heartbeat({ ee_enabled: true });
    expect(logApp.warn).not.toHaveBeenCalled();

    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: undefined, licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockReturnValue({ license_validated: false } as any);
    await heartbeat({ ee_enabled: true });
    await heartbeat({ ee_enabled: true });

    expect(warnings()).toHaveLength(1);
    expect(warnings()[0]).toContain('Upgrade XTM One to a release returning the XTM license');
  });

  it('does not warn when the answer claims nothing through the XTM license', async () => {
    await heartbeat({ ee_enabled: false, ee_sources: [], xtm_license_pem: null });
    await heartbeat({ ee_enabled: true, ee_sources: ['platform_license'], xtm_license_pem: null });
    vi.mocked(getEnterpriseEditionActivePem).mockReturnValue({ pem: 'own-pem', licenseByConfiguration: false });
    vi.mocked(decodeLicensePem).mockReturnValue({ license_validated: true, license_type: 'standard' } as any);
    // An XTM One predating the license proof reports the platform's own license the same way.
    await heartbeat({ ee_enabled: true });

    expect(xtmLicenseVerdict().granted).toBe(false);
    expect(logApp.warn).not.toHaveBeenCalled();
  });

  it('ends with the first answer that no longer carries the license', async () => {
    await heartbeat({ ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa) });
    expect(xtmLicenseVerdict().granted).toBe(true);

    await heartbeat({ ee_enabled: true, ee_sources: ['xtm_sublicense'], xtm_license_pem: null });
    expect(xtmLicenseVerdict().granted).toBe(false);
  });

  it('ends when the license expires, even between two heartbeats', async () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    await heartbeat({ ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa, { type: 'trial', notAfter: new Date(Date.now() + 60 * 60 * 1000) }) });
    expect(xtmLicenseVerdict().granted).toBe(true);

    vi.setSystemTime(Date.now() + 2 * 60 * 60 * 1000);
    expect(xtmLicenseVerdict()).toMatchObject({ granted: false, reason: 'the trial XTM license has expired' });
  });

  it('keeps an expired standard license during the 90 days of grace of XTM One only', async () => {
    await heartbeat({ ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa, { notAfter: new Date(Date.now() - 10 * DAY) }) });
    expect(xtmLicenseVerdict().granted).toBe(true);

    await heartbeat({ ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa, { notAfter: new Date(Date.now() - 91 * DAY) }) });
    expect(xtmLicenseVerdict().granted).toBe(false);
  });

  it('resets the settings cache of every node when the Enterprise Edition the license grants changes', async () => {
    vi.useFakeTimers({ toFake: ['Date'] });
    const trial = { ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa, { type: 'trial', notAfter: new Date(Date.now() + 60 * 60 * 1000) }) };
    await heartbeat(trial);
    expect(publishCacheResetEvent).toHaveBeenCalledTimes(1);
    expect(publishCacheResetEvent).toHaveBeenCalledWith('Settings');

    await heartbeat(trial);
    expect(publishCacheResetEvent).toHaveBeenCalledTimes(1);

    // Expired between two heartbeats: the next one publishes the return to Community Edition.
    vi.setSystemTime(Date.now() + 2 * 60 * 60 * 1000);
    await heartbeat(trial);
    expect(xtmLicenseVerdict().granted).toBe(false);
    expect(publishCacheResetEvent).toHaveBeenCalledTimes(2);
  });

  it('lets a node that did not register load the proof from the shared answer', async () => {
    await heartbeat({ ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa) });
    setCurrentXtmLicenseProof(null);
    expect(xtmLicenseVerdict().granted).toBe(false);

    await refreshXtmLicenseProof();
    expect(xtmLicenseVerdict().granted).toBe(true);
  });

  it('drops the proof when the stored answer lapses while XTM One is unreachable', async () => {
    await heartbeat({ ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa) });
    expect(xtmLicenseVerdict().granted).toBe(true);

    redisRegistrationResult = null;
    vi.mocked(xtmOneClient.register).mockResolvedValue(null);
    await registerWithXtmOne(mockContext, mockUser);
    expect(xtmLicenseVerdict().granted).toBe(false);
  });

  it('advertises approval prompts once the entitlement of the previous answer is verified', async () => {
    const xtmLicense = { ee_sources: ['xtm_sublicense'], xtm_license_pem: createTestXtmLicense(xtmCa) };
    await heartbeat(xtmLicense);
    await heartbeat(xtmLicense);

    const [first, second] = vi.mocked(xtmOneClient.register).mock.calls.map(([input]) => input);
    expect(first.supports_approval_prompts).toBe(false);
    expect(second.supports_approval_prompts).toBe(true);
  });
});
