import { createHash, X509Certificate } from 'node:crypto';
import forge from 'node-forge';
import { describe, expect, it, vi } from 'vitest';

// The pinned XTM CA is swapped for a CA generated by the test, whose key signs the licenses below.
const anchor = vi.hoisted(() => ({ certificate: undefined as unknown }));
vi.mock('../../../../src/enterprise-edition/xtm_ca', () => ({
  get XTM_CA() {
    return anchor.certificate;
  },
}));

import { LICENSE_OID_XTM_OPENCTI_IDS, verifyXtmLicenseProof } from '../../../../src/modules/xtm/one/xtm-one-license';
import type { XtmLicenseContext } from '../../../../src/modules/xtm/one/xtm-one-license';
import { createTestCertificateAuthority, createTestXtmLicense, DAY } from '../../../utils/xtmLicenseHelper';
import type { TestXtmLicenseOptions } from '../../../utils/xtmLicenseHelper';

const xtmCa = createTestCertificateAuthority();
anchor.certificate = xtmCa.certificate;
const foreignCa = createTestCertificateAuthority();

const PLATFORM_ID = 'platform-0001';
const context = (overrides: Partial<XtmLicenseContext> = {}): XtmLicenseContext => ({
  platformId: PLATFORM_ID,
  platformCreatedAt: new Date(Date.now() - 365 * DAY),
  ...overrides,
});
const verify = (options: TestXtmLicenseOptions = {}, overrides: Partial<XtmLicenseContext> = {}) => {
  return verifyXtmLicenseProof(createTestXtmLicense(xtmCa, options), context(overrides));
};

describe('verifyXtmLicenseProof: the XTM license XTM One returns at registration', () => {
  describe('grants the XTM One entitlement', () => {
    it('for a license sub-licensing every OpenCTI platform', () => {
      const verification = verify({ openctiIds: ['global'] });
      expect(verification.granted).toBe(true);
      expect(verification.licenseType).toBe('standard');
    });

    it('for a license listing this platform id', () => {
      expect(verify({ openctiIds: ['platform-0002', PLATFORM_ID] }).granted).toBe(true);
    });

    it('whatever the subject says: the XTM One instance in the OU is not checked', () => {
      // The license of the helper is issued for 'another-xtm-one-instance'.
      expect(verify({ openctiIds: [PLATFORM_ID] }).granted).toBe(true);
    });

    it('from the legacy product and type extensions', () => {
      expect(verify({ legacyOids: true }).granted).toBe(true);
    });

    it('from extension values wrapped in a DER string', () => {
      expect(verify({ derStrings: true, openctiIds: [PLATFORM_ID] }).granted).toBe(true);
    });

    it('from a sub-license list longer than a short DER length', () => {
      expect(verify({ openctiIds: [...Array.from({ length: 9 }, (_, index) => `another-platform-${index}`), PLATFORM_ID] }).granted).toBe(true);
    });

    it('from extension values surrounded by whitespace', () => {
      expect(verify({ product: ' filigran xtm\n', type: 'lts ', openctiIds: ` ["${PLATFORM_ID}"] ` }).granted).toBe(true);
    });

    it('when the issuer name is not the CA subject: only the signature counts', () => {
      const certificate = forge.pki.certificateFromPem(createTestXtmLicense(xtmCa));
      certificate.setIssuer([{ name: 'commonName', value: 'Somebody else' }]);
      certificate.sign(xtmCa.privateKey, forge.md.sha256.create());
      expect(verifyXtmLicenseProof(forge.pki.certificateToPem(certificate), context()).granted).toBe(true);
    });

    it('when the license is signed over SHA-512', () => {
      expect(verify({ digest: forge.md.sha512.create() }).granted).toBe(true);
    });
  });

  describe('does not grant it', () => {
    it.each([undefined, null, ''])('without a certificate (%s)', (pem) => {
      expect(verifyXtmLicenseProof(pem, context())).toEqual({ granted: false, reason: 'XTM One returned no XTM license certificate' });
    });

    it('for a value that is not a PEM certificate', () => {
      expect(verifyXtmLicenseProof('ee_enabled', context()).granted).toBe(false);
      expect(verifyXtmLicenseProof({ pem: createTestXtmLicense(xtmCa) }, context()).granted).toBe(false);
    });

    it('for two certificates, even if the first one is valid', () => {
      const pem = `${createTestXtmLicense(xtmCa)}${createTestXtmLicense(xtmCa)}`;
      expect(verifyXtmLicenseProof(pem, context()).reason).toBe('the XTM license is not a single PEM certificate');
    });

    it('for a certificate travelling with a key', () => {
      const key = forge.pki.privateKeyToPem(forge.pki.rsa.generateKeyPair({ bits: 1024 }).privateKey);
      expect(verifyXtmLicenseProof(`${createTestXtmLicense(xtmCa)}${key}`, context()).granted).toBe(false);
    });

    it('for a license signed by another CA with the same subject', () => {
      const verification = verifyXtmLicenseProof(createTestXtmLicense(foreignCa), context());
      expect(verification).toEqual({ granted: false, reason: 'the XTM license is not signed by the Filigran XTM CA' });
    });

    it('for a tampered license', () => {
      const pem = createTestXtmLicense(xtmCa, { openctiIds: ['platform-0002'] });
      const der = forge.pem.decode(pem)[0].body;
      expect(der).toContain('platform-0002');
      const tampered = forge.pem.encode({ type: 'CERTIFICATE', body: der.replace('platform-0002', PLATFORM_ID) });
      expect(verifyXtmLicenseProof(tampered, context()).reason).toBe('the XTM license is not signed by the Filigran XTM CA');
    });

    it('for a license signed over SHA-1', () => {
      expect(verify({ digest: forge.md.sha1.create() }).reason).toBe('the XTM license is not signed by the Filigran XTM CA');
    });

    it('for a certificate of another product', () => {
      expect(verify({ product: 'opencti' }).reason).toBe('the certificate is not an XTM license');
      expect(verify({ product: null }).reason).toBe('the certificate is not an XTM license');
    });

    it('for an unknown license type', () => {
      expect(verify({ type: 'enterprise' }).reason).toBe('the XTM license type is unknown');
    });

    it('for a license sub-licensing other OpenCTI platforms only', () => {
      expect(verify({ openctiIds: ['platform-0002'] }).reason).toBe('the XTM license does not sub-license this OpenCTI platform');
      expect(verify({ openctiIds: ['PLATFORM-0001'] }).granted).toBe(false);
    });

    it('for a license sub-licensing other products only', () => {
      const openCrqIds = { id: '1.3.6.1.4.1.62944.90', value: '["global"]' };
      const openAevIds = { id: '1.3.6.1.4.1.62944.60', value: `["${PLATFORM_ID}"]` };
      const verification = verify({ openctiIds: null, extraExtensions: [openCrqIds, openAevIds] });
      expect(verification.reason).toBe('the XTM license does not sub-license this OpenCTI platform');
    });

    it.each(['["global"', '{"global": true}', '"global"', 'global'])('for a sub-license that is not a JSON list (%s)', (openctiIds) => {
      expect(verify({ openctiIds }).granted).toBe(false);
    });

    it('for extension values XTM One does not unwrap either: a long-form DER length or an empty DER string', () => {
      // XTM One only skips a DER header whose one length byte covers the rest of the value: it would read no list
      // here and never sub-license the platform, so granting it here would be granting what XTM One refuses.
      const ids = JSON.stringify([...Array.from({ length: 9 }, (_, index) => `another-platform-${index}`), PLATFORM_ID]);
      expect(ids.length).toBeGreaterThan(127);
      const longFormList = { id: LICENSE_OID_XTM_OPENCTI_IDS, value: String.fromCharCode(0x0c, 0x81, ids.length) + ids };
      expect(verify({ openctiIds: null, extraExtensions: [longFormList] }).granted).toBe(false);
      expect(verify({ type: '\u000c\u0000' }).reason).toBe('the XTM license type is unknown');
    });

    it('for a license repeating an extension', () => {
      const duplicate = { id: LICENSE_OID_XTM_OPENCTI_IDS, value: `["${PLATFORM_ID}"]` };
      expect(verify({ openctiIds: ['platform-0002'], extraExtensions: [duplicate] }).reason).toBe('the XTM license repeats a certificate extension');
    });
  });

  describe('applies the validity dates of XTM One', () => {
    it.each(['standard', 'lts', 'nfr'])('keeps an expired %s license during 90 days of grace', (type) => {
      expect(verify({ type, notAfter: new Date(Date.now() - 89 * DAY) }).granted).toBe(true);
      expect(verify({ type, notAfter: new Date(Date.now() - 91 * DAY) }).reason).toBe('the XTM license has expired and its 90-day grace period is over');
    });

    it('counts the grace period in days rather than calendar months', () => {
      const notAfter = new Date(Date.now() - DAY);
      // Certificate dates keep whole seconds.
      const notAfterInCertificate = Math.floor(notAfter.getTime() / 1000) * 1000;
      expect(verify({ notAfter }).validUntil?.getTime()).toBe(notAfterInCertificate + 90 * DAY);
    });

    it('does not enforce the start date of a standard license', () => {
      expect(verify({ notBefore: new Date(Date.now() + 30 * DAY), notAfter: new Date(Date.now() + 400 * DAY) }).granted).toBe(true);
    });

    it('reads a license without type as a trial, which has no grace period and must have started', () => {
      expect(verify({ type: null }).licenseType).toBe('trial');
      expect(verify({ type: '' }).granted).toBe(true);
      expect(verify({ type: 'trial', notAfter: new Date(Date.now() - 60 * 1000) }).reason).toBe('the trial XTM license has expired');
      expect(verify({ type: 'trial', notBefore: new Date(Date.now() + DAY) }).reason).toBe('the trial XTM license is not valid yet');
    });

    it('ends a ci license 45 minutes after this platform was created', () => {
      const ci = { type: 'ci', notAfter: new Date(Date.now() + 365 * DAY) };
      const recentPlatform = verify(ci, { platformCreatedAt: new Date(Date.now() - 10 * 60 * 1000) });
      expect(recentPlatform.granted).toBe(true);
      expect(recentPlatform.validUntil?.getTime()).toBeLessThan(Date.now() + 36 * 60 * 1000);
      expect(verify(ci, { platformCreatedAt: new Date(Date.now() - 50 * 60 * 1000) }).reason).toBe('the ci XTM license has expired');
      // settings.created_at can be a string
      expect(verify(ci, { platformCreatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() }).granted).toBe(true);
    });

    it('ends a ci license a year after its start at the latest, and never before it', () => {
      const created = { platformCreatedAt: new Date() };
      expect(verify({ type: 'ci', notBefore: new Date(Date.now() - 366 * DAY), notAfter: new Date(Date.now() + DAY) }, created).granted).toBe(false);
      expect(verify({ type: 'ci', notBefore: new Date(Date.now() + DAY) }, created).reason).toBe('the ci XTM license is not valid yet');
    });

    it('refuses a ci license when the platform creation date is unknown', () => {
      expect(verify({ type: 'ci' }, { platformCreatedAt: undefined }).reason).toBe('the ci XTM license cannot be dated without the platform creation date');
      expect(verify({ type: 'ci' }, { platformCreatedAt: 'not a date' }).granted).toBe(false);
    });

    it('verifies the dates at the time of the check', () => {
      const pem = createTestXtmLicense(xtmCa, { type: 'trial', notAfter: new Date(Date.now() + DAY) });
      expect(verifyXtmLicenseProof(pem, context()).granted).toBe(true);
      expect(verifyXtmLicenseProof(pem, context({ now: new Date(Date.now() + 2 * DAY) })).granted).toBe(false);
    });
  });
});

describe('XTM_CA_PEM: the trust anchor pinned in the build', () => {
  it('is the XTM CA certificate XTM One verifies the XTM licenses with', async () => {
    const { XTM_CA_PEM } = await vi.importActual<typeof import('../../../../src/enterprise-edition/xtm_ca')>('../../../../src/enterprise-edition/xtm_ca');
    const certificate = new X509Certificate(XTM_CA_PEM);
    const subjectPublicKeyInfo = certificate.publicKey.export({ type: 'spki', format: 'der' });
    expect(certificate.fingerprint256).toBe('43:6E:0B:82:14:0F:43:CA:0E:15:3F:1B:27:AC:E3:B3:88:F1:9F:24:BC:6C:36:6E:C1:24:91:87:45:BC:40:64');
    expect(createHash('sha256').update(subjectPublicKeyInfo).digest('hex')).toBe('9ef09cc6ab116344afd1a47ae5b777842b8c44fae78d223440d19bb7bc7d84ec');
  });
});
