define

  ## PROPERTIES

  # Common
  internal_id sub attribute, value string;
  standard_id sub attribute, value string;
  entity_type sub attribute, value string;
  created_at sub attribute, value datetime;
  created_at_day sub attribute, value string;
  created_at_month sub attribute, value string;
  created_at_year sub attribute, value string;
  updated_at sub attribute, value datetime;
  name sub attribute, value string;
  description sub attribute, value string;
  x_opencti_graph_data sub attribute, value string;
  issuer sub attribute, value string;
  revoked sub attribute, value boolean;

  # STIX Common
  spec_version sub attribute, value string;
  stix_ids sub attribute, value string;
  created sub attribute, value datetime;
  modified sub attribute, value datetime;
  confidence sub attribute, value long;
  lang sub attribute, value string;

  # STIX General
  first_seen sub attribute, value datetime;
  first_seen_day sub attribute, value string;
  first_seen_month sub attribute, value string;
  first_seen_year sub attribute, value string;
  last_seen sub attribute, value datetime;
  last_seen_day sub attribute, value string;
  last_seen_month sub attribute, value string;
  last_seen_year sub attribute, value string;

  # Internal Relationships
  grant sub attribute, value string;

  # STIX Core Relationship
  relationship_type sub attribute, value string;
  start_time sub attribute, value datetime;
  start_time_day sub attribute, value string;
  start_time_month sub attribute, value string;
  start_time_year sub attribute, value string;
  stop_time sub attribute, value datetime;
  stop_time_day sub attribute, value string;
  stop_time_month sub attribute, value string;
  stop_time_year sub attribute, value string;

  # STIX Sighting Relationship
  attribute_count sub attribute, value long;
  x_opencti_negative sub attribute, value boolean;

  # Internal Entities
  platform_title sub attribute, value string;
  platform_language sub attribute, value string;
  platform_email sub attribute, value string;
  platform_url sub attribute, value string;
  title sub attribute, value string;
  timestamp sub attribute, value long;
  lastRun sub attribute, value string;
  uuid sub attribute, value string;
  duration sub attribute, value string;
  firstname sub attribute, value string;
  lastname sub attribute, value string;
  user_email sub attribute, value string;
  password sub attribute, value string;
  language sub attribute, value string;
  external sub attribute, value boolean;
  default_assignation sub attribute, value boolean;
  attribute_order sub attribute, value double;
  active sub attribute, value boolean;
  connector_type sub attribute, value string;
  connector_scope sub attribute, value string;
  connector_state sub attribute, value string;
  connector_state_reset sub attribute, value boolean;
  workspace_type sub attribute, value string;
  workspace_data sub attribute, value string;

  # STIX Object
  value sub attribute, value string;
  url sub attribute, value string;

  # STIX Meta Objects
  definition_type sub attribute, value string;
  definition sub attribute, value string;
  x_opencti_order  sub attribute, value long;
  x_opencti_color sub attribute, value string;
  color sub attribute, value string;
  source_name sub attribute, value string;
  hash sub attribute, value string;
  external_id sub attribute, value string;
  kill_chain_name sub attribute, value string;
  phase_name sub attribute, value string;

  # STIX Core Objects

  # STIX Domain Object
  aliases sub attribute, value string;
  i_aliases_ids sub attribute, value string;
  x_opencti_aliases sub attribute, value string;
  x_mitre_detection sub attribute, value string;
  x_mitre_platforms sub attribute, value string;
  x_mitre_permissions_required sub attribute, value string;
  x_mitre_id sub attribute, value string;
  contact_information sub attribute, value string;
  x_opencti_firstname sub attribute, value string;
  x_opencti_lastname sub attribute, value string;
  x_opencti_organization_type sub attribute, value string;
  x_opencti_reliability sub attribute, value string;
  latitude sub attribute, value double;
  longitude sub attribute, value double;
  precision sub attribute, value double;
  objective sub attribute, value string;
  hashes sub attribute, value string;
  pattern_type sub attribute, value string;
  pattern_version sub attribute, value string;
  pattern sub attribute, value string;
  indicator_types sub attribute, value string;
  valid_from sub attribute, value datetime;
  valid_from_day sub attribute, value string;
  valid_from_month sub attribute, value string;
  valid_from_year sub attribute, value string;
  valid_until sub attribute, value datetime;
  valid_until_day sub attribute, value string;
  valid_until_month sub attribute, value string;
  valid_until_year sub attribute, value string;
  x_opencti_score sub attribute, value long;
  x_opencti_detection sub attribute, value boolean;
  x_opencti_main_observable_type sub attribute, value string;
  infrastructure_types sub attribute, value string;
  goals sub attribute, value string;
  resource_level sub attribute, value string;
  primary_motivation sub attribute, value string;
  secondary_motivations sub attribute, value string;
  street_address sub attribute, value string;
  postal_code sub attribute, value string;
  malware_types sub attribute, value string;
  is_family sub attribute, value boolean;
  architecture_execution_envs sub attribute, value string;
  implementation_languages sub attribute, value string;
  capabilities sub attribute, value string;
  attribute_abstract  sub attribute, value string;
  content sub attribute, value string;
  authors sub attribute, value string;
  first_observed sub attribute, value datetime;
  last_observed sub attribute, value datetime;
  number_observed sub attribute, value long;
  explanation sub attribute, value string;
  opinion sub attribute, value string;
  report_types sub attribute, value string;
  x_opencti_report_status sub attribute, value long;
  published sub attribute, value datetime;
  published_day sub attribute, value string;
  published_month sub attribute, value string;
  published_year sub attribute, value string;
  threat_actor_types sub attribute, value string;
  sophistication sub attribute, value string;
  personal_motivations sub attribute, value string;
  roles sub attribute, value string;
  tool_types sub attribute, value string;
  tool_version sub attribute, value string;
  x_opencti_base_score sub attribute, value double;
  x_opencti_base_severity sub attribute, value string;
  x_opencti_attack_vector sub attribute, value string;
  x_opencti_integrity_impact sub attribute, value string;
  x_opencti_availability_impact sub attribute, value string;
  identity_class sub attribute, value string;
  x_opencti_location_type sub attribute, value string;

  # STIX Cyber Observables
  x_opencti_description sub attribute, value string;
  mime_type sub attribute, value string;
  payload_bin sub attribute, value string;
  encryption_algorithm sub attribute, value string;
  decryption_key sub attribute, value string;
  number sub attribute, value long;
  rir sub attribute, value string;
  path sub attribute, value string;
  path_enc sub attribute, value string;
  ctime sub attribute, value datetime;
  mtime sub attribute, value datetime;
  atime sub attribute, value datetime;
  display_name sub attribute, value string;
  is_multipart sub attribute, value boolean;
  attribute_date sub attribute, value datetime;
  content_type sub attribute, value string;
  message_id sub attribute, value string;
  subject sub attribute, value string;
  received_lines sub attribute, value string;
  body sub attribute, value string;
  content_disposition sub attribute, value string;
  size sub attribute, value long;
  extensions sub attribute, value string;
  name_enc sub attribute, value string;
  magic_number_hex sub attribute, value string;
  start sub attribute, value datetime;
  end sub attribute, value datetime;
  is_active sub attribute, value boolean;
  protocols sub attribute, value string;
  src_port sub attribute, value long;
  dst_port sub attribute, value long;
  src_byte_count sub attribute, value long;
  dst_byte_count sub attribute, value long;
  src_packets sub attribute, value long;
  dst_packets sub attribute, value long;
  is_hidden sub attribute, value boolean;
  pid sub attribute, value long;
  created_time sub attribute, value datetime;
  cwd sub attribute, value string;
  command_line sub attribute, value string;
  environment_variables sub attribute, value string;
  cpe sub attribute, value string;
  swid sub attribute, value string;
  languages sub attribute, value string;
  vendor sub attribute, value string;
  version sub attribute, value string;
  user_id sub attribute, value string;
  credential sub attribute, value string;
  account_login sub attribute, value string;
  account_type sub attribute, value string;
  is_service_account sub attribute, value boolean;
  is_privileged sub attribute, value boolean;
  can_escalate_privs sub attribute, value boolean;
  is_disabled sub attribute, value boolean;
  account_created sub attribute, value datetime;
  account_expires sub attribute, value datetime;
  credential_last_changed sub attribute, value datetime;
  account_first_login sub attribute, value datetime;
  account_last_login sub attribute, value datetime;
  attribute_key sub attribute, value string;
  modified_time sub attribute, value datetime;
  number_of_subkeys sub attribute, value double;
  data sub attribute, value string;
  data_type sub attribute, value string;
  is_self_signed sub attribute, value boolean;
  serial_number sub attribute, value string;
  signature_algorithm sub attribute, value string;
  validity_not_before sub attribute, value datetime;
  validity_not_after sub attribute, value datetime;
  subject_public_key_algorithm sub attribute, value string;
  subject_public_key_modulus sub attribute, value string;
  subject_public_key_exponent sub attribute, value string;
  basic_constraints sub attribute, value string;
  name_constraints sub attribute, value string;
  policy_constraints sub attribute, value string;
  key_usage sub attribute, value string;
  extended_key_usage sub attribute, value string;
  subject_key_identifier sub attribute, value string;
  authority_key_identifier sub attribute, value string;
  subject_alternative_name sub attribute, value string;
  issuer_alternative_name sub attribute, value string;
  subject_directory_attributes sub attribute, value string;
  crl_distribution_points sub attribute, value string;
  inhibit_any_policy sub attribute, value string;
  private_key_usage_period_not_before sub attribute, value datetime;
  private_key_usage_period_not_after sub attribute, value datetime;
  certificate_policies sub attribute, value string;
  policy_mappings sub attribute, value string;


  ## ROLES

  # Internal Relations
  authorized-by_from sub role;
  authorized-by_to sub role;
  migrates_from sub role;
  migrates_to sub role;
  member-of_from sub role;
  member-of_to sub role;
  allowed-by_from sub role;
  allowed-by_to sub role;
  has-role_from sub role;
  has-role_to sub role;
  has-capability_from sub role;
  has-capability_to sub role;

  # STIX Knowledge Relationships
  delivers_from sub role;
  delivers_to sub role;
  targets_from sub role;
  targets_to sub role;
  uses_from sub role;
  uses_to sub role;
  attributed-to_from sub role;
  attributed-to_to sub role;
  compromises_from sub role;
  compromises_to sub role;
  originates-from_from sub role;
  originates-from_to sub role;
  investigates_from sub role;
  investigates_to sub role;
  mitigates_from sub role;
  mitigates_to sub role;
  located-at_from sub role;
  located-at_to sub role;
  indicates_from sub role;
  indicates_to sub role;
  based-on_from sub role;
  based-on_to sub role;
  communicates-with_from sub role;
  communicates-with_to sub role;
  consists-of_from sub role;
  consists-of_to sub role;
  controls_from sub role;
  controls_to sub role;
  relation-has_from sub role;
  relation-has_to sub role;
  hosts_from sub role;
  hosts_to sub role;
  owns_from sub role;
  owns_to sub role;
  authored-by_from sub role;
  authored-by_to sub role;
  beacons-to_from sub role;
  beacons-to_to sub role;
  exfiltrate-to_from sub role;
  exfiltrate-to_to sub role;
  downloads_from sub role;
  downloads_to sub role;
  drops_from sub role;
  drops_to sub role;
  exploits_from sub role;
  exploits_to sub role;
  variant-of_from sub role;
  variant-of_to sub role;
  characterizes_from sub role;
  characterizes_to sub role;
  analysis-of_from sub role;
  analysis-of_to sub role;
  static-analysis-of_from sub role;
  static-analysis-of_to sub role;
  dynamic-analysis-of_from sub role;
  dynamic-analysis-of_to sub role;
  impersonates_from sub role;
  impersonates_to sub role;
  remediates_from sub role;
  remediates_to sub role;
  related-to_from sub role;
  related-to_to sub role;
  derived-from_from sub role;
  derived-from_to sub role;
  duplicate-of_from sub role;
  duplicate-of_to sub role;
  part-of_from sub role;
  part-of_to sub role;
  subtechnique-of_from sub role;
  subtechnique-of_to sub role;

  # STIX Sighting Relationships
  stix-sighting-relationship_from sub role;
  stix-sighting-relationship_to sub role;

  # STIX Meta Relationships
  object-label_from sub role;
  object-label_to sub role;
  created-by_from sub role;
  created-by_to sub role;
  object-marking_from sub role;
  object-marking_to sub role;
  object_from sub role;
  object_to sub role;
  external-reference_from sub role;
  external-reference_to sub role;
  kill-chain-phase_from sub role;
  kill-chain-phase_to sub role;


  ## RELATIONS

  basic-relationship sub relation,
    abstract,
    key internal_id,
    key standard_id,
    has entity_type,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at;

  # Internal relations
  internal-relationship sub basic-relationship,
    abstract;

  authorized-by sub internal-relationship,
    relates authorized-by_from,
    relates authorized-by_to;

  migrates sub internal-relationship,
    relates migrates_from,
    relates migrates_to;

  member-of sub internal-relationship,
    relates member-of_from,
    relates member-of_to;

  allowed-by sub internal-relationship,
    has grant,
    relates allowed-by_from,
    relates allowed-by_to;

  has-role sub internal-relationship,
    relates has-role_from,
    relates has-role_to;

  has-capability sub internal-relationship,
    relates has-capability_from,
    relates has-capability_to;

  # STIX relations
  stix-relationship sub basic-relationship,
    abstract,
    has stix_ids,
    has spec_version,
    has revoked,
    has confidence,
    has lang,
    has created,
    has modified,
    plays object_to;

  # STIX Core Relationships
  stix-core-relationship sub stix-relationship,
    abstract,
    has relationship_type,
    has description,
    has start_time,
    has start_time_day,
    has start_time_month,
    has start_time_year,
    has stop_time,
    has stop_time_day,
    has stop_time_month,
    has stop_time_year,
    plays created-by_from,
    plays object-marking_from,
    plays object-label_from,
    plays external-reference_from,
    plays duplicate-of_from,
    plays derived-from_from,
    plays related-to_from,
    plays duplicate-of_to,
    plays derived-from_to,
    plays related-to_to;

  delivers sub stix-core-relationship,
    relates delivers_from,
    relates delivers_to,
    plays indicates_to;

  targets sub stix-core-relationship,
    relates targets_from,
    relates targets_to,
    plays located-at_from;

  uses sub stix-core-relationship,
    relates uses_from,
    relates uses_to,
    plays kill-chain-phase_from,
    plays indicates_to;

  attributed-to sub stix-core-relationship,
    relates attributed-to_from,
    relates attributed-to_to;

  compromises sub stix-core-relationship,
    relates compromises_from,
    relates compromises_to;

  originates-from sub stix-core-relationship,
    relates originates-from_from,
    relates originates-from_to;

  investigates sub stix-core-relationship,
    relates investigates_from,
    relates investigates_to;

  mitigates sub stix-core-relationship,
    relates mitigates_from,
    relates mitigates_to;

  located-at sub stix-core-relationship,
    relates located-at_from,
    relates located-at_to;

  indicates sub stix-core-relationship,
    plays kill-chain-phase_from,
    relates indicates_from,
    relates indicates_to;

  based-on sub stix-core-relationship,
    relates based-on_from,
    relates based-on_to;

  communicates-with sub stix-core-relationship,
    relates communicates-with_from,
    relates communicates-with_to,
    plays indicates_to;

  consists-of sub stix-core-relationship,
    relates consists-of_from,
    relates consists-of_to;

  controls sub stix-core-relationship,
    relates controls_from,
    relates controls_to;

  relation-has sub stix-core-relationship,
    relates relation-has_from,
    relates relation-has_to;

  hosts sub stix-core-relationship,
    relates hosts_from,
    relates hosts_to;

  owns sub stix-core-relationship,
    relates owns_from,
    relates owns_to;

  authored-by sub stix-core-relationship,
    relates authored-by_from,
    relates authored-by_to;

  beacons-to sub stix-core-relationship,
    relates beacons-to_from,
    relates beacons-to_to,
    plays indicates_to;

  exfiltrate-to sub stix-core-relationship,
    relates exfiltrate-to_from,
    relates exfiltrate-to_to;

  downloads sub stix-core-relationship,
    relates downloads_from,
    relates downloads_to;

  drops sub stix-core-relationship,
    plays kill-chain-phase_from,
    relates drops_from,
    relates drops_to;

  exploits sub stix-core-relationship,
    plays kill-chain-phase_from,
    relates exploits_from,
    relates exploits_to,
    plays indicates_to;

  variant-of sub stix-core-relationship,
    relates variant-of_from,
    relates variant-of_to;

  characterizes sub stix-core-relationship,
    relates characterizes_from,
    relates characterizes_to;

  analysis-of sub stix-core-relationship,
    relates analysis-of_from,
    relates analysis-of_to;

  static-analysis-of sub stix-core-relationship,
    relates static-analysis-of_from,
    relates static-analysis-of_to;

  dynamic-analysis-of sub stix-core-relationship,
    relates dynamic-analysis-of_from,
    relates dynamic-analysis-of_to;

  impersonates sub stix-core-relationship,
    relates impersonates_from,
    relates impersonates_to;

  remediates sub stix-core-relationship,
    relates remediates_from,
    relates remediates_to;

  related-to sub stix-core-relationship,
    relates related-to_from,
    relates related-to_to;

  derived-from sub stix-core-relationship,
    relates derived-from_from,
    relates derived-from_to;

  duplicate-of sub stix-core-relationship,
    relates duplicate-of_from,
    relates duplicate-of_to;

  part-of sub stix-core-relationship,
    relates part-of_from,
    relates part-of_to;

  subtechnique-of sub stix-core-relationship,
    relates subtechnique-of_from,
    relates subtechnique-of_to;

  revoked-by sub stix-core-relationship,
    relates revoked-by_from,
    relates revoked-by_to;

  # STIX Sighting Relationships
  stix-sighting-relationship sub stix-relationship,
    has description,
    has first_seen,
    has first_seen_day,
    has first_seen_month,
    has first_seen_year,
    has last_seen,
    has last_seen_day,
    has last_seen_month,
    has last_seen_year,
    has attribute_count,
    has x_opencti_negative,
    has confidence,
    plays created-by_from,
    plays object-marking_from,
    plays object-label_from,
    plays external-reference_from,
    relates stix-sighting-relationship_from,
    relates stix-sighting-relationship_to;

  # STIX Meta Relationships
  stix-meta-relationship sub stix-relationship,
    abstract;

  created-by sub stix-meta-relationship,
    relates created-by_from,
    relates created-by_to;

  object-marking sub stix-meta-relationship,
    relates object-marking_from,
    relates object-marking_to;

  object sub stix-meta-relationship,
    relates object_from,
    relates object_to;

  # STIX Internal Meta Relationships
  internal-meta-relationship sub stix-meta-relationship,
    abstract;

  object-label sub stix-meta-relationship,
    relates object-label_from,
    relates object-label_to;

  external-reference sub internal-meta-relationship,
    relates external-reference_from,
    relates external-reference_to;

  kill-chain-phase sub internal-meta-relationship,
    relates kill-chain-phase_from,
    relates kill-chain-phase_to;

  # STIX Cyber Observable Relationships
  stix-cyber-observable-relationship sub stix-relationship,
    abstract,
    has relationship_type,
    has start_time,
    has start_time_day,
    has start_time_month,
    has start_time_year,
    has stop_time,
    has stop_time_day,
    has stop_time_month,
    has stop_time_year;

  operating-system sub stix-cyber-observable-relationship,
    relates operating-system_from,
    relates operating-system_to;

  sample sub stix-cyber-observable-relationship,
    relates sample_from,
    relates sample_to;

  contains sub stix-cyber-observable-relationship,
    relates contains_from,
    relates contains_to;

  resolves-to sub stix-cyber-observable-relationship,
    relates resolves-to_from,
    relates resolves-to_to;

  belongs-to sub stix-cyber-observable-relationship,
    relates belongs-to_from,
    relates belongs-to_to;

  from sub stix-cyber-observable-relationship,
    relates from_from,
    relates from_to;

  sender sub stix-cyber-observable-relationship,
    relates sender_from,
    relates sender_to;

  to sub stix-cyber-observable-relationship,
    relates to_from,
    relates to_to;

  cc sub stix-cyber-observable-relationship,
    relates cc_from,
    relates cc_to;

  bcc sub stix-cyber-observable-relationship,
    relates bcc_from,
    relates bcc_to;

  raw-email sub stix-cyber-observable-relationship,
    relates raw-email_from,
    relates raw-email_to;

  body-raw sub stix-cyber-observable-relationship,
    relates body-raw_from,
    relates body-raw_to;

  parent-directory sub stix-cyber-observable-relationship,
    relates parent-directory_from,
    relates parent-directory_to;

  relation-content sub stix-cyber-observable-relationship,
    relates relation-content_from,
    relates relation-content_to;

  src sub stix-cyber-observable-relationship,
    relates src_from,
    relates src_to;

  dst sub stix-cyber-observable-relationship,
    relates dst_from,
    relates dst_to;

  src-payload sub stix-cyber-observable-relationship,
    relates src-payload_from,
    relates src-payload_to;

  dst-payload sub stix-cyber-observable-relationship,
    relates dst-payload_from,
    relates dst-payload_to;

  encapsulates sub stix-cyber-observable-relationship,
    relates encapsulates_from,
    relates encapsulates_to;

  encapsulated-by sub stix-cyber-observable-relationship,
    relates encapsulates-by_from,
    relates encapsulates-by_to;

  opened-connection sub stix-cyber-observable-relationship,
    relates opened-connection_from,
    relates opened-connection_to;

  creator-user sub stix-cyber-observable-relationship,
    relates creator-user_from,
    relates creator-user_to;

  image sub stix-cyber-observable-relationship,
    relates image_from,
    relates image_to;

  parent sub stix-cyber-observable-relationship,
    relates parent_from,
    relates parent_to;

  child sub stix-cyber-observable-relationship,
    relates child_from,
    relates child_to;

  # Interrnal Cyber Observable Relationships
  internal-cyber-observable-relationship sub stix-cyber-observable-relationship,
      abstract;

  body-multipart sub internal-cyber-observable-relationship,
    relates body-multipart_from,
    relates body-multipart_to;

  values sub internal-cyber-observable-relationship,
    relates values_from,
    relates values_to;

  x509-v3-extensions sub internal-cyber-observable-relationship,
    relates x509-v3-extensions_from,
    relates x509-v3-extensions_to;


  ## ENTITIES

  Basic-Object sub entity,
    abstract,
    key internal_id,
    key standard_id,
    has entity_type;

  # Internal entities
  Internal-Object sub Basic-Object,
    abstract;

  Settings sub Internal-Object,
    has platform_title,
    has platform_email,
    has platform_url,
    has platform_language,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at;

  MigrationStatus sub Internal-Object,
    has lastRun,
    plays migrates_from;

  MigrationReference sub Internal-Object,
    has title,
    has timestamp,
    plays migrates_to;

  Token sub Internal-Object,
    key uuid,
    has name,
    has duration,
    has issuer,
    has revoked,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at,
    plays authorized-by_to;

  Group sub Internal-Object,
    has name,
    has description,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at,
    plays member-of_to;

  User sub Internal-Object,
    has user_email,
    has password,
    has name,
    has description,
    has firstname,
    has lastname,
    has language,
    has external,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at,
    plays authorized-by_from,
    plays has-role_from,
    plays member-of_from,
    plays allowed-by_from;

  Role sub Internal-Object,
    key name,
    has default_assignation,
    has description,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at,
    plays allowed-by_to,
    plays has-capability_from,
    plays has-role_to;

  Capability sub Internal-Object,
    key name,
    has attribute_order,
    has description,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at,
    plays has-capability_to;

  Connector sub Internal-Object,
    has name,
    has active,
    has connector_type,
    has connector_scope,
    has connector_state,
    has connector_state_reset,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at;

  Workspace sub Internal-Object,
    has workspace_type,
    has name,
    has description,
    has x_opencti_graph_data,
    has workspace_data,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at;

  # STIX Object Entities
  Stix-Object sub Basic-Object,
    abstract,
    has stix_ids,
    has spec_version,
    has created_at,
    has created_at_day,
    has created_at_month,
    has created_at_year,
    has updated_at;

  # STIX Meta Object Entities
  Stix-Meta-Object sub Stix-Object,
    abstract,
    has created,
    has modified;

  Marking-Definition sub Stix-Meta-Object,
    has definition_type,
    has definition,
    has x_opencti_order,
    has x_opencti_color,
    plays object-marking_to;

  Label sub Stix-Meta-Object,
    key value,
    has color,
    plays object-label_to;

  External-Reference sub Stix-Meta-Object,
    has source_name,
    has description,
    has url,
    has hash,
    has external_id,
    plays external-reference_to;

  Kill-Chain-Phase sub Stix-Meta-Object,
    has kill_chain_name,
    has phase_name,
    has x_opencti_order,
    plays kill-chain-phase_to;

  Stix-Core-Object sub Stix-Object,
    abstract,
    plays created-by_from,
    plays object-marking_from,
    plays object-label_from,
    plays external-reference_from,
    plays object_to;

  # STIX Domain Object Entities
  Stix-Domain-Object sub Stix-Core-Object,
    abstract,
    has revoked,
    has confidence,
    has lang,
    has created,
    has modified,
    plays revoked-by_from,
    plays duplicate-of_from,
    plays derived-from_from,
    plays related-to_from,
    plays stix-sighting-relationship_from,
    plays revoked-by_to,
    plays duplicate-of_to,
    plays derived-from_to,
    plays related-to_to;

  Attack-Pattern sub Stix-Domain-Object,
    has name,
    has description,
    has aliases,
    has i_aliases_ids,
    has x_mitre_platforms,
    has x_mitre_permissions_required,
    has x_mitre_detection,
    has x_mitre_id,
    plays kill-chain-phase_from,
    plays subtechnique-of_from,
    plays delivers_from,
    plays targets_from,
    plays uses_from,
    plays subtechnique-of_to,
    plays indicates_to,
    plays mitigates_to,
    plays uses_to;

  Campaign sub Stix-Domain-Object,
    has name,
    has description,
    has aliases,
    has i_aliases_ids,
    has first_seen,
    has first_seen_day,
    has first_seen_month,
    has first_seen_year,
    has last_seen,
    has last_seen_day,
    has last_seen_month,
    has last_seen_year,
    has objective,
    plays attributed-to_from,
    plays compromises_from,
    plays originates-from_from,
    plays targets_from,
    plays uses_from,
    plays attributed-to_to,
    plays indicates_to;

  Container sub Stix-Domain-Object,
    abstract,
    plays object_from;

  Note sub Container,
    has attribute_abstract,
    has content,
    has authors;

  Observed-Data sub Container,
    has first_observed,
    has last_observed,
    has number_observed,
    plays object_to,
    plays based-on_to,
    plays consists-of_to;

  Opinion sub Container,
    has explanation,
    has authors,
    has opinion;

  Report sub Container,
    has name,
    has description,
    has report_types,
    has x_opencti_report_status,
    has published,
    has published_day,
    has published_year,
    has published_month,
    has x_opencti_graph_data;

  Course-Of-Action sub Stix-Domain-Object,
    has name,
    has description,
    has x_opencti_aliases,
    has i_aliases_ids,
    has x_mitre_id,
    plays mitigates_from,
    plays investigates_from,
    plays migrates_from,
    plays remediates_from;

  Identity sub Stix-Domain-Object,
    abstract,
    has name,
    has description,
    has contact_information,
    has identity_class,
    has roles,
    has x_opencti_aliases,
    has i_aliases_ids,
    plays located-at_from,
    plays part-of_from,
    plays stix-sighting-relationship_to,
    plays targets_to,
    plays attributed-to_to,
    plays impersonates_to;

  Individual sub Identity,
    has x_opencti_firstname,
    has x_opencti_lastname,
    plays created-by_to;

  Organization sub Identity,
    has x_opencti_organization_type,
    has x_opencti_reliability,
    plays created-by_to,
    plays part-of_to;

  Sector sub Identity,
    plays part-of_to;

  Indicator sub Stix-Domain-Object,
    has pattern_type,
    has pattern_version,
    key pattern,
    has name,
    has description,
    has indicator_types,
    has valid_from,
    has valid_from_day,
    has valid_from_month,
    has valid_from_year,
    has valid_until,
    has valid_until_day,
    has valid_until_month,
    has valid_until_year,
    has x_opencti_score,
    has x_opencti_detection,
    has x_opencti_main_observable_type,
    plays kill-chain-phase_from,
    plays indicates_from,
    plays based-on_from,
    plays investigates_to,
    plays mitigates_to;

  Infrastructure sub Stix-Domain-Object,
    has name,
    has description,
    has aliases,
    has i_aliases_ids,
    has infrastructure_types,
    has first_seen,
    has first_seen_day,
    has first_seen_month,
    has first_seen_year,
    has last_seen,
    has last_seen_day,
    has last_seen_month,
    has last_seen_year,
    plays kill-chain-phase_from,
    plays communicates-with_from,
    plays consists-of_from,
    plays controls_from,
    plays relation-has_from,
    plays hosts_from,
    plays located-at_from,
    plays uses_from,
    plays compromises_to,
    plays beacons-to_to,
    plays exfiltrate-to_to,
    plays hosts_to,
    plays indicates_to,
    plays owns_to,
    plays targets_to,
    plays uses_to;

  Intrusion-Set sub Stix-Domain-Object,
    has name,
    has description,
    has aliases,
    has i_aliases_ids,
    has first_seen,
    has first_seen_day,
    has first_seen_month,
    has first_seen_year,
    has last_seen,
    has last_seen_day,
    has last_seen_month,
    has last_seen_year,
    has goals,
    has resource_level,
    has primary_motivation,
    has secondary_motivations,
    plays attributed-to_from,
    plays compromises_from,
    plays hosts_from,
    plays owns_from,
    plays originates-from_from,
    plays targets_from,
    plays uses_from,
    plays attributed-to_to,
    plays authored-by_to,
    plays indicates_to;

  Location sub Stix-Domain-Object,
    abstract,
    has name,
    has description,
    has latitude,
    has longitude,
    has precision,
    has x_opencti_aliases,
    has i_aliases_ids,
    has x_opencti_location_type,
    plays located-at_from,
    plays stix-sighting-relationship_to,
    plays located-at_to,
    plays originates-from_to,
    plays targets_to;

  City sub Location;

  Country sub Location;

  Region sub Location;

  Position sub Location,
    has street_address,
    has postal_code;

  Malware sub Stix-Domain-Object,
    has name,
    has description,
    has aliases,
    has i_aliases_ids,
    has malware_types,
    has is_family,
    has first_seen,
    has first_seen_day,
    has first_seen_month,
    has first_seen_year,
    has last_seen,
    has last_seen_day,
    has last_seen_month,
    has last_seen_year,
    has architecture_execution_envs,
    has implementation_languages,
    has capabilities,
    plays kill-chain-phase_from,
    plays operating-system_from,
    plays sample_from,
    plays authorized-by_from,
    plays beacons-to_from,
    plays exfiltrate-to_from,
    plays communicates-with_from,
    plays controls_from,
    plays downloads_from,
    plays drops_from,
    plays exploits_from,
    plays originates-from_from,
    plays targets_from,
    plays uses_from,
    plays variant-of_from,
    plays variant-of_to,
    plays delivers_to,
    plays indicates_to,
    plays mitigates_to,
    plays remediates_to,
    plays uses_to,
    plays drops_to,
    plays controls_to,
    plays characterizes_to,
    plays static-analysis-of_to,
    plays dynamic-analysis-of_to;

  Threat-Actor sub Stix-Domain-Object,
    has name,
    has description,
    has aliases,
    has i_aliases_ids,
    has threat_actor_types,
    has first_seen,
    has first_seen_day,
    has first_seen_month,
    has first_seen_year,
    has last_seen,
    has last_seen_day,
    has last_seen_month,
    has last_seen_year,
    has goals,
    has sophistication,
    has resource_level,
    has primary_motivation,
    has secondary_motivations,
    has personal_motivations,
    plays attributed-to_from,
    plays compromises_from,
    plays hosts_from,
    plays owns_from,
    plays impersonates_from,
    plays located-at_from,
    plays targets_from,
    plays uses_from,
    plays attributed-to_to,
    plays authored-by_to,
    plays indicates_to;

  Tool sub Stix-Domain-Object,
    has name,
    has description,
    has aliases,
    has i_aliases_ids,
    has tool_types,
    has tool_version,
    plays kill-chain-phase_from,
    plays delivers_from,
    plays drops_from,
    plays relation-has_from,
    plays targets_from,
    plays uses_from,
    plays hosts_to,
    plays downloads_to,
    plays drops_to,
    plays indicates_to,
    plays uses_to;

  Vulnerability sub Stix-Domain-Object,
    has name,
    has description,
    has x_opencti_base_score,
    has x_opencti_base_severity,
    has x_opencti_attack_vector,
    has x_opencti_integrity_impact,
    has x_opencti_availability_impact,
    plays targets_to,
    plays exploits_to,
    plays mitigates_to,
    plays remediates_to,
    plays relation-has_to;

  X-OpenCTI-Incident sub Stix-Domain-Object,
    has name,
    has description,
    has aliases,
    has i_aliases_ids,
    has first_seen,
    has first_seen_day,
    has first_seen_month,
    has first_seen_year,
    has last_seen,
    has last_seen_day,
    has last_seen_month,
    has last_seen_year,
    has objective,
    plays attributed-to_from,
    plays compromises_from,
    plays targets_from,
    plays uses_from,
    plays indicates_to;

   # STIX Cyber Observables Entities
  Stix-Cyber-Observable sub Stix-Core-Object,
    abstract,
    has x_opencti_description,
    has x_opencti_score,
    plays stix-sighting-relationship_from,
    plays related-to_from,
    plays consists-of_to,
    plays based-on_to,
    plays related-to_to;

  Autonomous-System sub Stix-Cyber-Observable,
    has number,
    has name,
    has rir,
    plays belongs-to_to;

  Directory sub Stix-Cyber-Observable,
    has path,
    has path_enc,
    has ctime,
    has mtime,
    has atime,
    plays contains_from;

  Domain-Name sub Stix-Cyber-Observable,
    has value,
    plays resolves-to_to,
    plays src_to,
    plays dst_to;

  Email-Addr sub Stix-Cyber-Observable,
    has value,
    has display_name,
    plays belongs-to_from,
    plays from_to,
    plays sender_to,
    plays to_to,
    plays cc_to,
    plays bcc_to;

  Email-Message sub Stix-Cyber-Observable,
    has is_multipart,
    has attribute_date,
    has content_type,
    has message_id,
    has subject,
    has received_lines,
    has body,
    plays from_from,
    plays sender_from,
    plays to_from,
    plays cc_from,
    plays bcc_from,
    plays body-multipart_from,
    plays raw-email_from;

  Email-Mime-Part-Type sub Stix-Cyber-Observable,
    has body,
    has content_type,
    has content_disposition,
    plays body-raw_from,
    plays body-multipart_to;

  Hashed-Observable sub Stix-Cyber-Observable,
    abstract,
    has hashes;

  Artifact sub Hashed-Observable,
    has mime_type,
    has payload_bin,
    has url,
    has encryption_algorithm,
    has decryption_key,
    plays raw-email_to,
    plays body-raw_to;

  StixFile sub Hashed-Observable,
    has extensions,
    has size,
    has name,
    has name_enc,
    has magic_number_hex,
    has mime_type,
    has ctime,
    has mtime,
    has atime,
    plays parent-directory_from,
    plays contains_from,
    plays relation-content_from,
    plays parent-directory_to,
    plays contains_to,
    plays image_to;

  X509-Certificate sub Hashed-Observable,
    has is_self_signed,
    has version,
    has serial_number,
    has signature_algorithm,
    has issuer,
    has validity_not_before,
    has validity_not_after,
    has subject,
    has subject_public_key_algorithm,
    has subject_public_key_modulus,
    has subject_public_key_exponent,
    plays x509-v3-extensions_from;

  IPv4-Addr sub Stix-Cyber-Observable,
    has value,
    plays located-at_from,
    plays resolves-to_from,
    plays belongs-to_from,
    plays resolves-to_to,
    plays src_to,
    plays dst_to;

  IPv6-Addr sub Stix-Cyber-Observable,
    has value,
    plays located-at_from,
    plays resolves-to_from,
    plays belongs-to_from,
    plays resolves-to_to,
    plays src_to,
    plays dst_to;

  Mac-Addr sub Stix-Cyber-Observable,
    has value,
    plays resolves-to_to,
    plays src_to,
    plays dst_to;

  Mutex sub Stix-Cyber-Observable,
    has name;

  Network-Traffic sub Stix-Cyber-Observable,
    has extensions,
    has start,
    has end,
    has is_active,
    has src_port,
    has dst_port,
    has protocols,
    has src_byte_count,
    has dst_byte_count,
    has src_packets,
    has dst_packets,
    plays src_from,
    plays dst_from,
    plays src-payload_from,
    plays dst-payload_from,
    plays encapsulates_from,
    plays encapsulates-by_from,
    plays encapsulates_to,
    plays encapsulates-by_to,
    plays opened-connection_to;

  Process sub Stix-Cyber-Observable,
    has extensions,
    has is_hidden,
    has pid,
    has created_time,
    has cwd,
    has command_line,
    has environment_variables,
    plays opened-connection_from,
    plays creator-user_from,
    plays image_from,
    plays parent_from,
    plays child_from,
    plays parent_to,
    plays child_to;

  Software sub Stix-Cyber-Observable,
    has name,
    has cpe,
    has swid,
    has languages,
    has vendor,
    has version;

  Url sub Stix-Cyber-Observable,
    has value;

  User-Account sub Stix-Cyber-Observable,
    has extensions,
    has user_id,
    has credential,
    has account_login,
    has account_type,
    has display_name,
    has is_service_account,
    has is_privileged,
    has can_escalate_privs,
    has is_disabled,
    has account_created,
    has account_expires,
    has credential_last_changed,
    has account_first_login,
    has account_last_login,
    plays creator-user_to;

  Windows-Registry-Key sub Stix-Cyber-Observable,
    has attribute_key,
    has modified_time,
    has number_of_subkeys,
    plays values_from,
    plays creator-user_from;

  Windows-Registry-Value-Type sub Stix-Cyber-Observable,
    has name,
    has data,
    has data_type,
    plays values_to;

  X509-V3-Extensions-Type sub Stix-Cyber-Observable,
    has basic_constraints,
    has name_constraints,
    has policy_constraints,
    has key_usage,
    has extended_key_usage,
    has subject_key_identifier,
    has authority_key_identifier,
    has subject_alternative_name,
    has issuer_alternative_name,
    has subject_directory_attributes,
    has crl_distribution_points,
    has inhibit_any_policy,
    has private_key_usage_period_not_before,
    has private_key_usage_period_not_after,
    has certificate_policies,
    has policy_mappings,
    plays x509-v3-extensions_to;

  X-OpenCTI-Cryptographic-Key sub Stix-Cyber-Observable,
    has value;

  X-OpenCTI-Cryptocurrency-Wallet sub Stix-Cyber-Observable,
    has value;

  X-OpenCTI-Hostname sub Stix-Cyber-Observable,
    has value;

  X-OpenCTI-Text sub Stix-Cyber-Observable,
    has value;

  X-OpenCTI-User-Agent sub Stix-Cyber-Observable,
    has value;
