compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.4.cjs

packageExtensions:
  "@typescript-eslint/utils@*":
    dependencies:
      typescript: "*"            # satisfies: utils → typescript-estree peer "typescript"
  "eslint-config-airbnb-typescript@*":
    dependencies:
      eslint-plugin-import: "^2"  # satisfies: airbnb-typescript → airbnb-base peer "eslint-plugin-import"
