FROM node:16-alpine AS base

RUN set -ex; \
    corepack enable; \
    apk add --no-cache git tini gcc musl-dev python3 python3-dev postfix postfix-pcre make g++; \
    python3 -m ensurepip; \
    rm -rv /usr/lib/python*/ensurepip; \
    pip3 install --no-cache-dir --upgrade pip setuptools wheel; \
    ln -sf python3 /usr/bin/python;

WORKDIR /opt/test
COPY . .
RUN yarn add node-gyp
RUN yarn install --check-cache --inline-builds --network-timeout 300000 --immutable

CMD ["yarn", "test"]
