import React, { FunctionComponent, useState } from 'react';
import { ExpandLess, ExpandMore } from '@mui/icons-material';
import IconButton from '@mui/material/IconButton';
import { uniqueId } from 'lodash';
import { emptyFilled, truncate } from '../utils/String';
import MarkdownDisplay from './MarkdownDisplay';

interface ExpandableMarkdownProps {
  id?: string; // ID Required for Selenium Auto Test
  source: string | null;
  limit: number;
}

const ExpandableMarkdown: FunctionComponent<ExpandableMarkdownProps> = ({
  id, // ID Required for Selenium Auto Test
  source,
  limit,
}) => {
  const [expand, setExpand] = useState(false);
  const onClick = () => setExpand(!expand);
  const shouldBeTruncated = (source || '').length > limit;
  return (
    <span>
      <div style={{ position: 'relative' }}>
        {shouldBeTruncated && (
          <div style={{ position: 'absolute', top: -32, right: 0 }}>
            <IconButton onClick={onClick} size="large">
              {expand ? <ExpandLess /> : <ExpandMore />}
            </IconButton>
          </div>
        )}
        <div style={{ marginTop: 5 }}>
          <MarkdownDisplay
            id={id ?? uniqueId('autogenerated-')} // ID Required for Selenium Auto Test
            content={expand ? emptyFilled(source) : truncate(source, limit)}
            remarkGfmPlugin={true}
            commonmark={true}
          />
        </div>
        <div className="clearfix" />
      </div>
    </span>
  );
};

export default ExpandableMarkdown;
