mutation CreateExternalReference {
  createCyioExternalReference(
    input: {
      source_name: "Nitro"
      description: "2022 Z21 XL Pro Bass Boat"
      url: "https://www.nitro.com/bass/z21-xl-pro.build.html"
      external_id: "2022-Z21-XL-PRO"
      reference_purpose: reference
      media_type: "text/html"
    }
  ) {
    id
  }
}