query ListLabels {
  cyioLabels {
    pageInfo {
      globalCount
      startCursor
      endCursor
      hasPreviousPage
      hasNextPage
    }
    edges {
      node {
        id
        created
        modified
        name
        color
        description
      }
    }
  }
}