query NotesList {
  cyioNotes(first: 5) {
    pageInfo {
      globalCount
      startCursor
      endCursor
      hasNextPage
      hasPreviousPage
    }
    edges {
      node {
        id
        created
        modified
        labels {
          id
          name
          color
          description
        }
        abstract
        content
        authors
      }
    }
  }
}