const i18n = {
  messages: {
    fr: {
      // Titles
      'OpenCTI - Cyber threat intelligence platform': 'OpenCTI - Plateforme d\'analyse de la cybermenace',
      // Interface
      Search: 'Rechercher',
      'Do you want to delete this user?': 'Souahitez-vous supprimer cet utilisateur ?',
      'Do you want to delete this group?': 'Souahitez-vous supprimer ce groupe ?',
      'Do you want to delete this threat actor?': 'Souhaitez-vous supprimer cet acteur ?',
      'Do you want to delete this intrusion set?': 'Souhaitez-vous supprimer ce mode opératoire ?',
      'Do you want to delete this campaign?': 'Souhaitez-vous supprimer cette campagne ?',
      'Do you want to delete this incident?': 'Souhaitez-vous supprimer cet incident ?',
      'Do you want to delete this malware?': 'Souhaitez-vous supprimer ce code malveillant ?',
      'Do you want to delete this marking definition?': 'Souhaitez-vous supprimer ce marquage ?',
      'Do you want to delete this kill chain phase?': 'Souhaitez-vous supprimer cette étape de kill chain ?',
      Information: 'Informations',
      'Last reports': 'Derniers rapports',
      'Global parameters': 'Paramètres généraux',
      'External authentication': 'Authentification externe',
      Title: 'Titre',
      'Sender email address': 'Adresse mail d\'expédition',
      'Base URL': 'URL de base',
      Language: 'Langue',
      Automatic: 'Automatique',
      Registration: 'Inscription',
      'are updating...': 'modifient actuellement...',
      'is updating...': 'modifie actuellement...',
      // Form
      Create: 'Créer',
      Update: 'Modifier',
      Export: 'Exporter',
      Delete: 'Supprimer',
      Cancel: 'Annuler',
      Import: 'Importer',
      'This field is required': 'Ce champ est requis',
      'The value is too short': 'La valeur est trop courte',
      'The value is too long': 'La valeur est trop longue',
      'The value must be a number': 'La valeur doit être un nombre',
      'The value must be an email address': 'La valeur doit être une adresse email',
      'The values do not match': 'Les valeurs ne correspondent pas',
      'No available options': 'Aucune option disponible',
      'Create a user': 'Créer un utilisateur',
      'Update a user': 'Modifier un utilisateur',
      'Create a group': 'Créer un groupe',
      'Update a group': 'Modifier un groupe',
      'Create a threat actor': 'Créer un acteur',
      'Update a threat actor': 'Modifier un acteur',
      'Create an intrusion set': 'Créer un mode opératoire',
      'Update an intrusion set': 'Modifier un mode opératoire',
      'Create a campaign': 'Créer une campagne',
      'Update a campaign': 'Modifier une campagne',
      'Create an incident': 'Créer un incident',
      'Update an incident': 'Modifier un incident',
      'Create a malware': 'Créer un code malveillant',
      'Update a malware': 'Modifier un code malveillant',
      'New alias': 'Nouvel alias',
      'Create a marking definition': 'Créer un marquage',
      'Update a marking definition': 'Modifier un marquage',
      'Create a kill chain phase': 'Créer une étape de kill chain',
      'Update a kill chain phase': 'Modifier une étape de kill chain',
      'The password has been updated': 'Le mot de passe a été modifié',
      // Menu
      Dashboard: 'Tableau de bord',
      Knowledge: 'Connaissance',
      Explore: 'Explorer',
      Investigate: 'Investiguer',
      Sources: 'Sources',
      Settings: 'Paramètres',
      'Threat actors': 'Acteurs',
      Sectors: 'Secteurs',
      'Intrusion sets': 'Modes opératoires',
      Campaigns: 'Campagnes',
      Incidents: 'Incidents',
      Malwares: 'Codes malveillants',
      Tools: 'Outils',
      Vulnerabilities: 'Vulnérabilités',
      Identities: 'Identités',
      Reports: 'Rapports',
      Overview: 'Aperçu',
      Relationships: 'Relations',
      Entities: 'Entités',
      Observables: 'Observables',
      Parameters: 'Paramètres',
      Users: 'Utilisateurs',
      Groups: 'Groupes',
      Global: 'Global',
      'TTPs frameworks': 'Frameworks de TTP',
      // User
      'Sign in': 'S\'identifier',
      Email: 'Email',
      Password: 'Mot de passe',
      Logout: 'Se déconnecter',
      Profile: 'Profil',
      Admin: 'Admin',
      // Properties
      'Sort by': 'Trier par',
      'Filter by': 'Filtrer par',
      Name: 'Nom',
      Description: 'Description',
      'Creation date': 'Date de création',
      'Modification date': 'Date de modification',
      'Updated the': 'Mis à jour le',
      Creator: 'Créateur',
      Marking: 'Marquage',
      'Kill chain phases': 'Phases de kill chain',
      Definition: 'Définition',
      Level: 'Niveau',
      Color: 'Couleur',
      Type: 'Type',
      'Email address': 'Adresse email',
      Username: 'Nom d\'utilisateur',
      Firstname: 'Prénom',
      Lastname: 'Nom',
      Permissions: 'Permissions',
      Members: 'Membres',
      Confirmation: 'Confirmation',
      'Kill chain': 'Kill chain',
      'Phase name': 'Nom de l\'étape',
      'Kill chain name': 'Nom de la kill chain',
      Order: 'Ordre',
      // Statistics
      'Total entities': 'Nombre d\'entités',
      'Total observables': 'Nombre d\'observables',
      'Total reports': 'Nombre de rapports',
      'Total investigations': 'Nombre d\'investigations',
      'Ingested entities': 'Entités stockées',
      'last 24h': 'dernières 24h',
    },
  },
};

export default i18n;
