const i18n = {
  messages: {
    fr: {
      // Titles
      'OpenCTI - Cyber threat intelligence platform': 'OpenCTI - Plateforme d\'analyse de la cybermenace',
      // Interface
      Search: 'Rechercher',
      'Do you want to delete this malware?': 'Souhaitez-vous supprimer ce code malveillant ?',
      Information: 'Informations',
      'Last reports': 'Derniers rapports',
      // Form
      Create: 'Créer',
      Update: 'Modifier',
      Export: 'Exporter',
      Delete: 'Supprimer',
      Cancel: 'Annuler',
      Import: 'Importer',
      'This field is required': 'Ce champ est requis',
      'The value is too short': 'La valeur est trop courte',
      'The value is too long': 'La valeur est trop longue',
      'No available options': 'Aucune option disponible',
      'Create a malware': 'Créer un code malveillant',
      'Update a malware': 'Modifier un code malveillant',
      'New alias': 'Nouvel alias',
      // Menu
      Dashboard: 'Tableau de bord',
      Knowledge: 'Connaissance',
      Explore: 'Explorer',
      Investigate: 'Investiguer',
      Sources: 'Sources',
      Settings: 'Paramètres',
      'Threat actors': 'Acteurs',
      Sectors: 'Secteurs',
      'Intrusion sets': 'Modes opératoires',
      Campaigns: 'Campagnes',
      Incidents: 'Incidents',
      Malwares: 'Codes malveillants',
      Tools: 'Outils',
      Vulnerabilities: 'Vulnérabilités',
      Identities: 'Identités',
      Reports: 'Rapports',
      Overview: 'Aperçu',
      Relationships: 'Relations',
      Entities: 'Entités',
      Observables: 'Observables',
      // User
      'Sign in': 'S\'identifier',
      Email: 'Email',
      Password: 'Mot de passe',
      Logout: 'Se déconnecter',
      Profile: 'Profil',
      Admin: 'Admin',
      // Properties
      'Sort by': 'Trier par',
      'Filter by': 'Filtrer par',
      Name: 'Nom',
      Description: 'Description',
      'Creation date': 'Date de création',
      'Modification date': 'Date de modification',
      'Updated the': 'Mis à jour le',
      Creator: 'Créateur',
      Marking: 'Marquage',
      'Killchain phases': 'Phases de killchain',
      // Statistics
      'Total entities': 'Nombre d\'entités',
      'Total observables': 'Nombre d\'observables',
      'Total reports': 'Nombre de rapports',
      'Total investigations': 'Nombre d\'investigations',
      'Ingested entities': 'Entités stockées',
      'last 24h': 'dernières 24h',
    },
  },
};

export default i18n;
