import { describe, expect, it, vi } from 'vitest';
import { filterTargetByExisting } from '../../../src/database/middleware';
import { testContext } from '../../utils/testQuery';

// No RELATION_OBJECT_MARKING relations are generated by this fuzzer, so cleanMarkings is mocked out.
vi.mock('../../../src/utils/markingDefinition-utils', () => ({
  cleanMarkings: vi.fn().mockResolvedValue([]),
}));

const ATTACK_PATTERN = 'Attack-Pattern';
// A small, non-schema-registered set of relation "types" so isSingleRelationsRef/isStixRefRelationship
// always resolve to false, keeping the fuzz focused purely on the matching/dedup logic under test
// (the single-meta and self-meta branches are untouched by the fix and exercised separately elsewhere).
const RELATION_TYPES = ['related-to', 'related-to-x', 'derived-from'];

// Simple seeded PRNG (mulberry32) for reproducible fuzz runs.
function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

type Rng = () => number;
const pick = <T>(rng: Rng, arr: T[]): T => arr[Math.floor(rng() * arr.length)];

// Small id alphabet (with intentional overlap between sources/targets) to maximize the chance of
// exercising shared-key buckets, duplicates, and both matching and non-matching cases.
const ID_POOL = Array.from({ length: 12 }).map((_, i) => `id-${i}`);

const buildDep = (rng: Rng) => {
  const dated = rng() < 0.35;
  const internalId = pick(rng, ID_POOL);
  const entityType = pick(rng, RELATION_TYPES);
  return {
    _index: 'test_index',
    internal_id: internalId,
    entity_type: ATTACK_PATTERN,
    name: `entity-${internalId}`,
    i_relation: {
      internal_id: `rel-${internalId}-${entityType}-${Math.floor(rng() * 1e9)}`,
      entity_type: entityType,
      fromId: 'some-from-id',
      fromType: ATTACK_PATTERN,
      toId: internalId,
      toType: ATTACK_PATTERN,
      ...(dated ? { start_time: '2020-01-01T00:00:00.000Z' } : {}),
    },
  };
};

const ed = (date?: string) => date === undefined;
const noDateRef = (e: { start_time?: string }) => ed(e.start_time);

// Brute-force reference implementation: mirrors exactly what the pre-fix O(n x m) algorithm computed for
// the matching decision (direct field comparison, no string-key concatenation) plus the same cache-dedup
// semantics (first-seen composite id wins). This is independent of filterTargetByExisting's internals,
// so agreement between the two is a genuine differential check, not a tautology.
const bruteForceFilter = (sources: any[], targets: any[]) => {
  const cache = new Set<string>();
  const kept: string[] = [];
  for (const source of sources) {
    const hasExistingTarget = targets.some((t) => (
      t.internal_id === source.internal_id
      && t.i_relation.entity_type === source.i_relation.entity_type
      && noDateRef(t.i_relation)
    ));
    const id = `${source.i_relation.entity_type}-${source.internal_id}`;
    if (!hasExistingTarget && !cache.has(id)) {
      kept.push(source.i_relation.internal_id);
      cache.add(id);
    }
  }
  return kept.sort();
};

const targetEntity = { internal_id: 'target-entity', entity_type: ATTACK_PATTERN } as any;

describe('filterTargetByExisting randomized differential fuzz (real impl vs brute-force reference)', () => {
  const SEEDS = 50;
  for (let seedIndex = 0; seedIndex < SEEDS; seedIndex += 1) {
    it(`matches the brute-force reference implementation for random case #${seedIndex}`, async () => {
      const rng = mulberry32(seedIndex * 7919 + 13);
      const sourceCount = Math.floor(rng() * 40);
      const targetCount = Math.floor(rng() * 40);
      const sources = Array.from({ length: sourceCount }).map(() => buildDep(rng));
      const targets = Array.from({ length: targetCount }).map(() => buildDep(rng));

      const expected = bruteForceFilter(sources, targets);
      const sourcesDependencies = { i_relations_from: sources, i_relations_to: [] } as any;
      const targetDependencies = { i_relations_from: targets, i_relations_to: [] } as any;
      const { redirects } = await filterTargetByExisting(testContext, targetEntity, 'from', sourcesDependencies, targetDependencies);
      const actual = redirects.map((r) => r.i_relation.internal_id).sort();

      expect(actual).toEqual(expected);
    });
  }
});
