import { describe, expect, it, vi } from 'vitest';
import { filterTargetByExisting } from '../../../src/database/middleware';
import { testContext } from '../../utils/testQuery';

// No RELATION_OBJECT_MARKING relations are generated by this dataset, so cleanMarkings is mocked out.
vi.mock('../../../src/utils/markingDefinition-utils', () => ({
  cleanMarkings: vi.fn().mockResolvedValue([]),
}));

const ATTACK_PATTERN = 'Attack-Pattern';
const targetEntity = { internal_id: 'target-entity', entity_type: ATTACK_PATTERN } as any;

// Realistic mix of STIX relationship types an Attack-Pattern accumulates relations through.
const RELATION_TYPES = [
  'uses',
  'targets',
  'related-to',
  'indicates',
  'mitigates',
  'detects',
  'subtechnique-of',
];

// Simple seeded PRNG (mulberry32) for a reproducible, non-adversarial "real-world-shaped" dataset.
function mulberry32(seed: number) {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Builds `count` relation dependencies to DISTINCT related entities (unlike the pathological
 * same-key stress case, this mirrors the actual T1027 incident: ~78k genuinely different
 * relationships, not tens of thousands of literal duplicates to one single entity).
 * `datedRatio` controls what fraction carry a start_time/stop_time (excluded from "already exists" matches).
 * `overlapPool`, when provided, is sampled for a fraction of entries so some relations legitimately
 * point at entities the other side also relates to (the real case that makes merge-dedup necessary).
 */
const buildRealisticDependencies = (
  rng: () => number,
  count: number,
  idPrefix: string,
  datedRatio = 0.1,
  overlapPool?: string[],
  overlapRatio = 0,
) => {
  return Array.from({ length: count }).map((_, index) => {
    const useOverlap = overlapPool && overlapPool.length > 0 && rng() < overlapRatio;
    const internalId = useOverlap
      ? overlapPool[Math.floor(rng() * overlapPool.length)]
      : `${idPrefix}-entity-${index}`;
    const entityType = RELATION_TYPES[Math.floor(rng() * RELATION_TYPES.length)];
    const dated = rng() < datedRatio;
    return {
      _index: 'test_index',
      internal_id: internalId,
      entity_type: ATTACK_PATTERN,
      name: `related-entity-${internalId}`,
      i_relation: {
        internal_id: `${idPrefix}-rel-${index}`,
        entity_type: entityType,
        fromId: 'source-attack-pattern',
        fromType: ATTACK_PATTERN,
        toId: internalId,
        toType: ATTACK_PATTERN,
        ...(dated ? { start_time: '2020-01-01T00:00:00.000Z' } : {}),
      },
    };
  });
};

// Frozen, verbatim copy of the pre-fix (commit 3e1529d531^) algorithm: R.find-equivalent linear scan
// over the full targets array per source, plus a linear cache array scan. Kept local (not imported)
// so this file remains a faithful "before" snapshot even if middleware.ts changes further in the future.
const noDateRef = (e: {
  start_time?: string;
  stop_time?: string;
  first_seen?: string;
  last_seen?: string;
}) =>
  e.first_seen === undefined &&
  e.last_seen === undefined &&
  e.start_time === undefined &&
  e.stop_time === undefined;
const preFixFilterTargetByExisting = (sources: any[], targets: any[]) => {
  const cache: string[] = [];
  const filtered: any[] = [];
  for (let index = 0; index < sources.length; index += 1) {
    const source = sources[index];
    const finder = (t: any) =>
      t.internal_id === source.internal_id &&
      t.i_relation.entity_type === source.i_relation.entity_type &&
      noDateRef(t.i_relation);
    const found = targets.find(finder);
    const id = `${source.i_relation.entity_type}-${source.internal_id}`;
    if (!found && !cache.includes(id)) {
      filtered.push(source);
      cache.push(id);
    }
  }
  return filtered;
};

const runComparison = async (label: string, sources: any[], targets: any[]) => {
  const sourcesDependencies = { i_relations_from: sources, i_relations_to: [] } as any;
  const targetDependencies = { i_relations_from: targets, i_relations_to: [] } as any;

  const newStart = performance.now();
  const { redirects } = await filterTargetByExisting(
    testContext,
    targetEntity,
    'from',
    sourcesDependencies,
    targetDependencies,
  );
  const newElapsed = performance.now() - newStart;

  const oldStart = performance.now();
  const oldFiltered = preFixFilterTargetByExisting(sources, targets);
  const oldElapsed = performance.now() - oldStart;

  const newIds = redirects.map((r) => r.i_relation.internal_id).sort();
  const oldIds = oldFiltered.map((r) => r.i_relation.internal_id).sort();

  // oxlint-disable-next-line no-console
  console.log(
    `[REAL-WORLD-SCALE] ${label}: new=${newElapsed.toFixed(2)}ms, old=${oldElapsed.toFixed(2)}ms, speedup=${(oldElapsed / Math.max(newElapsed, 0.001)).toFixed(1)}x, kept=${newIds.length}/${sources.length}`,
  );

  return { newElapsed, oldElapsed, newIds, oldIds };
};

describe('filterTargetByExisting real-world-scale comparison (T1027 incident shape)', () => {
  it('matches the T1027 incident: target has 77,964 DISTINCT relations, duplicate source has 2,000 relations with partial overlap', async () => {
    const rng = mulberry32(42);
    const targets = buildRealisticDependencies(rng, 77964, 'target');
    // Duplicate entity (the one being merged away) has its own, smaller set of relations,
    // ~25% of which happen to point at entities the target already relates to (the real reason
    // merge-dedup is needed at all - otherwise every merge would just be a no-op union).
    const overlapPool = targets.slice(0, 20000).map((t) => t.internal_id);
    const sources = buildRealisticDependencies(rng, 2000, 'source', 0.1, overlapPool, 0.25);

    const { newElapsed, oldElapsed, newIds, oldIds } = await runComparison(
      'target=77964 distinct, source=2000 (25% overlap)',
      sources,
      targets,
    );

    expect(newIds).toEqual(oldIds); // correctness: identical decision set as the pre-fix algorithm
    expect(newElapsed).toBeLessThan(2000); // new: comfortably sub-second/low-second even at this scale
    expect(oldElapsed).toBeGreaterThan(newElapsed); // sanity: old is still slower on real-shaped data too
  }, 120000);

  it('both sides large: two comparably-sized duplicates (40,000 distinct relations each, partial overlap)', async () => {
    const rng = mulberry32(1337);
    const targets = buildRealisticDependencies(rng, 40000, 'target');
    const overlapPool = targets.slice(0, 15000).map((t) => t.internal_id);
    const sources = buildRealisticDependencies(rng, 40000, 'source', 0.1, overlapPool, 0.3);

    const { newElapsed, oldElapsed, newIds, oldIds } = await runComparison(
      'target=40000 distinct, source=40000 distinct (30% overlap)',
      sources,
      targets,
    );

    expect(newIds).toEqual(oldIds);
    expect(newElapsed).toBeLessThan(2000);
    expect(oldElapsed).toBeGreaterThan(newElapsed);
  }, 180000);
});
