import { logApp } from '../../../config/conf';
import { draftWorkspaceEditAuthorizedMembers, validateDraftWorkspace } from '../../draftWorkspace/draftWorkspace-domain';
import type { AsyncActionSlot, Context } from '../types/workflow-types';
import { z } from 'zod';

export type ActionFunction<TContext extends Context = Context> = (executionContext: TContext, params?: any) => Promise<void> | void;

export interface ActionDefinition {
  fn: ActionFunction;
  paramsSchema?: z.ZodTypeAny;
  /** Execution positions this action type is allowed in. Omit to allow both. */
  allowedModes?: ('sync' | 'async')[];
}

// Zod schema for an individual background task action step (mirrors BackgroundTask actions[])
const bulkTaskActionSchema = z.object({
  type: z.string(),
  context: z.record(z.string(), z.unknown()).optional(),
});

export const asyncBulkActionParamsSchema = z.object({
  scope: z.string(),
  description: z.string().optional(),
  actions: z.array(bulkTaskActionSchema).min(1),
  failOnAnyError: z.boolean().optional(),
});

export const ActionRegistry: Record<string, ActionFunction> = {
  // actions examples:
  log: async (executionContext, params) => {
    logApp.info(`[Action: LOG] Context: ${JSON.stringify(executionContext)} | Message: ${params?.message || 'No message'}`);
  },
  validateDraft: async (executionContext) => {
    const { entity, user, context } = executionContext;
    await validateDraftWorkspace(context, user, entity.id);
  },
  updateAuthorizedMembers: async (executionContext, params) => {
    const { entity, user, context } = executionContext;
    await draftWorkspaceEditAuthorizedMembers(context, user, entity.id, params?.authorized_members);
  },
  /**
   * asyncBulkAction: spawns a BackgroundTask + Work via createListTask.
   * The slot is pushed onto ctx.pendingAsyncSlots (mutable accumulator).
   * createListTask is injected at trigger time via ctx.__createListTask to avoid
   * a direct import cycle between the registry and backgroundTask-common.js.
   */
  asyncBulkAction: async (executionContext, params) => {
    const { entity, user, context, pendingAsyncSlots, __createListTask, __workflowInstanceId } = executionContext as any;
    if (typeof __createListTask !== 'function') {
      logApp.error('[asyncBulkAction] __createListTask not injected into context — action skipped');
      return;
    }

    const { scope, description, actions, failOnAnyError = true } = params ?? {};

    // Resolve entity IDs for the bulk task
    const ids: string[] = entity?.id ? [entity.id] : [];

    const task = await __createListTask(context, user, {
      scope,
      description: description ?? 'Workflow async bulk action',
      actions,
      ids,
      workflow_instance_id: __workflowInstanceId,
      // workflow_action_id is generated by the domain layer and set on the task after this call
      // (slot id is the source of truth; domain sets it when building pendingTransition)
    });

    const slot: AsyncActionSlot = {
      id: task.id, // Temporary: domain will overwrite with its own UUID; task keeps workflow_action_id
      workId: task.work_id ?? '',
      type: 'asyncBulkAction',
      status: 'pending',
    };

    if (Array.isArray(pendingAsyncSlots)) {
      pendingAsyncSlots.push({ ...slot, _taskId: task.id, _failOnAnyError: failOnAnyError });
    }
  },
};

export const ActionDefinitions: Record<string, ActionDefinition> = {
  log: {
    fn: ActionRegistry.log,
    paramsSchema: z.object({ message: z.string().optional() }).optional(),
    allowedModes: ['sync', 'async'],
  },
  validateDraft: {
    fn: ActionRegistry.validateDraft,
    paramsSchema: z.object({}).optional(),
    allowedModes: ['sync', 'async'],
  },
  updateAuthorizedMembers: {
    fn: ActionRegistry.updateAuthorizedMembers,
    paramsSchema: z.object({
      authorized_members: z.array(z.object({
        id: z.string(),
        access_right: z.string(),
      })).optional(),
    }).optional(),
    allowedModes: ['sync', 'async'],
  },
  asyncBulkAction: {
    fn: ActionRegistry.asyncBulkAction,
    paramsSchema: asyncBulkActionParamsSchema,
    allowedModes: ['async'], // Only valid in asyncActions[], never in syncActions[]
  },
};
