name: Assign labels on PR from an organization
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting labels
        uses: FiligranHQ/auto-label@1.0.0
        with:
          labels_by_organization: "{\"FiligranHQ\":[\"filigran team\"]}"