name: OpenCTI CD Rolling
# This workflow prepare all artifact for the rolling images
# Build on each merge on master

on:
  push:
    branches:
      # FIXME change to master before merge.
      - issue/16821-docker-wf

jobs:
  # -----------------------
  # Standard default images
  # -----------------------
  build-platform-standard:
    name: Build platform (standard)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-platform
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true

  build-worker-standard:
    name: Build worker (standard)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-worker
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true

  generate-sbom-platform-standard:
    name: Generate SBOM (platform standard)
    runs-on: ubuntu-latest
    needs: [build-platform-standard]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}"]'
          image_name: "filigran/platform"
          source: "artifact"
          artifact_name: "docker-image-opencti-platform"

  generate-sbom-worker-standard:
    name: Generate SBOM (worker standard)
    runs-on: ubuntu-latest
    needs: [build-worker-standard]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}"]'
          image_name: "filigran/worker"
          source: "artifact"
          artifact_name: "docker-image-opencti-worker"

  # -----------------------
  # UBI 9 images
  # -----------------------
  build-platform-ubi9:
    name: Build platform (UBI9)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-platform
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true
          docker_image_suffix: "_ubi9"

  build-worker-ubi9:
    name: Build worker (UBI9)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-worker
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true
          docker_image_suffix: "_ubi9"

  generate-sbom-platform-ubi9:
    name: Generate SBOM (platform UBI9)
    runs-on: ubuntu-latest
    needs: [build-platform-ubi9]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}"]'
          image_name: "filigran/platform"
          source: "artifact"
          artifact_name: "docker-image-opencti-platform_ubi9"

  generate-sbom-worker-ubi9:
    name: Generate SBOM (worker UBI9)
    runs-on: ubuntu-latest
    needs: [build-worker-ubi9]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}"]'
          image_name: "filigran/worker"
          source: "artifact"
          artifact_name: "docker-image-opencti-worker_ubi9"

  # -----------------------
  # FIPS 9 images
  # -----------------------
  build-platform-fips:
    name: Build platform (FIPS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-platform
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true
          docker_image_suffix: "_fips"

  build-worker-fips:
    name: Build worker (FIPS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-worker
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true
          docker_image_suffix: "_fips"

  generate-sbom-platform-fips:
    name: Generate SBOM (platform FIPS)
    runs-on: ubuntu-latest
    needs: [build-platform-fips]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}"]'
          image_name: "filigran/platform"
          source: "artifact"
          artifact_name: "docker-image-opencti-platform_fips"

  generate-sbom-worker-fips:
    name: Generate SBOM (worker FIPS)
    runs-on: ubuntu-latest
    needs: [ build-worker-fips ]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}"]'
          image_name: "filigran/worker"
          source: "artifact"
          artifact_name: "docker-image-opencti-worker_fips"

  upload-artifacts:
    name: Upload all artifacts
    runs-on: ubuntu-latest
    needs: [generate-sbom-platform-standard, generate-sbom-platform-ubi9, generate-sbom-platform-fips, generate-sbom-worker-standard, generate-sbom-worker-ubi9, generate-sbom-worker-fips]
    steps:
      - name: Download all SBOM artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: sbom-*
          path: artifacts/

      - name: Download all Docker artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: docker-image-*
          path: artifacts/

      - name: Upload consolidated artifacts
        uses: actions/upload-artifact@v7
        with:
          name: opencti-rolling-${{ github.sha }}
          path: artifacts/
          retention-days: 7
