name: Check signed commits in PR 
on: [pull_request,pull_request_target]
jobs:
  check-signed-commits:
    name: Check signed commits in PR
    runs-on: ubuntu-latest
    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
        with:
          comment: |
            Thank you for your contribution, but we need you to sign your commits. Please see https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits