name: OpenCTI Build Images and SBOM on Merge

on:
  push:
    branches:
      # FIXME change to master before merge.
      - issue/16821-docker-wf

jobs:
  build-platform-standard:
    name: Build platform (standard)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-platform
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true

  build-worker-standard:
    name: Build worker (standard)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-worker
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true

  build-platform-ubi9:
    name: Build platform (UBI9)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-platform
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true
          docker_image_suffix: "_ubi9"

  build-worker-ubi9:
    name: Build worker (UBI9)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-worker
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true
          docker_image_suffix: "_ubi9"

  build-platform-fips:
    name: Build platform (FIPS)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/docker-build-platform
        with:
          checkout_ref: ${{ github.sha }}
          client_python_local: true
          docker_image_suffix: "_fips"

  generate-sbom-platform-standard:
    name: Generate SBOM (platform standard)
    runs-on: ubuntu-latest
    needs: [build-platform-standard, build-worker-standard, build-platform-ubi9, build-worker-ubi9, build-platform-fips]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}"]'

  generate-sbom-platform-ubi9:
    name: Generate SBOM (platform UBI9)
    runs-on: ubuntu-latest
    needs: [build-platform-standard, build-worker-standard, build-platform-ubi9, build-worker-ubi9, build-platform-fips]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}-ubi9"]'

  generate-sbom-platform-fips:
    name: Generate SBOM (platform FIPS)
    runs-on: ubuntu-latest
    needs: [build-platform-standard, build-worker-standard, build-platform-ubi9, build-worker-ubi9, build-platform-fips]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}-fips"]'

  generate-sbom-worker-standard:
    name: Generate SBOM (worker standard)
    runs-on: ubuntu-latest
    needs: [build-platform-standard, build-worker-standard, build-platform-ubi9, build-worker-ubi9, build-platform-fips]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}"]'

  generate-sbom-worker-ubi9:
    name: Generate SBOM (worker UBI9)
    runs-on: ubuntu-latest
    needs: [build-platform-standard, build-worker-standard, build-platform-ubi9, build-worker-ubi9, build-platform-fips]
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/generate-sbom
        with:
          tags: '["${{ github.sha }}-ubi9"]'

  upload-artifacts:
    name: Upload all artifacts
    runs-on: ubuntu-latest
    needs: [generate-sbom-platform-standard, generate-sbom-platform-ubi9, generate-sbom-platform-fips, generate-sbom-worker-standard, generate-sbom-worker-ubi9]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Upload consolidated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencti-release-${{ github.sha }}
          path: artifacts/
          retention-days: 7
