name: OpenCTI CI
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/docs/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'docs/docs/**'

jobs:
  wf-build-image:
      name: Build image
      if: github.event_name == 'workflow_dispatch'
      uses: ./.github/workflows/ci-docker-build.yml
      with:
        checkout_ref: ${{ github.event_name == 'pull_request'  && format('refs/pull/{0}/merge', github.event.pull_request.number) || github.sha }}
        dockerfile_target: testing
        client_python_local: true
      secrets: inherit

  wf-backend-test:
      name: Backend
      uses: ./.github/workflows/ci-test-backend.yml
      needs: [wf-build-image]
      if: github.event_name == 'workflow_dispatch'
      with:
        checkout_ref: ${{ github.event_name == 'pull_request'  && format('refs/pull/{0}/merge', github.event.pull_request.number) || github.sha }}
        run-id: ${{ github.run_id }}
      secrets: inherit

  wf-frontend-test:
      name: Frontend
      if: github.event_name == 'workflow_dispatch'
      uses: ./.github/workflows/ci-test-frontend.yml
      with:
        checkout_ref: ${{ github.event_name == 'pull_request'  && format('refs/pull/{0}/merge', github.event.pull_request.number) || github.sha }}
      secrets: inherit

  wf-client-python-test:
      name: Client Python
      uses: ./.github/workflows/ci-test-client-python.yml
      needs: [ wf-build-image]
      if: github.event_name == 'workflow_dispatch'
      with:
        checkout_ref: ${{ github.event_name == 'pull_request'  && format('refs/pull/{0}/merge', github.event.pull_request.number) || github.sha }}
      secrets: inherit

  wf-license-check:
      name: License check
      if: github.event_name == 'workflow_dispatch'
      uses: ./.github/workflows/ci-license-check.yml
      with:
        checkout_ref: ${{ github.event_name == 'pull_request'  && format('refs/pull/{0}/merge', github.event.pull_request.number) || github.sha }}
      secrets: inherit
