name: PR conventions checks
# This workflow should work for forks without requiring manual run.
# It avoids jobs that require elevated write permissions/secrets on fork PRs; PR-write operations should live in a separate workflow.

on:
  pull_request_target:
    types: [opened, edited, reopened, ready_for_review, synchronize]
jobs:
  check-pr-title-convention:
    name: Check that PR title follows convention
    if: ${{ github.event.pull_request.user.login != 'renovate[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: Slashgear/action-check-pr-title@76166c63ec0b25cdbe693e5e972e83ca186313fb
        with:
          regexp: '^(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)(\([a-z0-9._/-]+\))?!?: .+ \(#[0-9]+(, ?#[0-9]+)*\)$'
          flags: "gm"
          helpMessage: "Format: 'type(scope?): description (#issue)' for example 'docs: updating a doc page (#1234)'. see https://github.com/OpenCTI-Platform/opencti/blob/master/CONTRIBUTING.md#how-can-you-contribute"

  check-signed-commits:
    name: Check signed commits in PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Information about how to sign commits see https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
        # "with comment" below does not work for forks.
        run: |
          echo "If you need to sign commits, Please see https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits"
      - name: Check signed commits in PR on fail see above information.
        uses: 1Password/check-signed-commits-action@v1
        with:
          comment: |
            Thank you for your contribution, but we need you to sign your commits. Please see https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits