name: (WIP) Deploy feature branch on staging (next gen)                                                                   
on:                                                                                                       
  workflow_dispatch:                                                                                      
    inputs:                                                                                               
                                                                                                          
jobs:                                                                                                     
  wf-build-image:                                                                                         
      name: Build image                                                                                   
      uses: ./.github/workflows/ci-docker-build.yml                                                       
      with:                                                                                               
        image_tag: ${{ github.ref_name }}                                                                 
        publish_to_registry: true                                                                         
      secrets: inherit 
