import {
  aliases,
  authorizedMembers,
  baseType,
  createdAt,
  creators,
  draftChange,
  draftIds,
  entityLocationType,
  entityType,
  files,
  iAliasedIds,
  id,
  identityClass,
  internalId,
  lang,
  modified,
  parentTypes,
  relationshipType,
  revoked,
  standardId,
  updatedAt,
  xOpenctiStixIds,
  xOpenctiType,
} from '../schema/attribute-definition';

export const INTERNAL_ATTRIBUTES = [
  // ID
  id.name,
  internalId.name,
  standardId.name,
  draftIds.name,
  draftChange.name,
  xOpenctiStixIds.name,
  iAliasedIds.name,
  // Auditing
  createdAt.name,
  updatedAt.name,
  modified.name,
  // Technical
  entityType.name,
  parentTypes.name,
  entityLocationType.name,
  baseType.name,
  relationshipType.name,
  xOpenctiType.name,
  identityClass.name,
  creators.name,
  files.name,
  lang.name,
  revoked.name,
  aliases.name,
  'refreshed_at',
  'metrics',
  'fromType',
  'toType',
  'i_inference_weight',
  'content_mapping',
  'caseTemplate',
  'default_dashboard',
  'default_hidden_types',
  'grantable_groups',
  authorizedMembers.name,
  'authorized_authorities',
  'precision',
  'pattern_version',
  'connections',
  'i_attributes',
  'pir_information',
  // X - Mitre
  'x_opencti_graph_data',
  // X - OpenCTI
  'x_opencti_workflow_id',
  'x_opencti_detection',
  'x_opencti_threat_hunting',
  'x_opencti_log_sources',
  'x_opencti_firstname',
  'x_opencti_lastname',
  'x_opencti_modified_at',
  // CVSS 3
  'x_opencti_cvss_base_severity',
  'x_opencti_cvss_attack_vector',
  'x_opencti_cvss_attack_complexity',
  'x_opencti_cvss_privileges_required',
  'x_opencti_cvss_user_interaction',
  'x_opencti_cvss_scope',
  'x_opencti_cvss_confidentiality_impact',
  'x_opencti_cvss_integrity_impact',
  'x_opencti_cvss_availability_impact',
  'x_opencti_cvss_exploit_code_maturity',
  'x_opencti_cvss_remediation_level',
  'x_opencti_cvss_report_confidence',
  'x_opencti_cvss_temporal_score',
  // CVSS 2
  'x_opencti_cvss_v2_access_vector',
  'x_opencti_cvss_v2_access_complexity',
  'x_opencti_cvss_v2_authentication',
  'x_opencti_cvss_v2_confidentiality_impact',
  'x_opencti_cvss_v2_integrity_impact',
  'x_opencti_cvss_v2_availability_impact',
  'x_opencti_cvss_v2_exploitability',
  'x_opencti_cvss_v2_remediation_level',
  'x_opencti_cvss_v2_report_confidence',
  'x_opencti_cvss_v2_temporal_score',
  // CVSS 4
  'x_opencti_cvss_v4_base_severity',
  'x_opencti_cvss_v4_attack_vector',
  'x_opencti_cvss_v4_attack_complexity',
  'x_opencti_cvss_v4_attack_requirements',
  'x_opencti_cvss_v4_privileges_required',
  'x_opencti_cvss_v4_user_interaction',
  'x_opencti_cvss_v4_confidentiality_impact_v',
  'x_opencti_cvss_v4_confidentiality_impact_s',
  'x_opencti_cvss_v4_integrity_impact_v',
  'x_opencti_cvss_v4_integrity_impact_s',
  'x_opencti_cvss_v4_availability_impact_v',
  'x_opencti_cvss_v4_availability_impact_s',
  'x_opencti_cvss_v4_exploit_maturity',
  'x_opencti_cwe',
  'x_opencti_first_seen_active',
  'x_opencti_product',
  'x_opencti_additional_names',
  // Decay internal fields on Indicator
  'decay_next_reaction_date',
  'decay_base_score',
  'decay_base_score_date',
  'decay_history',
  'decay_applied_rule',
  // Opinions
  'opinions_metrics',
];

export const INTERNAL_REFS = [
  'objectOrganization'
];
